### ISSUE TITLE
Redundant Collections Sidebar Display

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1004]
When you navigate to the Collections landing page and select `Resources` from the sidebar, both `Resources` and `General` are emboldened and underlined, instead of just `Resources` alone.

<img width="942" alt="collections" src="https://user-images.githubusercontent.com/25825222/39154787-119c3392-4715-11e8-9a22-934a131e51d6.png">

**Comment by SMaxOwok** [comment]
This should be fixed in master.

https://github.com/ManifoldScholar/manifold/commit/340a84bb1ac72c4b528feee74d8d7de8ea2c5c5c
