### ISSUE TITLE
Excessive Rows Included in Bulk Load CSV

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1005]
When using a CSV file (Mac Excel 2011 export) for the bulk load, the export created 897 rows, which Manifold tried to ingest. After it successfully ingested the first 16 rows of resources (accounting for all those I was trying to load) I simply hit the back button to get off the screen. That worked, but if I hadn't I would have had to wait for a while.

**Comment by SMaxOwok** [comment]
Is the issue that the other 881 columns were blank?

**Comment by tsmyre** [comment]
Yes, but like the issue I opened an closed about character encoding, this is an Excel thing, not a Manifold thing. I can easily open in a text editor and fix. But I am wondering if there's a way for the system to simply eliminate entirely blank rows?

**Comment by SMaxOwok** [comment]
I think this should be relatively easy to address!

Also the encoding issue is fixed in master.  Excel CSVs should be ok now.
