### ISSUE TITLE
Should "Email" and "Twitter" footer links be editable?

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1019]
At the moment, the `Twitter` and `Email` links in the footer are hardcoded to be relevant to `Manifold` and not the instance.  

Should these be editable? 

 If not, should they maybe be moved closer to the `Powered by Manifold` block or out of the left links group?

If I make a handful of pages and display them in the footer, they're grouped with these links, which is a little misleading because they are _not_ relevant to the installation.  As such, it seems there is no way to contact the individual installation's owner.

![screen shot 2018-05-01 at 9 47 35 am](https://user-images.githubusercontent.com/8389445/39482698-ee7d4124-4d24-11e8-848d-33170fa858ab.png)

**Comment by mkgold** [comment]
Good point. I'd say they should be editable.

**Comment by SMaxOwok** [comment]
![screen shot 2018-05-09 at 1 04 11 pm](https://user-images.githubusercontent.com/8389445/39836823-80cb67da-5389-11e8-8866-aff3cb33940d.png)
WIP screen.  I think @laelito wanted to adjust a bit.

**Comment by zdavis** [comment]
Design is here: https://sketch.cloud/s/nmjQz

**Comment by zdavis** [comment]
Blake, I'm assigning this to you to do the CSS. Please touch base with Max and I real quick before beginning, so we can make sure we're all on the same page in terms of behavior.

**Comment by SMaxOwok** [comment]
Per discussion:
- Email button should link to a contact form page (if contact email is provided in settings)
- Footer links are divided in two columns: pages and social
- Social links should be configurable in backend

**Comment by blnkt** [comment]
@SMaxOwok Is there more work to be done here or is this ready to be rolled up into a pull request?  I believe my frontend contribution is complete: styled the contact form; reorganized the footer to reflect the new design.  Perhaps the only thing left would be to update the mobile layout too?  I didn't think we were waiting on mobile comps so I just tried to keep it as similar to the existing layout as I could given the updated content.

**Comment by SMaxOwok** [comment]
@blnkt I think this is ready for a PR then! If everything was working when you were building/styling the contact form and footer, then my piece was complete too.
