### ISSUE TITLE
Project Creator not seeing admin dashboard link

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1027]
On the CUNY Manifold site, I set up a user account to have the Project Creator role, but the user reports that he cannot see the Admin link and so cannot get to the admin dashboard to create projects.

Please see the attached screenshots for the following account: 

ccnyditigal@gmail.com

<img width="640" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/278503/39838867-89a3abfa-53a8-11e8-813f-0000c3d01ea8.png">

<img width="640" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/278503/39838865-898cbbca-53a8-11e8-9a67-28122ec046af.png">

**Comment by SMaxOwok** [comment]
I wasn't able to replicate this with a new project creator account on the CUNY installation.

@mkgold are you sure this is on the CUNY install?  The second screenshot looks like the UMP installation.

**Comment by mkgold** [comment]
Ugh -- that would explain things, wouldn't it?!!! Sorry -- I didn't notice that. User error!!!
