### ISSUE TITLE
Can't find user account

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1028]
A user says she has an account and showed me screenshots showing a login. But I do not see her listed among the list of users and search produces no result.

Email address:  cchen@ccny.cuny.edu

Screenshots

<img width="640" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/278503/39839028-e9aee492-53a8-11e8-8d22-94f100c49091.png">

<img width="640" alt="pastedgraphic-4" src="https://user-images.githubusercontent.com/278503/39839027-e9a17b90-53a8-11e8-9d29-7593fea4a21d.png">

**Comment by mkgold** [comment]
Also, this is on the CUNY Manifold install

**Comment by SMaxOwok** [comment]
@mkgold Same thing, here.  It looks like the user is on the UMP installation.  Can you confirm that the installations you and the user are interacting with are the same?

**Comment by mkgold** [comment]
Unbelievable. Please ignore. So sorry!!!
