### ISSUE TITLE
Manifold should meet W3C 2.0 Accessibility Guidelines

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1037]
See:
http://romeo.elsevier.com/accessibility_checklist/
https://www.w3.org/WAI/WCAG20/quickref/

We will keep track of the requirements we think we've met here:

- [x] 1.1.1 Provide text alternatives for non-text content
- [x] 1.2.1 Provide alternatives for prerecorded audio-only and video-only content [Publisher responsibility]
- [x] 1.3.1 - 1.3.3 Content can be presented in different ways (e.g. through a screen reader) without losing info or structure
- [x] 1.4.1 Color is not used as the only visual means of conveying info
- [x] 1.4.2 Audio can be paused and stopped, or the audio volume can be changed (e.g. through a screen reader)
- [x] 2.1.1 All functionality is available from a keyboard
- [x] 2.1.2 The user can not get trapped on a particular element when navigating the page via the keyboard (e.g. all parts of the page are accessible using on the keyboard)
- [x] 2.2.2 Users can stop, pause, or hide moving, blinking, scrolling or auto-updating information
- [x] 2.4.1 Users can bypass blocks of content that are repeated on multiple web pages, such as navigation menus
- [x] 2.4.2 The page has a title describing its topic or purpose
- [x] 2.4.3 Users can tab through all interactive elements of a page in a logical order
- [x] 2.4.4 The purpose of each link (or button) can be determined from the link (or button) text
- [x] 3.2.1 When a UI component receives focus, this does not trigger unexpected actions such as automatically submitting a form, opening a new window or switching focus to another element
- [x] 3.2.2 Changing the setting of a checkbox, radio, button, or other UI component does not trigger unexpected changes in context, such as causing significant changes to the page content (such as opening a popup) or opening a new window 
- [x] 3.3.1 Input errors are clearly marked and described to the user
- [x] 3.3.2 Items requiring user input are clearly labeled or have other clear instructions
- [x] 4.1.1 Use valid, error-free HTML including unique (non-duplicate) element IDs 
- [x] 4.1.2 For all UI components, the name, value, and role can be programmatically determined (i.e. accurately interpreted by the screen reader)

**Comment by zdavis** [comment]
Closing this issue, as we believe we've met the above criteria. As we continue to find places where we fall short, we will open smaller, more focused issues.

**Comment by tsmyre** [comment]
First of, this is amazing and awesome! I'd also like to advocate for going further on this course over the next two years and aim for general WCAG AA compliance.
