### ISSUE TITLE
Manifold fails to ingest very large Google docs.

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1041]
A project editor on the CUNY Manifold install ( http://cuny.manifoldapp.org ) reports the following error when trying to ingest this GDoc -- https://docs.google.com/document/d/15cVx-fqVXBn3aUm_9hpL56PjBrw9trFfrZMfYm5RZSc/edit?usp=sharing

```
Connecting to Manifold websocket...
Ingesting "edit?usp=sharing"
Ingestor::Strategy::EPUB::Strategy can ingest? false
Ingestor::Strategy::Markdown::Strategy can ingest? false
Ingestor::Strategy::GoogleDoc::Strategy can ingest? true
Using strategy Ingestor::Strategy::GoogleDoc::Strategy
Ingesting "edit?usp=sharing"
Ingestor::Strategy::EPUB::Strategy can ingest? false
Ingestor::Strategy::Markdown::Strategy can ingest? false
Ingestor::Strategy::GoogleDoc::Strategy can ingest? true
Using strategy Ingestor::Strategy::GoogleDoc::Strategy
Processing failed: File /tmp/gdoc_ingestion20180514-16734-16skjfp.zip has zero size. Did you mean to pass the create flag?

```

Thanks in advance to Team CIC for looking into this -- and please let me know whether I can provide more info.

**Comment by zdavis** [comment]
Strange. We will investigate this today, Matt!

**Comment by mkgold** [comment]
Thanks! FYI, I successfully ingested our sample google doc into the same instance today. The people behind this doc note that it was created through LATEX, and they are wondering whether that has something to do with this.

**Comment by SMaxOwok** [comment]
There is something very strange about this document... I can't even download it directly from google docs.

**Comment by Alexny1992** [comment]
```
Connecting to Manifold websocket...
Successfully connected to websocket.
Ingesting "edit?usp=sharing"
Ingestor::Strategy::EPUB::Strategy can ingest? false
Ingestor::Strategy::Markdown::Strategy can ingest? false
Ingestor::Strategy::GoogleDoc::Strategy can ingest? true
Using strategy Ingestor::Strategy::GoogleDoc::Strategy
Ingesting "edit?usp=sharing"
Ingestor::Strategy::EPUB::Strategy can ingest? false
Ingestor::Strategy::Markdown::Strategy can ingest? false
Ingestor::Strategy::GoogleDoc::Strategy can ingest? true
Using strategy Ingestor::Strategy::GoogleDoc::Strategy
Processing failed: exportSizeLimitExceeded: This file is too large to be exported.
```
I have tried to ingest the file again and was received a different message. 
Since we treat the file as one text section according to SMaxOwok, is there any possibly to force injecting the file in smaller chunks?

**Comment by SMaxOwok** [comment]
@Alexny1992 I believe chunking file uploads is on the horizon, but in the case you posted there, I'm not sure that is something Manifold can address.  That error is coming from the Drive API on Google's side.

You could try downloading the file from Docs as an EPUB and ingesting that.  Otherwise I think the only alternative is breaking up the document into smaller parts.  If you're part of the Slack group, you can also DM me the link and I can try some stuff.

**Comment by zdavis** [comment]
Closing this issue for now. Google docs API has a hard limit of 10mb, and there's nothing we can do at this time to work around that.
