### ISSUE TITLE
Add Speed and Pitch Control to Audio/Video players

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1047]
For some projects that are investigating the nature of sound and its affects, it will be useful to have our media players allow for the audio to be sped up or slowed down without adjusting pitch.  

This is something that YouTube does as well as the Fulcrum players (e.g., https://www.fulcrum.org/concern/file_sets/kk91fk54w)

**Comment by zdavis** [comment]
Discussed on May 17 in weekly call. Team agreed to icebox for now. We're willing to reconsider if there's adequate interest.

**Comment by zdavis** [comment]
Closing for now. We can always reopen.
