### ISSUE TITLE
Redundant button in General Settings: Subject Input

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#1048]
The "Create New" button works as expect, as does hitting enter (as the"Create New" button is type="submit"), however clicking the plus sign next to the text input does not seem to do anything.  Redundant?  Other expected behavior?

![redundant button](https://user-images.githubusercontent.com/8166060/40136415-b94c51b4-58fc-11e8-9225-4cef60ed4966.gif)

**Comment by zdavis** [comment]
Related to #942. This component is due for a bit of an overhaul.

**Comment by SMaxOwok** [comment]
Weird that it's a button and not an icon.  I don't know if it used to also submit or not.  As it is now, it seems like it should be an icon or removed.
