### ISSUE TITLE
Lint jsx files for Accessibility related issues

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#1056]
This includes the linter and any rules either so general as to be safe to include in front of more serious changes related to making Manifold more Accessible, or those rules specifically related to the implementation of ARIA attributes (as there are none present now and all future strategies for addressing Accessibility will involve ARIA)

**Comment by zdavis** [comment]
Hey Blake... this has a "has pull request" label, but I'm not seeing it. Please reference the issue from the PR so that the relationship is more clear. Thanks.

**Comment by blnkt** [comment]
Sorry.  I referenced the PR # instead of the issue # in the associated commit.  This was resolved with #1057.

**Comment by zdavis** [comment]
Keep in mind you can always reference the issue in the PR body, which is
sometimes easier! I don’t care where the reference is, as long as I can
find it.
