### ISSUE TITLE
Variant fields don't save resource

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1067]
On the demo site I created a Video resource (YouTube) and tried uploading an MP4 as a variant. It seemed to save, but when I nav away, Manifold asks if I want to save. But it never actually does. Each time I mean to leave, I get the same prompt. If I refresh the variant I tried loading disappears.

**Comment by SMaxOwok** [comment]
There is a behavior/presentation mismatch currently for external videos.  We show the variant upload dropzones, but strip those attachments in the model.

**Comment by zdavis** [comment]
I think that we should allow variants for external videos, and if used, offer them as download links on the frontend. Does that make sense to others?

**Comment by tsmyre** [comment]
It does, and I fully agree.
