### ISSUE TITLE
Refactor Project.Texts component

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1082]
https://github.com/ManifoldScholar/manifold/blob/master/client/src/containers/backend/Project/Texts.js

There is a bit of redundancy in the position button rendering as well as this just being a monster container.

**Comment by zdavis** [comment]
Before you start refactoring this, I'd look at https://github.com/ManifoldScholar/manifold/issues/1009. We may as well just address that issue instead of refactoring this only to remove the up/down stuff.

**Comment by zdavis** [comment]
In fact, I'm going to close this, since I think #1009 renders it unnecessary.
