### ISSUE TITLE
Refactor ingestions to be of two types: single file and multi file

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1085]
This will let us use one index file format for both google doc and markdown ingestion.  

I believe we could use this for an html ingestion as well and might be able to have one structure generation style for EPUBs and one for everything else.

**Comment by mkgold** [comment]
okay but I will say that this sounds good to me!

**Comment by zdavis** [comment]
Discussed in meeting; all on board.

**Comment by SMaxOwok** [comment]
After discussing the `manifest.yml` addition to other ingestion types, we decided a bigger refactor should be undertaken.

- Ingestions are created as either single file or multi-file (presence of `manifest.yml` determines).
- `manifest.yml` can specify _any_ combination of supported files (epub, md, html, google doc).
- Type-specific ingestion is handled at the TextSection level, rather than Ingestion/Text level.
- Ingestion steps are handled through ActiveInteractions.
- Frontend uploader takes a single file, the Ingestor figures out the rest.

**Comment by SMaxOwok** [comment]
There will now be three steps:
1. Strategy determination (EPUB, manifest, single)
2. Fetching
3. Conversion

**Strategy**: 
- Generates metadata for text, TOC, starting section, etc.
- Builds an array of text section objects:
```
[
 { meta: {
     title: “text section title”,
     etc…
   },
   source: “some-source.md”
 }
]```
- Initializes tmp directory
- Utilizes extra services (text section title determination, etc.)

**Fetching**:
- Collects additional source files
- Pulls files from url
- Extracts files from zip

**Conversion**:
- Assumes source file is HTML at this point
- TextSection is created around this process
- Converts a single text section's source body
