### ISSUE TITLE
Review resource list hover states

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#1086]
Apologies in advance if this was done on purpose, but based on the way this list's stylesheet, I would expect the hoverstates for these list items to be more comprehensive (changing the color of the icon, title, etc.) -- see attached screenshot of the stylesheet.  But I'm not super familiar with this project's styles so perhaps this was a planned departure and not some kind of regression.

![correct hoverstates](https://user-images.githubusercontent.com/8166060/40569903-6d0971de-603a-11e8-8552-60c4f34c56b2.gif)

<img width="416" alt="screen shot 2018-05-25 at 4 36 38 pm" src="https://user-images.githubusercontent.com/8166060/40569902-6cf18b32-603a-11e8-8af1-59d96a3900b1.png">

**Comment by zdavis** [comment]
I agree that this could be improved. Feel free to take a shot at it. Check comps to see if there is a hover state defined, and use best judgement if not. I can review and validate whatever you decide to do.
