### ISSUE TITLE
Activity search doesn't filter for resources or social

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1123]
In a project's `Activity` sidebar there are options to filter search results by `Text Added` and `Project Created`. But there are no filters for added resources or social tiles coming from Twitter.

**Comment by SMaxOwok** [comment]
@tsmyre this seems to be working ok for me.  Where were you seeing it? The filters are added based on the activity.  For example: if there are no resources, there won't be a filter option for resource added.

![screen shot 2018-06-26 at 11 32 24 am 3](https://user-images.githubusercontent.com/8389445/41932065-ce57c6ee-7934-11e8-953a-38f97ff42ed5.png)

**Comment by tsmyre** [comment]
Yep. User error: I didn't consider that if certain elements weren't present the filters wouldn't show. I'll amend documentation accordingly and close this. Thanks!
