### ISSUE TITLE
Adding links for screen reader users to bypass main nav

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#1146]
- [x]  Frontend main nav
- [x] Reader main nav
- [x] Backend main nav

See http://www.jimthatcher.com/skipnav.htm

**Comment by zdavis** [comment]
Is this in fact done?

**Comment by blnkt** [comment]
I finished the links to skip the main top nav.  I left this in progress cause I was interested in adding skips for the sidebar menus in the admin section.  But that could certainly just be its own issue instead.  I'll remove the in progress label.

**Comment by zdavis** [comment]
Ok, in that case, if the work for this has been merged, please close this and create another, more focused issue for the sidebar menus.
