### ISSUE TITLE
Refactor icon system 

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#1160]
We use an iconfont (produced by webpack from a collection of svgs) but seem to always be making the same kinds of minor positioning adjustments to the same troublesome icons across the site.  As we move toward implementing an updated admin section (with its own host of new icons), it is a good moment to revisit the existing icon system and refactor it to render icons more consistently in a manner we would like (i.e. so that the icons effortlessly horizontally align to each other or neighboring text without ever having to absolutely position anything).  This might take a bit of research.  This might mean cleaning up original svg assets.  This might mean creating replacement or additional svg assets.  One strategy we've considered is having a consistent bounding box across the svgs.  Or at least all of the square ones.  But other strategies are worth considering.

**Comment by SMaxOwok** [comment]
@zdavis I think you've completed this or are about to complete this?

**Comment by zdavis** [comment]
We still need to remove the manicons, which is close but not yet complete. I think we can call this in progress.
