### ISSUE TITLE
Social Sharing Message unresponsive

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1162]
The `Social Sharing Message` field under Settings/General in the backend doesn't inform the popups for Twitter or Facebook when sharing selected text. For Facebook the window is only auto-populated with the project tile. And in Twitter, the message reads "from Manifold" regardless of what has been entered here.

**Comment by SMaxOwok** [comment]
I'm closing this as the text setting is applicable to pages _outside_ the reader.  The reader share text is always based on the text title/sections.  

@zdavis, @tsmyre please reopen if you feel a change in language should be made to the form label or the setting should override the reader share text.

**Comment by tsmyre** [comment]
It may be worth reopening this only to make the label more accurate. What's entered in this field does not show up in the Facebook share, only Twitter. For Facebook it reads `"Title" Resource on {Installation name}.` Alternatively Facebook could mirror Twitter in terms of text.
