### ISSUE TITLE
RedirectToFirstMatch component is overriding user navigation

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1171]
Using `RedirectToFirstMatch` component in wrapper containers is causing any navigation into a wrapper container to redirect to the first item in the nav list.  We need to use a condition of some sort or rethink how we're using this component.

For example, destroying a project text redirects to `projectTexts` on success, but this component then sends the user to `projectGeneral`.

Covers #1159

**Comment by SMaxOwok** [comment]
Passing to you, @zdavis, for resolution or ideas on approach.

**Comment by zdavis** [comment]
Another problem, browser back button doesn't work after being redirected.
