### ISSUE TITLE
Navigation path when going from home page to a resource and back

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1203]
Right now, when you visit the home page of a book e.g. https://manifold.umn.edu/project/in-visible-archives-of-the-1980s , and then click on a resource to view it, the breadcrumb navigation at the top of the resource page you arrive at only allows you to go back to the resources page, not to the home page where you started from

**Comment by zdavis** [comment]
This may require rethinking the breadcrumb. I don't really want to have to make the breadcrumb on the resource detail view know how the user go to that page, so we may need to move toward a proper breadcrumb that shows multiple levels.
