### ISSUE TITLE
Page progress indicator

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1207]
## Feature Description
@drjwbaker suggested in a tweet that we should consider implementing a reading progress indicator https://twitter.com/j_w_baker/status/1004632336082841600 . He pointed to the TechCrunch indicator here -- https://techcrunch.com/2018/06/04/microsoft-promises-to-keep-github-independent-and-open/

and Zach seemed to think that was a good idea -- https://twitter.com/zdavis/status/1004724243525820416

## *Why* is this feature important? *Who* does it help?
it helps readers figure out how long a given page is and how much progress they've made through it

## User Stories
I'm a reading a Manifold chapter and I want to know how long a page is / how much further I have to go

## Design Notes
As a reader, I definitely want the ability to turn this visualization off

**Comment by drjwbaker** [comment]
I'd add that the bar on the right side does give *an* indication of progress, but it is telling how many places have now combined this with the right bar. See also: Medium and the '5 minutes to read' bit at the top of posts.
