### ISSUE TITLE
Implement lightweight content management for project pages

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1209]
### Project Types
With this, we introduce concept of project types, which scaffold content blocks:

*Proposed list of project types:*
- Simple Book (Blocks: hero, metadata)
- Enhanced Book (Blocks: hero, activity, texts, resources, metadata)
- Journal or Collection from single source (Blocks: hero, text TOC block, resources, metadata)
- Journal or Collection from multiple sources (Blocks: hero, text list with abstract + author visible, resources, metadata)
- OER or Teaching Resource (Blocks: hero, markdown block with placeholder text, activity, text list with abstract + author visible, resources, metadata)
- Report or Handbook (Blocks: hero, text TOC block, resources, metadata)
- Resource Only (Blocks: hero, markdown block with placeholder text, resources)

### Content Block Types

*Hero Block*
What text the hero block features becomes configurable. We still pull some content (title, subtitle, authors, desc, hashtag, social, etc) from project attributes. Cover image, start reading, TOC, and other things that currently come from the “published text” are set manually by the editor. We adjust the layout of this element a bit so that it renders better when there is no cover image.

*Markdown Block (new)*
This is a new block that we’d be adding. It would accept markdown and render it in its own blade. Imagined uses include a longer project description or abstract to contextualize the various texts, resources, etc. that appear in an in-progress project.

*Text List Block*
We will continue to segment published texts (now more than one potentially) at the top of the list. Explore alternate ways of rendering this list. For example, if the project is an issue of a journal, and each text is an article within that issue, wouldn’t it make more sense to represent this list of texts in a more abbreviated way, more like a table of contents? Both text list views need to be configured to show the author and the abstract in the list.

*Text TOC Block (new)*
This content block would allow an editor to select a text. Manifold would render that text’s table of contents (very much like what’s in the sidebar) as content block on the project page. Configurable to include abstract and author.

*Resources Block*
Team is OK with this block as is, no significant changes needed.

*Metadata Block*
Team is OK with this block as is, no significant changes needed.

### Misc. Related UI Changes
- Relabel Project description field to “Short description” in the backend.
- Texts that are published get a “published” badge or indication on them.

### Project Model Changes
- We no longer store a “published” text on the project.
- Texts are assigned a “published” boolean attribute

### Text Model Changes
Backend editors can choose the “icon” for the cover, or manage the cover image (at high enough resolution to populate the hero featured text area).

**Comment by zdavis** [comment]
This feature was discussed at the UMP meeting, and is also covered by grant #2, so no +1s are necessary to proceed with it

**Comment by susanmpls** [comment]
There's a request for a Project's page to have both a buy button for the print edition of a work and a download button for the ebook file (for offline reading). The ebook file could be either an epub or a PDF.

**Comment by zdavis** [comment]
Update on this —I brief Lael on the requirements, and design is starting in the next couple business days. Should have comps to share in a few weeks.

**Comment by zdavis** [comment]
Update: design in progress.

**Comment by zdavis** [comment]
Round 1 design: https://marvelapp.com/9g32f14/screen/47735702
