### ISSUE TITLE
Document Manifold APIs

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1212]
## Open Development Items

- [ ] Content Block resource attributes depend on the block type, and we need to explain this in the API
- [ ] Describe what the Action Callout route does
- [ ] Describe what the Category route does
- [ ] Describe what the Comment route does
- [ ] Set the swagger docs host to point to the settings in the `.env` file
- [ ] Describe the difference between the `metadataFormatted` and the `metadataProperties` on the projects response
- [ ] Provide a description of the project `tagList`
- [ ] Provide a description of the project `resourceKinds`
- [ ] Provide a description of the project `resourceTags`
- [ ] Check that the relationships on the categories create object is valid
- [ ] Document the data structure of the `text` attribute on the `action_callout` response relationships 
- [ ] Explain why the makers create has both a `name` and `firstName` attribute
- [ ] When a user is not signed in, the abilities attribute is empty

**Comment by zdavis** [comment]
This is a no-brainer. We need to do it.

**Comment by zdavis** [comment]
I will add that I considered moving this issue to the documentation repo, but I suspect that our API documentation will be more a part of the code (based on my experience with other API documentation systems), and a distinct set of docs from the written docs in ManifoldScholar/manifold-docs-jekyll.

**Comment by zdavis** [comment]
API docs were delivered in #2481. Closing!
