### ISSUE TITLE
Improve mobile navigation

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1215]
<img width="512" alt="screen shot 2018-07-19 at 8 57 35 am" src="https://user-images.githubusercontent.com/8389445/42955559-9c3b31cc-8b32-11e8-89cb-6dbe3e2188f3.png">

We currently show `Projects` and `Following` in the footer button nav on mobile.  These two buttons are represented in both the header nav and the home page buttons.  

It's not totally clear if these buttons should reflect the top now (which will have 3 links: home, projects, following) or the buttons on the page.

If they're meant to reflect the buttons on the page, there will now be a state where that will be only one button (on All Projects view => "See Project Collections").

If they're meant to reflect the top nav, there is a little bit of redundancy between the links there and the footer colophon links (home, projects).

**Comment by zdavis** [comment]
@laelito any updates on this?

**Comment by laelito** [comment]
We have redesigned the mobile header for the backend,and I think some of that work might translate to the frontend as well. I have a couple possible solutions, which I can share today.

**Comment by zdavis** [comment]
The comps for this are available now:

https://marvelapp.com/5e29d91/screen/46280219

**Comment by zdavis** [comment]
Closing in favor of #1256
