### ISSUE TITLE
ISBN metadata field is duplicated in project backend

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1219]
<img width="1187" alt="screen shot 2018-07-19 at 11 57 37 am" src="https://user-images.githubusercontent.com/8389445/42964145-090a0f86-8b4b-11e8-86ed-0d6d2bf8cd20.png">

**Comment by tsmyre** [comment]
@SMaxOwok From that screenshot I don't see the duplication: there's the ISBN and the ISSN for International Standard Book and Serial Number, respectively.

**Comment by SMaxOwok** [comment]
Great eye, @tsmyre, you're totally right.
