### ISSUE TITLE
Resource modal thumbnail boxed on exit from modal

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1221]
When closing out of a resource modal accessed by clicking a resource from a text, a gray box surrounds the resource thumbnail until a user clicks to escape from it.

<img width="943" alt="gray-box" src="https://user-images.githubusercontent.com/25825222/42969483-ef4aa256-8b6b-11e8-85b3-2817b2a4bda7.png">

**Comment by zdavis** [comment]
@blnkt this is relevant to your continued work on focus states that we discussed this AM.

**Comment by zdavis** [comment]
Addressed in either #1116 or #1118
