### ISSUE TITLE
Improve resource attachment validation

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1229]
Currently resource attachments are validated as `:resource` first, which checks the extension and content type as being allowed as a resource.  These are broad and encompass _all_ of our resource types.

The resource is then validated against its specific attachment type restrictions.  These do **not** include extension checks.

An example of how this is failing:
We don't allow midi files as audio attachments, but we do allow them as file attachments.  These will still pass audio validation because we accept any `audio/` content type for audio attachments and don't validate the extensions.

**Comment by zdavis** [comment]
So, the solution is to add extension checks for the specific attachment type check?

**Comment by SMaxOwok** [comment]
I think so, yeah.
