### ISSUE TITLE
Including stylesheet for Markdown in manifest ingest breaks reader

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1233]
When including a reference to a stylesheet in a Markdown file used in a manifest ingest the reader behaves abnormally. The margins are slightly different, and the menu does not line up properly. Also the footer no longer spans the width of the screen.

In what may be a separate issue, the screenshot below (taking from [here](https://edge.manifoldapp.org/read/untitled-5358f377-7b2f-4026-9682-b204a1887285/section/103b9840-5978-4856-9212-e9a88455035b)) shows the wrong section title. This should read `3. On Horsell Common` but instead is showing the title of the next section, `4. The Cylinder Opens`. That later section is a plain text file, and thus, perhaps another item altogether.

<img width="1438" alt="md-style" src="https://user-images.githubusercontent.com/25825222/43016898-fec0e476-8c19-11e8-97ab-351c5f59ea61.png">

Here's the coding of the style reference in the original markdown:

<img width="778" alt="style" src="https://user-images.githubusercontent.com/25825222/43017043-63eb3e00-8c1a-11e8-9b4b-2fb29888b969.png">

**Comment by tsmyre** [comment]
Interesting. I simply removed the stylesheet reference from the MD file, and that seemed to clear it up, which is why I associated the two.

**Comment by zdavis** [comment]
I take that back. It is the stylesheet, and I see what's causing it. I'm going to close this issue in a moment in favor of a more targeted issue.

**Comment by zdavis** [comment]
Closing in favor of #1244
