### ISSUE TITLE
When a drawer opens, focus on the first available form input if there is one

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#1240]
Drawers usually contain forms; if you add a `focusOnMount` prop to the first form input, then it will receive focus when the drawer opens rather than focus being applied to the first focusable element (in this case the close button)

Do this work in accessibility/1112:https://github.com/ManifoldScholar/manifold/pull/1116/commits/66667aa480e4e2356b05d8a3e3a8c3bef5ab3b92

**Comment by zdavis** [comment]
Addressed in #1116 and #1118
