### ISSUE TITLE
HTML document ingest does not load external resources

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1252]
I ingested [this HTML document archive](https://github.com/ManifoldScholar/manifold/files/2229642/godzilla.zip) that includes an external stylesheet and one image over on the Edge instance ([here](https://edge.manifoldapp.org/read/untitled-7d4cbbc1-bab6-445d-a0ca-b614aa79abec/section/2563460b-375a-44da-bcf6-ed7cf18c8b1f)).

I noticed that the image was not loading, and when I checked the console for errors saw that the CSS wasn't either.

<img width="401" alt="external" src="https://user-images.githubusercontent.com/25825222/43229230-b6bacafc-9029-11e8-958a-51b122a08c18.png">

I expected a zip of this nature would be confirmed as a document (instead of a manifest) upload, and it was, but the system doesn't seem to look to external resources when it does.

**Comment by zdavis** [comment]
Max, please look into this ASAP. Any kind of ingestion needs to maintain linked assets (both relatively linked assets included in the source package, and external assets referenced through a URL)
