### ISSUE TITLE
Apply backend UI design updates for v2.0

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1256]
This issue encapsulates the backend design changes introduced in this deck:

https://marvelapp.com/5e29d91/screen/46280163

The changes, in a nutshell, are as follows:

- [x] Build all projects view
- [x] Add new snapshot for all projects
- [x] Adjust backend primary navigation options per comps
- [x] Move some containers into "records" instead of the "people" navigation
- [x] Implement secondary backend navigation (eg, projects / collections)
- [x] Update design of tabbed (left col) backend navigation
- [x] Update design of backend record headers
- [x] Update design of backend nested record breadcrumbs
- [x] Update form grouping labels and introduce 2-col form layouts
- [x] Implement mobile version of backend secondary navigation
- [x] Implement mobile version of backend _and frontend_ primary navigation
- [x] Implement backend mobile form styles

**Comment by SMaxOwok** [comment]
I think @dananjohnson is done or mostly done with this in `mo/771`

**Comment by zdavis** [comment]
#1215 will be addressed as part of this work
