### ISSUE TITLE
Elements do not lose focus after event completion

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1257]
![focus](https://user-images.githubusercontent.com/8389445/43420746-99590888-93f9-11e8-857f-995da3575e63.gif)

**Comment by zdavis** [comment]
Not convinced this is in fact a bug. Adding under discussion label.

**Comment by SMaxOwok** [comment]
Agreed now that it might not be a bug, but it does seem like weird behavior.  Is there any accessibility standard for manually blurring afterwards?

In terms of UX it feels weird that the active/focus style is maintained.  It feels like the app is delayed or something.

**Comment by zdavis** [comment]
Yes, as I use it, I agree. @blnkt wondering what you think here.

**Comment by tsmyre** [comment]
I also agree. I encountered it in the adding text screen, and it definitely caught my eye as something that didn't normally happen.

<img width="983" alt="green" src="https://user-images.githubusercontent.com/25825222/43425379-1101fe12-9418-11e8-95d4-9dcea051365d.png">

**Comment by zdavis** [comment]
I wonder, though, if the focus style on these buttons is in fact too foregrounded and too easy to mixup with an active or "on" state. If this focus style was far more subtle, this would be less of an issue.

**Comment by zdavis** [comment]
Also agree that the active (white) state should override the focus state. Might be better to apply an outline in those cases?

**Comment by blnkt** [comment]
Addressing this issue by adjusting the intensity of the focus state styles (at least in the admin backend; so they might not be confused for active or hover states) and making any "active" navigation button or link with focus use a dotted outline focus style instead of their default.
