### ISSUE TITLE
Video fails to render in ingested doc

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1258]
[md.zip](https://github.com/ManifoldScholar/manifold/files/2242914/md.zip)

Md file has this source:
```
<video controls>
  <source src="sample.mp4" type="video/mp4">
  <source src="sample.webm" type="video/webm">
Oops, it looks like your browser does not support
this video element.
</video>
```
Which leads to this rendering error when you view the text in the reader:
```
INVARIANT VIOLATION: SOURCE IS A VOID ELEMENT TAG AND MUST NEITHER HAVE `CHILDREN` NOR USE `DANGEROUSLYSETINNERHTML`. IN SOURCE IN DEFAULTNODE IN VALIDATEDNODE IN VIDEO IN DEFAULTNODE IN VALIDATEDNODE IN DIV IN DEFAULTNODE IN VALIDATEDNODE IN BODY IN DIV IN DIV IN DIV IN DIV IN ANNOTATABLE IN CONNECT(ANNOTATABLE) IN SECTION IN DIV IN HTMLCLASS IN SIDEEFFECT(HTMLCLASS) IN TEXT IN DIV IN SECTIONCONTAINER IN WITHSETTINGS('SECTIONCONTAINER) IN CONNECT(WITHSETTINGS('SECTIONCONTAINER)) IN HIGHERORDER.FETCHDATA('SECTIONCONTAINER) IN CONNECT(HIGHERORDER.FETCHDATA('SECTIONCONTAINER)) IN ROUTE IN WITHROUTER(CONNECT(HIGHERORDER.FETCHDATA('SECTIONCONTAINER))) IN ROUTE IN SPAN IN PASSTHROUGH IN MAIN IN DIV IN BODYCLASS IN SIDEEFFECT(BODYCLASS) IN READERCONTAINER IN HIGHERORDER.FETCHDATA('READERCONTAINER) IN CONNECT(HIGHERORDER.FETCHDATA('READERCONTAINER)) IN ROUTE IN WITHROUTER(CONNECT(HIGHERORDER.FETCHDATA('READERCONTAINER))) IN ROUTE IN SWITCH IN DIV IN MANIFOLDCONTAINER IN CONNECT(MANIFOLDCONTAINER) IN ROUTE IN WITHROUTER(CONNECT(MANIFOLDCONTAINER)) IN ANALYTICS IN WITHSETTINGS('ANALYTICS) IN CONNECT(WITHSETTINGS('ANALYTICS)) IN ROUTE IN WITHROUTER(CONNECT(WITHSETTINGS('ANALYTICS))) IN ROUTER IN STATICROUTER IN PROVIDER IN APP
```

**Comment by SMaxOwok** [comment]
@zdavis there are two problems here:

1. Nokogiri closes `source` tags, so the output is `<source></source>`, which is invalid HTML.
> Void elements only have a start tag; end tags must not be specified for void elements.
https://www.w3.org/TR/html/syntax.html#void-elements

This is solved simply enough by closing the tag in the source (`<source attributes />`), but I'm not really sure what a good solution is for this on the backend.  My first thought would be adding a validation step to remove the closing tags for void elements.  `<source>` _is_ valid, so we would be ok to just strip the matching closing tag.

2. The `controls` attribute gets parsed with an empty string value by Nokogiri and is thus ignored by React.  I have a fix for this, which involves adding a `transform_attribute_value!` method to the tag validator.  Entries can be added to the manifold config and will adjusted accordingly.  In the case of `controls`, changing its value to `true` ensures it renders on the frontend.

Let me know if these sound good to you.

**Comment by zdavis** [comment]
Could we close the void elements before sending them to nokogiri for parsing? If we turned <source> into <source /> before passing it to Nokogiri, which is valid html5 and xml, does it solve the problem?

#2 sounds fine to me.

**Comment by SMaxOwok** [comment]
Yeah, closing ahead of time also takes care of the issue.
