### ISSUE TITLE
Single file manifest ingestions are failing

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1288]
```
      def determine_ingestibility
        context.source_path_for_file("manifest", %w(yml yaml)).present?
      end
```

We're assuming the file is called manifest, but when the file is uploaded without being zipped, the source file gets a new name from Paperclip and the ingestibility check fails.  We also reference "manifest" in the inspector.  

Seems like the fix will be similar to what we do in the document strategy:
- Look for any yaml files
- If there's only one, assume that is the manifest
- If there are multiple, see if one is called "manifest"

**Comment by tsmyre** [comment]
Two questions: what would be the case for uploading two YAML files, and does this mean that there are circumstances where the structuring YAML file need not be called `manifest.yml`?

**Comment by SMaxOwok** [comment]
I'm not really sure there is one; it would be in a case where one is referenced in the actual document somewhere.

This approach just offers slightly more flexibility than _always_ taking the first yaml file we find.  There isn't a case where the structuring document should purposefully be named anything other than `manifest.yml` though.

It's also worth noting that this may be more dependable after #1264 is merged in because we won't be using Paperclip anymore.  I think the plan is to fix it in master first and be more explicit again following #1264, if possible.
