### ISSUE TITLE
Google doc ingestions are missing bullets in unordered lists

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1298]

**Comment by SMaxOwok** [comment]
This is included in the styles that get attached to the google doc.

I'm not sure this is something we should try to fix as we don't really have any way of knowing if this is by the user's design or not.

```
.manifold-text-section ul.lst-kix_ro96a8lq6rkf-0 {
    list-style-type: none;
}
.manifold-text-section ul.lst-kix_ro96a8lq6rkf-3 {
    list-style-type: none;
}
.manifold-text-section ul.lst-kix_ro96a8lq6rkf-2 {
    list-style-type: none;
}
```

**Comment by zdavis** [comment]
So, if you export the HTML from google docs and open it in a browser, the lists don't have bullets?

**Comment by zdavis** [comment]
Because if I make a simple google doc with a bullet list and export it, that's not the behavior I'm seeing.  I'd like to confirm that the problem is in the exported HTML version of the doc—what you're showing above doesn't really prove that it's not a Manifold bug, because those styles you cite are the results of Manifold's style extraction, and it's possible there's an error in that extraction process.

**Comment by SMaxOwok** [comment]
So what's happening is that the bullets are provided as a `::before` pseudo-element with an icon character.  The stylesheets hide all list styles and then apply these to each element.

This works when ingesting the doc as a .zip:
```
.manifold-text-section .lst-kix_wim8u6ju9jtr-1>li:before {
    content: "\0025cb  ";
}
.manifold-text-section .lst-kix_wim8u6ju9jtr-2>li:before {
    content: "\0025a0  ";
}
```

But seems to be failing when ingesting from a URL:
```
.manifold-text-section .lst-kix_wim8u6ju9jtr-1 > li:before {
    content: "     ";
}
.manifold-text-section .lst-kix_wim8u6ju9jtr-2 > li:before {
    content: "     ";
}
```

**Comment by SMaxOwok** [comment]
Looking at our css parsing, I think we might be able to just replace these with character codes
```
.lst-kix_wim8u6ju9jtr-0 > li:before{content:\"●  \"}
```

**Comment by SMaxOwok** [comment]
This is an issue within the css_parser gem.

The call to `parser.load_string!` removes the symbols from its style declarations.
