### ISSUE TITLE
Ingestion modal does not scroll on mobile

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1303]
<img width="378" alt="screen shot 2018-08-09 at 4 46 13 pm" src="https://user-images.githubusercontent.com/8389445/43931585-1430ffdc-9bf4-11e8-899b-1e9b861e6978.png">

**Comment by zdavis** [comment]
Rather than make the modal scroll, I'm inclined to move this into a drawer (perhaps a wider drawer, like what we're going to have for collections). I think the modal is the wrong UI for this component.
