### ISSUE TITLE
Explore Google Scholar Indexing

### ISSUE THREAD

**Issue by suryadalimunthe** [ManifoldScholar/manifold#1314]
Are works published through the Manifold platform indexed by Google Scholar? If not, is it possible to include this indexing feature?

**Comment by zdavis** [comment]
I'm assigning this to v7, and we'll explore this further at that time.

**Comment by zdavis** [comment]
Closing for now due to inactivity.

**Comment by suryadalimunthe** [comment]
has the question been answered, that is, manifold indexed by google
scholar? :) surya



Pada tanggal Rab, 31 Jul 2019 01.49, Zach Davis <notifications@github.com>
menulis:
