### ISSUE TITLE
Frontend covers in grid shouldn't highlight

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1328]
This is an opinion:

I don't think the covers should highlight given our new hover styles.  It feels distracting to see internal and external changes to the content.  It also animates where the hover doesn't, which also breaks the cohesion a bit.

![covers](https://user-images.githubusercontent.com/8389445/44422470-20181180-a538-11e8-8808-daa650d54d41.gif)

**Comment by zdavis** [comment]
@laelito Care to weigh in on this? You can see this in action on the edge server.

**Comment by laelito** [comment]
I think that's a fair point by @SMaxOwok, and I am fine with removing the highlight border—the hover effect is probably plenty. But speaking of that hover effect, I have a couple visual fine-tuning adjustments:

1) The shadow on hover is coming across a bit heavier when compared with the comps, which have a lighter, subtler touch. Specifically, in the design comp the shadows seem a bit lighter, positioned higher up, and with more spread to the blur. @SMaxOwok can you refer back to the comps in Sketch and see if you can get the shadows to match up more closely?

2) When the project grid is on the light grey background color (F7F7F7), we use ECECEC for the hover effect color. But when the project grid is over a white background we _still_ use ECECEC for the hover effect color. Ideally, the hover effect color would have the same visual relationship with the background color on grey or white backgrounds. So...when we do have a white background, I would like us to lighten the hover effect color one level to F7F7F7.

I recognize that both of these requests are pretty subtle moves. Maybe even "fussy." So if either seem too difficult or time-consuming, let me know.

Here's a screengrab for reference:

![hover effect](https://user-images.githubusercontent.com/26985828/44557837-7c746000-a6f5-11e8-8844-e7d43223bb5c.jpg)

**Comment by SMaxOwok** [comment]
- [ ] Remove hover cover outline
- [ ] Adjust shadow positioning/style
- [ ] Adjust shadow color on white background

**Comment by dananjohnson** [comment]
Hey @laelito ! Thanks for the feedback. I'll get these hover effects sorted out pronto.

**Comment by laelito** [comment]
excellent! thanks @dananjohnson.

**Comment by mkgold** [comment]
thank you for being fussy about Manifold @laelito ! and huge thanks for your work @SMaxOwok @dananjohnson
