### ISSUE TITLE
Load MathJax polyfill when texts include <math> tags

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1354]
We'd want to import the polyfill dynamically, since we don't want to load this for all texts. I believe that the reader has mechanisms for rendering tags in specific ways, so we might be able to build a custom component for <math> tags in the text and apply the polyfill just to those component. Consider looking at https://github.com/SamyPesse/react-mathjax, as an example of approach here.

**Comment by jojokarlin** [comment]
We have had another request for MathJax from a stats professor at Guttman.

## *Why* is this feature important? *Who* does it help?

This feature would help STEM teachers hoping to publish their course materials in Manifold. The OER 

Pressbooks now supports MathJax -- see 
[Pressbooks MathJax](https://pressbooks.com/2019/07/10/mathjax-now-available-on-pressbooksedu/)

**Comment by robin-miller** [comment]
We have another request for MathJax or LaTeX support from a Math and Computer Science professor at QCC-CUNY.
He would like to publish his [Algebra and Geometry of Elementary Functions ](https://agfun.yfei.page) on Manifold and is having issues with math equations.

### _Why_ is this feature important? _Who_ does it help?
This feature would help STEM instructors that would like to publish OER on Manifold.

**Comment by fyemath** [comment]
> We have another request for MathJax or LaTeX support from a Math and Computer Science professor at QCC-CUNY.
> He would like to publish his [Algebra and Geometry of Elementary Functions ](https://agfun.yfei.page) on Manifold and is having issues with math equations.
> 
> ### _Why_ is this feature important? _Who_ does it help?
> This feature would help STEM instructors that would like to publish OER on Manifold.

Thank you, Robin! The source files for this book can be found in [https://github.com/fyemath/agfun/tree/master/book_output](https://github.com/fyemath/agfun/tree/master/book_output).
