### ISSUE TITLE
Refactored ingestion should not catch StandardError

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1355]
The recent refactoring of the ingestion service is assigning any error raised during ingestion to the active interaction errors. This needs to be narrowed considerably so that it is only rescuing from errors that are reasonably raised by our ingestion classes.

**Comment by zdavis** [comment]
Fixing this isn't quite as easy as it should be, because exceptions appear to be used for flow control in places. For example, if we let these exceptions through, the Fetcher no longer fails correctly. Code will need to be refactored somewhat to address this.

**Comment by SMaxOwok** [comment]
Perfect opportunity to address #1430
