### ISSUE TITLE
Link dashboard project headers to all projects page.

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1359]
## Feature Description
Right now, if, as an admin of a Manifold instance, you click on "Admin Mode," you are taken to a page containing two columns -- Projects (with a search option, and a paginated view) and a list of recently updated projects.

![screen shot 2018-08-31 at 6 33 57 pm](https://user-images.githubusercontent.com/278503/44938417-dd7ee200-ad4c-11e8-895f-0213bac89398.png)

There is an All Projects view available 

![screen shot 2018-08-31 at 6 37 38 pm](https://user-images.githubusercontent.com/278503/44938431-f8515680-ad4c-11e8-9d2c-c799825a82ef.png)

But, oddly, we don't surface a link to it except (as far as I can see) on an individual project dashboard page

![screen_shot_2018-08-31_at_6_38_28_pm](https://user-images.githubusercontent.com/278503/44938471-364e7a80-ad4d-11e8-979c-124b78c8338e.png)

(though I've just now realized it is also accessible from the "Projects" link in the top nav.

I'd argue that either the "Projects" text or the "# of projects" text should be linked to the All Projects view, so that one could click one of those things and get to the All Projects view

![screen_shot_2018-08-31_at_6_33_57_pm](https://user-images.githubusercontent.com/278503/44938545-ab21b480-ad4d-11e8-943e-1e4078706fbe.png)

## *Why* is this feature important? *Who* does it help?
User experience of the admin. When I go to the dashboard, I want a more obvious way to see all projects.

## User Stories
I'm an admin and I want to get as much of an overview of the projects on this instance as possible, because I want to select a few to be featured. If I can't easily get to an All Projects view, I get frustrated.

**Comment by zdavis** [comment]
I agree that these two things should be linked, and it's easy to do. +1

**Comment by mkgold** [comment]
thanks!
