### ISSUE TITLE
Request for public comment management panel for projects

### ISSUE THREAD

**Issue by hieburt** [ManifoldScholar/manifold#1360]
## Feature Description
Tab/panel where you can view/manage/sort all public annotations on a project. 

## *Why* is this feature important? *Who* does it help?

- This would be useful for Instructors using Manifold to host course texts. 
- It would be useful for a publisher or community moderator. 

## User Stories
I'm a literature instructor and I'm using Manifold for my course texts. I'm asking students to collectively annotate the texts. All of that works, but it's very hard to locate annotations. For example, checking to see if everyone did the annotation assignment requires me scrolling through the entire assigned sectoin(s), finding the subtle underline, and clicking it to find out who the student is/when they posted. It would be much harder if I reuse the text in the future or had the same group of students go back and annotate again (i.e. first time for definitions; second time for questions; third time for...). This would quickly become a mess if other instructors were using the same text, too. 

Another example is when I find an annotation from a student I want to draw attention to in class later. I have to remember where it is or highlight/annotate it myself to be able to find it. 

I can also imagine that a publisher or a community moderator may want to manage comments occasionally. Sure, you must be logged in to comment, but I can think of many cases where the ability of a project owner to delete/manage comments would be incredibly useful. Heck, I can see it useful even for an instructor. 

## Design Notes
- Ideally, you it would listing all **public** highlighting and annotations with sort features by user and post time. 

- It would be helpful to be able to click on a username and view the user's public highlights/annotations on that particlar project. This way instructor's could quickly look at the work of known student user OR people could follow their instructor/colleague/friend through a particular work. (ex. a kind of "read Marx's Capital along with David Harvey"-thing. Or Melville's annotations to Shakespeare's. 

## Development Notes
A lot of these features might be redundent/unncesary if groups are enabled for annotations.

**Comment by zdavis** [comment]
We will build this, or something close to this as part of annotation groups in v4. Discussed this during the PDX team meeting today.

**Comment by zdavis** [comment]
Closing this issue because it is included in the work we are doing for #2240. Thank you very much for this request—this issue will be associated with #2240 and we will consider it as we work through that issue.
