### ISSUE TITLE
Refactored ingestion no long supports multiple languages

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1364]
@SMaxOwok any thoughts on why we can no longer ingest non-latin characters:

![image](https://user-images.githubusercontent.com/255909/45106103-ab71d500-b0ea-11e8-90fe-b72e268065c6.png)

This surely worked before.

**Comment by SMaxOwok** [comment]
Might be related to https://github.com/ManifoldScholar/manifold/commit/b3e7845bb53f6ca04ae5f294376f3f22aad365b3?

**Comment by zdavis** [comment]
I fixed it today, but haven’t committed it yet. I introduced this one when
working the document TOC generation back into ingestion.
