### ISSUE TITLE
Migrate comment kind field to classy enums

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1368]
See https://gist.github.com/scryptmouse/b950f6b74b2e9ea68351387c078acff7.

This was raised during the email notification work, but didn't quite make it in.

**Comment by SMaxOwok** [comment]
@zdavis and I agreed to close this a while back after a discussion.  Since we're making distinctions based on `subject_type`, there isn't much to gain by adding a column and enums for `kind`.
