### ISSUE TITLE
Selected project avatar color has unnecessary green circle

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1374]
Crossover styles from form toggles

![screen shot 2018-09-12 at 1 47 19 pm](https://user-images.githubusercontent.com/8389445/45452323-86ed9e00-b692-11e8-9547-4e27b477f8cd.png)

**Comment by zdavis** [comment]
Yep, I can reproduce. @dananjohnson can we get a very quick fix on this? Trying to get a release out.
