### ISSUE TITLE
Potential problems re-ingesting a text in 2.x over a text ingested in 1.x

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1390]
@tsmyre reports problem ingesting an EPUB in 2.0 that had been ingested in 1.x on the Minnesota instance. This problem manifested as invalid links in the TOC (the text_section segment was undefined). Deleting the text and ingesting it again worked fine, as did ingesting the text on a 2.0 instance and reingesting it.

Max, could you please take a look at this? I think that you might be able to run Manifold 1.0 on a Manifold 2.0 DB schema, but we'll see. If that's the case, checkout 1.x and ingest an epub. I suspect that we're changing how source identifiers are generated in 2.0, and that this problem stems from the 2.0 text section upsert mechanisms (or toc mechanisms) not finding the text sections by source identifiers. I'd start by looking at how these change. Make sense? We can talk it through if that helps.

**Comment by SMaxOwok** [comment]
This should be resolved by #1394
