### ISSUE TITLE
Backlink in text not working

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1416]
Links to footnotes are inconsistently broken when brought in from an EPUB. @SMaxOwok I've DM'ed you a sample file that is loaded here: https://aupress.manifoldapp.org/projects/assessment-strategies-for-online-learning

See the end of ch. 3 for examples of notes that both link and don't.

**Comment by SMaxOwok** [comment]
The links are appearing, but the content is appearing outside of the link in some cases.  Looking closer.
![screen shot 2018-09-21 at 11 17 38 am](https://user-images.githubusercontent.com/8389445/45898843-09134c00-bd90-11e8-992e-e4348bece126.png)

**Comment by zdavis** [comment]
Did you find anything on this?
