### ISSUE TITLE
Header navigation problems

### ISSUE THREAD

**Issue by rlzevallos** [ManifoldScholar/manifold#1435]
When adding an external page to the header navigation, it seems to link to an internal link such as /page/1, however it links properly when added as a footer link.

In addition adding multiple pages results in duplicated header navigation links, which continues to duplicate when the header area is clicked on.

![image](https://user-images.githubusercontent.com/26172306/46362498-4a73e900-c625-11e8-925d-05673716bcae.png)
![image](https://user-images.githubusercontent.com/26172306/46362530-5f507c80-c625-11e8-8ddd-7c07edc4ffbc.png)

**Comment by zdavis** [comment]
Good catch. Thanks. It'll be fixed in the next minor release.
