### ISSUE TITLE
Form select instructions should be underneath select

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1442]
Currently form select instruction elements are above the actual select, which breaks from the arrangement other form elements use.  As a result aligning a select and other form element looks strange. 

Need to check other uses of form selects to make sure it's safe to universally change alignment.

![screen shot 2018-10-03 at 9 27 16 am](https://user-images.githubusercontent.com/8389445/46424687-af474600-c6ee-11e8-8d6b-43d653aec963.png)

**Comment by zdavis** [comment]
The only select I could find with instructions was this one. I'm going to make this change.
