### ISSUE TITLE
Create a mechanism to export Texts

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1444]
For those who are publishing OER or like materials on the platform, we do not presently provide an easy means for associated users to secure and remix Texts.

A moonshot-solution would be to think of Texts in the same way we do Resources, which are associated with projects generally and can added to any Text in a project. This path would allow users, through the system, to create custom Texts out of individual text sections in the system.

A more modest and equally usable approach would be to allow users to export any text (to EPUB or Manifest + files or the like) from the system, allowing them update/adjust/remix those texts outside of Manifold without having to hunt down the source files from whoever may have uploaded them to their instance.

Beyond remixing, this would also potentially be applicable for preservation.

**Comment by zdavis** [comment]
Interested in exploring remixing possibilities—this issue needs a little more development, discussion.
