### ISSUE TITLE
Feature request: display notes across an installation

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1446]
If I am right about this, one only sees the "My Notes" for the text one is currently reading through Manifold. I think it could be useful in that My Notes section to see notes from any text on that installation. Not sure whether that is possible, but it seems to me like it would be a useful feature. Or, maybe, surface links somewhere to the texts that the user has annotated/highlighted

**Comment by zdavis** [comment]
I think we need to address this in a broader context of a user dashboard where the user can access their content across the installation.

**Comment by zdavis** [comment]
Closing, because this is now covered as part of the OER work.
