### ISSUE TITLE
Add an explicit checkbox to signup and record assent if terms and conditions are set.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1464]

**Comment by SMaxOwok** [comment]
Started in `mo/1464`

**Comment by zdavis** [comment]
This requires some further discussion and decisions before we can proceed. For example... how do we deal with user accounts that are created in the backend by admins? How do we determine if this checkbox should be visible? What if the TOS change? We should probably address this as part of a larger GDRP approach.

**Comment by zdavis** [comment]
Closing for now; we will tackle this as part of GDPR generally #1722
