### ISSUE TITLE
Incorrect header to TOC mapping in Google Doc

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1471]
Ingesting this gdoc:

https://docs.google.com/document/d/1vDHKZPtBRT5NgqxRAbWL7n7JXMzUHdL1wcXne5p289w/edit#

Leads to a TOC with incorrect header nesting:

![image](https://user-images.githubusercontent.com/255909/46826049-012d4300-cd63-11e8-878d-8dc539423a9a.png)

**Comment by SMaxOwok** [comment]
This could be considered a bug with our depth detection.  It fails if headers are skipped.

**Comment by SMaxOwok** [comment]
I have some tests in `mo/1471`.  Still working out the best way to handle cases where header tags are jumped.

**Comment by zdavis** [comment]
Max took a stab at this in mo/1471 but wasn't quite able to sort it out. Assigning to me.
