### ISSUE TITLE
Cannot access internal page when there is an external link in the header

### ISSUE THREAD

**Issue by Chu-2** [ManifoldScholar/manifold#1493]
## Expected Behavior

User should be able to use external link in the header and go to any internal page of the site.

## Current Behavior

When an external page is the first link after Home in the header, go to any internal page link returns
error page.

## Possible Solution

Workaround: Hide external link in the header or make sure there is an internal page link before external link in the header.

## Steps to Reproduce

1. Create one internal page and one external page.
2. In the external page's setting page, make sure `Show in Header` set to ON.
3. Navigate to internal page's path returns error page.

## Context (Environment)

Manifold v2.0.4 on Ubuntu 18.04 and 16.04

**Comment by SMaxOwok** [comment]
https://github.com/ManifoldScholar/manifold/blob/master/client/src/components/global/Navigation/Mobile/Breadcrumb.js#L37

**Comment by zdavis** [comment]
Additional info: the external page must appear before the internal page in the nav to reproduce.

**Comment by zdavis** [comment]
Dang — referenced the wrong issue in my commit. In any case, this issue has been addressed by #1533. Thanks for taking the time to report this bug!! We really appreciate it!
