### ISSUE TITLE
Scroll-locking not working with backend drawers in iOS Safari

### ISSUE THREAD

**Issue by dananjohnson** [ManifoldScholar/manifold#1506]
When drawers are open, scrolling should only be possible within the drawer. However, in iOS, the user is still able to scroll other content.

![screencast 2018-10-23 16-01-12](https://user-images.githubusercontent.com/12454203/47395782-f5376e80-d6dc-11e8-813a-0175337018fe.gif)

**Comment by zdavis** [comment]
This is also an issue for the reader drawers.
