### ISSUE TITLE
Project add button styles should be responsive

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1512]
![screen shot 2018-10-24 at 10 27 42 am](https://user-images.githubusercontent.com/8389445/47449490-9ffc6b00-d777-11e8-86b3-3bd7b44a6d6d.png)

These should probably resize a little or change position so they aren't overlapping the container padding.

**Comment by dananjohnson** [comment]
In the comps, it looks like there's some lefthand padding to compensate for the size of the button.

<img width="464" alt="screen shot 2018-10-24 at 11 06 08 am" src="https://user-images.githubusercontent.com/12454203/47451520-dc7e9580-d77c-11e8-90d5-f1def9ee2c96.png">

**Comment by dananjohnson** [comment]
I'm also noticing that that "+" icon is shifted to the right a pixel or so.
