### ISSUE TITLE
FatalError doesn't seem to catch 502 errors

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1539]
<img width="1427" alt="screen shot 2018-10-25 at 4 15 25 pm" src="https://user-images.githubusercontent.com/8389445/47535791-e9c97c00-d871-11e8-883e-0b6fa0b9d6ac.png">

**Comment by zdavis** [comment]
![image](https://user-images.githubusercontent.com/255909/47570058-0ef9d100-d8ea-11e8-8a3f-5d2761f41d6b.png)
