### ISSUE TITLE
Drawer notification alignment regression

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1554]
"Dismiss" should always be below the message.
![screen shot 2018-10-26 at 1 13 45 pm](https://user-images.githubusercontent.com/8389445/47590450-24d6b880-d921-11e8-86ad-e86c0f93baf1.png)

**Comment by SMaxOwok** [comment]
Actually, probably the headline, message, and dismiss should all be on separate lines.  I can't remember exactly how it used to look.

**Comment by zdavis** [comment]
Looked like this:
![image](https://user-images.githubusercontent.com/255909/47591382-3b324380-d924-11e8-841b-8a07933d6135.png)

**Comment by SMaxOwok** [comment]
Nailed it
