### ISSUE TITLE
Reports of Annotations not persisting in Edge

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1559]
From Slack:

"This is a really basic problem, but I'm having some trouble getting an annotation to stick. I highlight text, annotate it, save it as public; the text is now underlined and when I click it again, I can read the annotation - all good. But when I click on the notepad to see my annotations, it says I haven't made any yet. If I go to another page and then come back, it's gone. And it doesn't show up on the homepage counter. What am I doing wrong?"

User is using Edge, so we should start with seeing if we can reproduce it there.

https://uw.manifoldapp.org/read/345bd627-c340-4f13-9e39-d2deb886089b/section/6e8e132e-93b1-4b00-bd87-9f45455b6610

**Comment by SMaxOwok** [comment]
Investigate... I believe this is related

![screen shot 2018-10-31 at 2 37 40 pm](https://user-images.githubusercontent.com/8389445/47820376-909e9400-dd1a-11e8-8940-b5444d679f11.png)

**Comment by SMaxOwok** [comment]
I haven't been able to replicate this.

**Comment by zdavis** [comment]
Thanks for checking. I'm pretty sure it was a rendering problem rather than a persistence problem.
