### ISSUE TITLE
Markdown doesn't render in title fields

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1563]
Markdown doesn't render as expected in the project title field nor in the the text title field:

<img width="1179" alt="project-title" src="https://user-images.githubusercontent.com/25825222/47681518-b2234280-db97-11e8-8fda-bb7f1015fbbf.png">
<hr/>
<img width="532" alt="text-title" src="https://user-images.githubusercontent.com/25825222/47681582-dc750000-db97-11e8-9b87-6a042dd35ecb.png">

It does render as expected in the resource title field, but having an asterisk as the first character seems to break the resource, serving [only a blank page](https://edge.manifoldapp.org/projects/this-is-a-title-within-a-title/resource/title-in-title).

The samples here come from a [dummy project on Edge](https://edge.manifoldapp.org/projects/this-is-a-title-within-a-title).

**Comment by SMaxOwok** [comment]
Resource issue is noted in #1565.  I believe it's unrelated to this issue.
