### ISSUE TITLE
Display multiple home page Features in a scrollable carousel

### ISSUE THREAD

**Issue by BethFuget** [ManifoldScholar/manifold#1573]
## Feature Description
It would be nice to have the features in a carousel, rather than randomly pop up.  Thanks!

## *Why* is this feature important? *Who* does it help?
We could use several features but still make sure people see whatever essential information we want them to see when they first arrive at the site.  If we had a carousel, for example, we could use both our intro feature and the main Manifold feature. But since I want to be sure people see our intro, I had to disable the Manifold intro (though I did put a link to it).

## User Stories
As a User, I can create multiple Features and have them scrollable in a carousel on the homepage.

**Comment by susanmpls** [comment]
Instead of developing a carousel, we recommend that publishers use project collections to direct readers to different groups of featured projects.
