### ISSUE TITLE
Add option to deactivate frontend user registration

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#1581]
It would be very helpful to be able to somehow temporally deactivate frontend user registration.

Depending on the use case 'open' user registration is not always desirable, especially when using Manifold as a publication platform only.

In our context it is very important due to the EU's General Data Protection Regulation. To offer registration immediately demands to put much more work into a data protection declaration, something that is not a trivial task.

**Comment by zdavis** [comment]
Thank you for opening this issue—we really appreciate it. However, after discussing this, I don't see us making this change. Instead, we'd prefer to devote our resources to ensuring that Manifold can be GDPR compliant—allowing users to download the information we have about them, delete their acct, provide cookie consent, etc.

Closing in favor of #1722
