### ISSUE TITLE
Project Collection new drawer should focus on first text input when opened

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1593]
When you click the button to create a new collection and the drawer slides out from the right to begin that process, the `X` in the upper left to close the modal is already selected:

<img width="477" alt="button-box" src="https://user-images.githubusercontent.com/25825222/47926873-bdc08300-de8f-11e8-94f3-211a4dafbf11.png">

**Comment by SMaxOwok** [comment]
I think this is by-design for accessibility.  I'm not sure if it is supposed to be the close button or if it can be anything in the drawer.  If it can be anything, perhaps it should be moved to the input field?

**Comment by SMaxOwok** [comment]
In fact, yes, it can be on the input.

**Comment by zdavis** [comment]
It defaults to the close button (as the first link in the modal), I think, but in almost every case should be on the first input. I think we just need to add the focus attribute.

Zach
