### ISSUE TITLE
Text citation not working

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1619]
I just created the following test project on Edge to investigate the citation generator: `https://edge.manifoldapp.org/projects/poe-test-project`.

However I am not able to get the Cite button to appear. My understanding is that to get that the following four metadata fields need to be filled in: `Author`, `Publisher`, `Publisher Place`, and `Publication Date`. I added these in on the Text level to no avail. Adding them in to the project's metadata also didn't work.

**Comment by tsmyre** [comment]
My feeling is that these items of metadata should be required on the individual text instead of as the project as a whole, so different texts within a project can be properly cited.

**Comment by SMaxOwok** [comment]
Weird... I do see the citations for that text.

```
 citations:
  {"apa"=>"Poe, E. A. (1896, March 6). The Works of Edgar Allan Poe — Volume 2. Publisher, Plance: Publisher Name.",
   "mla"=>"Poe, Edgar Allan. <i>The Works of Edgar Allan Poe — Volume 2</i>. Publisher Name, 6 Mar. 1896.",
   "chicago"=>"Poe, Edgar Allan. “The Works of Edgar Allan Poe — Volume 2.” Publisher, Plance: Publisher Name, March 6, 1896."}
```

Looking closer.

**Comment by SMaxOwok** [comment]
Not sure what happened here, but the text sections didn't have citations generated.  It must have been a problem with `with_citable_children`, but it's hard to track down after the fact.

This text does have the 2 created events bug, which may be related to why the children weren't updated when it was created.

**Comment by zdavis** [comment]
Closing until we can find clearer steps to reproduce.
