### ISSUE TITLE
Allow hiding of "Sign Up" link on homepage

### ISSUE THREAD

**Issue by simpsonw** [ManifoldScholar/manifold#1622]
Currently, a "Sign Up" link appears in the featured content area at the top of the home page:

![screenshot from 2018-11-08 15-02-46](https://user-images.githubusercontent.com/10437788/48230404-15fff500-e368-11e8-8be0-ba927da256c6.png)

We'd like to have the option to hide this link (preferably via a configuration variable in `manifold.rb`) since we feel that it would be confusing to our users given our use case for Manifold.

**Comment by zdavis** [comment]
I'm inclined to remove it all together and instead make it possible to add zero or more links to a feature record, one of which could be a link to signup. I don't think it's helpful to have it added to the feature programmatically, as it is now. @tsmyre, what do you think?

**Comment by tsmyre** [comment]
@zdavis I concur with your take. I'd add that I think Sign In/Sign Up will still be useful for some, so having the ability to simply choose that as an option, in addition to being able to create custom links would be great.

**Comment by SMaxOwok** [comment]
Seems related to #1581

**Comment by cg433n** [comment]
Is this slated for release soon? We (University of Arizona Libraries) would love to have the Sign-up link hidden before we go live.

**Comment by zdavis** [comment]
I expect it to be released as part of 2.1. We'll have betas of 2.1 ready this week (perhaps as soon as today), and final packages soon thereafter, depending on how the betas shape up.

**Comment by cg433n** [comment]
Fantastic - thank you!

**Comment by zdavis** [comment]
We're implementing this setting on each feature record for now (not in global settings per the original request). The default will be _not_ to include a signup link. If a user wants a feature to render the sign up link, they will need to check the appropriate checkbox on the feature record.

Zach
