### ISSUE TITLE
Remove copyright field pre-population

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1634]
The `Copyright` field in Subjects/General adds an introductory copyright symbol `©` and a terminal period.

Thus if I input `Copyright © 2018 University of Minnesota Press.` the system will return this `© Copyright © 2018 University of Minnesota Press..`, with two copyright symbols and double punctuation at the end.

**Comment by SMaxOwok** [comment]
Probably either add a mask to the input or stop rendering a prefix in the client.
