### ISSUE TITLE
Add Start and Expiration fields to project collections

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1635]
It would be useful to have `Start` and `Expiration` fields as modifiers to a project collection's visibility, enabling a publisher the means to create a collection blade for a campaign for a set amount of time ahead of an event. When the start date was reached the blade would become visible on the homepage and then toggle off from homepage visibility when the expiration date was reached.

**Comment by SMaxOwok** [comment]
@tsmyre Do you envision this affecting only homepage visibility and not overall visibility?

**Comment by tsmyre** [comment]
I could see it both ways, but my first thought was specific to homepage visibility.

**Comment by susanmpls** [comment]
I would love this. And I would want it to affect homepage visiblity only.
