### ISSUE TITLE
FormContainer should display base model errors

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1643]
The FormContainer component should include an error field that responds to errors on the model `:base`.  Right now these errors aren't displayed anywhere on the frontend.

Additionally, the existing `groupErrors` prop/errors in the form container should ignore `:base` errors after the above is added.

**Comment by zdavis** [comment]
Please provide an example of where this is a problem.

**Comment by SMaxOwok** [comment]
I don't know if it currently is a problem, but it would be with https://github.com/ManifoldScholar/manifold/pull/1644/commits/0e263d7b29af44db2bfc85b91f3aa48dc698ba49, which I think is a valid case...

I think there _could_ be more cases where we are applying an error to the record as a whole and not a a specific attribute.  I'm happy to change up that commit and close this if you disagree though.

**Comment by zdavis** [comment]
In that case, can you address this as part of that PR?

**Comment by SMaxOwok** [comment]
Yeah, no problem

**Comment by SMaxOwok** [comment]
We decided to take care of this on separately from the name stuff in the end.
