### ISSUE TITLE
Feature request: New options for sorting projects

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1667]
## Feature Description
right now, we have three options for sorting projects on the backend:
default (it's unclear what this means)
a to z
z to a

I propose that we add fournew sorting options:

1. Date created (newest first)
2. Date created (oldest first)
3. Last updated or active (newest first)
4. Last updated or active (oldest first)

I'm not stuck on those names but do think we should have those general concepts

## *Why* is this feature important? *Who* does it help?
Especially when an admin is running a large install, with lots of people creating new projects, one may want a view of the newest ones created or the most recently updated. this would allow one to quickly see which new projects were created 

The thought came to me tonight when I wanted to see which projects had been created in the workshop @jojokarlin ran, but I couldn't get a list of the most recently created projects.

## User Stories
I'm an admin and I want to see a list of the most recently created or updated projects. being able to sort by date would be helpful

**Comment by zdavis** [comment]
We should address this.

We store "created_at" and "updated_at" timestamps on projects. We should touch the project record (which would update the "updated_at" timestamp when new texts or resources are created (or maybe simpler, when a new event is created on the project). I think we should also offer sorting by the publication_date project field.
