### ISSUE TITLE
Add fields to provide credit to image rights holders

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1689]
It would be useful to have a field in the backend to give credit to those whose images and art is being used for decorative purposes as the project hero, thumbnail, or poster images. I expect that rendering that information alongside existing metadata for resources would be sufficient. My first inclination for the hero would be to have it appear on the image itself, but perhaps down in the project metadata blade would be better, assuming the field name was appropriately descriptive enough for a general reader.

**Comment by zdavis** [comment]
We'll put it under the cover.

![image](https://user-images.githubusercontent.com/255909/52228783-2260f480-2868-11e9-8868-31852e07eb18.png)

**Comment by zdavis** [comment]
Mobile:

![image](https://user-images.githubusercontent.com/255909/52228825-34db2e00-2868-11e9-9c8b-cbdbbe69ff09.png)

**Comment by tsmyre** [comment]
These two fields presently run into the same line. Is that by design or is that a bug? My initial sense/expectation was that they should be two different lines.

<img width="1120" alt="credits" src="https://user-images.githubusercontent.com/25825222/52538982-295c9b00-2d71-11e9-9ae1-2bc0018563b6.png">

**Comment by SMaxOwok** [comment]
@tsmyre the image credits field is markdown, so you should be able to put a break in by adding an extra return between lines

**Comment by tsmyre** [comment]
Oh! That changed from before. It had been two fields. Thanks, this is brilliant!
