### ISSUE TITLE
Add updating notification

### ISSUE THREAD

**Issue by caosborne89** [ManifoldScholar/manifold#1692]
When we update manifold on our production instance we notice about 15 minutes of downtime. Would it be possible to add a page that could be displayed to users during the upgrade process so that they don't just receive an "ERR_CONNECTION_REFUSED" page? Some page that is themed similar to the application.

**Comment by zdavis** [comment]
Calling this a bug. We'll fix it.

**Comment by zdavis** [comment]
Need to move this to ManifoldScholar/omnibus-manifold

**Comment by zdavis** [comment]
Closing in favor of ManifoldScholar/omnibus-manifold#9
