### ISSUE TITLE
Reader pagination should respect dark mode

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1696]
Opinion: reader pagination should have darker version when in dark mode.  It's kind of intense since the footer is dark too.

![screen shot 2018-11-29 at 3 10 12 pm](https://user-images.githubusercontent.com/8389445/49258105-2a746200-f3e9-11e8-80aa-3c2661dc5093.png)

**Comment by zdavis** [comment]
I think we should do this.
