### ISSUE TITLE
Images in upload components that are meant to accept files have unexpected thumbnail behavior

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1704]
To reproduce, upload an image to the "download file" field at the bottom of project/appearance. You'll get output like this:

![image](https://user-images.githubusercontent.com/255909/49408708-3f673300-f712-11e8-9651-0fa13bc2cafc.png)

**Comment by SMaxOwok** [comment]
Decision was to treat any relative path in `currentPreviewIsPath` as false and not show image preview.
