### ISSUE TITLE
Google analytics integration isn't working as it should

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1713]
On the manifold.umn.edu instance we're not seeing google analytics data in the backend. I've confirmed that Manifold is talking to Google Analytics, but it seems like maybe the Statistics object isn't being updated correctly.

I'll DM you, @SMaxOwok, with some more details.

**Comment by SMaxOwok** [comment]
Can you provide a little more on what exactly you weren't seeing?  After looking at it a bit, it _seems_ to be working ok...

<img width="568" alt="screen shot 2018-12-07 at 3 06 47 pm" src="https://user-images.githubusercontent.com/8389445/49677124-d6ddc600-fa31-11e8-93ab-3a37d19a489e.png">

**Comment by zdavis** [comment]
Didn’t seem to be working on the MN instance

**Comment by zdavis** [comment]
Hmm... working now. Closing until we can further verify / collect more information.
