### ISSUE TITLE
Include all annotations/highlights in notes drawer

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1717]
- Notes drawer should be toggleable to filter by all/mine
- Should also refactor "View all" to respect setting in drawer

**Comment by zdavis** [comment]
I'm not sure I agree with this—that is, I'm not sure that repurposing the notes drawer to show all annotations is the right approach. I'm going to close this for now, and we'll work out a solution to this as we tackle design for annotation groups.
