### ISSUE TITLE
Add field for Original Publication Date on Text Metadata

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#1724]
## Feature Description
For texts out of copyright, add a field for original publication date in the same view as original publication place.

## *Why* is this feature important? *Who* does it help?
For contributors creating new editions of old books and want their students to know when the original edition was published (especially if there were variants)

**Comment by zdavis** [comment]
@tsmyre @susanmpls any objections to adding this field?

**Comment by susanmpls** [comment]
I do not agree that adding an "original publication date" field is the best way to handle this. Sometimes the information is more complex than a simply listing the original publication date--adding the field will work in some use cases, not in others. And, more importantly, there exists a standard practice for sharing this information: we include publication history & source(s) of the text(s) on the copyright page of the work.

Here is an example: in the edition of Edith Wharton's "The Custom of the Country" that is on my bookshelf the copyright page says:

"Copyright 1913 Charles Scribner's Sons
Copyright renewed 1941 by Elisina Tyler
Introduction copyright 1987 by Macmillan Publishing Company
First Scribner Paperback Fiction edition 1997. 
The text for this edition is reprinted from "Novels" by Edith Wharton, pubished by the Library of America, 1986, by permission."

The next page in the book is a note about the original serialization of the text in Scribner's Magazine, a note about Wharton's revison of that text for book publication, and a note about which edition/why they chose to reprint the text for the paperback copy that I have on my shelf.

I would encourage Project Creators or OERs to use this practice, too, as it is standard publishing practice. And even as I say this, I recognize that teachers/instructors/professors making OERs may not be planning to add a new copyright page to the file they are uploading.

**Comment by tsmyre** [comment]
I think this field would be useful for the citation generator. I don't disagree with Susan's note above, but the generator wouldn't be able to comb through to find the original date in a way that it could use. So I would favor this field. Does this map to Dublin Core?

**Comment by zdavis** [comment]
Would be helpful to get to consensus on this. We're not sure how to proceed with this issue. @susanmpls @tsmyre @jojokarlin @mkgold

**Comment by tsmyre** [comment]
I'm still in favor of this.

**Comment by jojokarlin** [comment]
I understand what @susanmpls is saying and also agree with @tsmyre that having clearer fields for this history would help those users unaccustomed to creating publication history pages. Gutenberg doesn't always give the clearest indication of where they are getting their versions--  I usually include the Gutenberg preparer information in Description (which I now realize might be better put in the Publisher fields of Metadata). Perhaps in addition to original publication year we have a text field for publication history? The Publisher category on metadata right now doesn't make the extended publication trail immediately obvious to the wayward classroom edition maker.

**Comment by zdavis** [comment]
Let's proceed with this. I think Susan's argument is strong, and I do think we should encourage publishers to include copyright history within the text itself. That said, many users can't or won't change the source text, and there are at least two really valid use cases for showing this information (citation and instructional uses), and those use cases argue for including this.

**Comment by jojokarlin** [comment]
Sounds good.
