### ISSUE TITLE
File upload promotes original file after canceled upload

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1743]
If I drag/drop a file into the Text uploader and then cancel out from the screen, remove the file, and then upload a new one in its place, the system ignores the new file and persists in uploading the original.

E.g., I drop a ZIP archive into the loader and click continue. I realize I chose the wrong file and click the back button, remove the original file from the deck, and then load the correct file. Despite processing the new file, when I proceed the original file I canceled out of loads instead into the reader.

**Comment by SMaxOwok** [comment]
Confirmed not replicable on Edge/local with @tsmyre.  Might be an outdated issue.  Will reopen if seen again.
