### ISSUE TITLE
Add Maker names to ElasticSearch index

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#1760]
## Feature Description
I think a search field for authors would be helpful

## *Why* is this feature important? *Who* does it help?
This would help students trying to search for texts uploaded by their instructor.

## User Stories
I am a student in a class and would like to find all the texts created by instructor. I search by my instructor's name but nothing comes up. It would be helpful to see author's names in search results.

**Comment by SMaxOwok** [comment]
Off the top of my head, I believe this is already included.  Need to double check as it might just require updating indexes on the instance instead.

**Comment by SMaxOwok** [comment]
@krosemichael do you remember what instance you were on when you opened this issue?

**Comment by krosemichael** [comment]
I was on the CUNY instance, but I think that I must have been confused because I can search by author now. You can close this ticket - sorry for the hassle!

**Comment by SMaxOwok** [comment]
Closing.  Sounds like this was an outdated indices issue.
