### ISSUE TITLE
Video playback not working

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1761]
After loading a video to a project, it can be viewed from the Resource page, but when placed on a text, the preview modal that pops up doesn't show the video. @jojokarlin reports a 404 error on the CUNY instance, and on Edge, when clicking the resource thumbnail in the text, the user only get a blank screen with no error noted.

**Comment by zdavis** [comment]
This fix has been deployed to the CUNY instance @jojokarlin
