### ISSUE TITLE
Can't delete projects that have added resources in bulk

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1803]
After having added resources to a project in bulk, I am unable to delete the project without first having to delete each bulk-added resource individually. [This](https://manifold.ecds.emory.edu/backend/projects/e0c2102f-477e-4558-86b6-2cad40440449/general) draft project on a pilot instance is one such project where resources were added in bulk.

**Comment by tsmyre** [comment]
This also has come up on the Liverpool instance. I needed to delete each resource that was bulk loaded before I could delete the project.


Here's the [CSV file](https://github.com/ManifoldScholar/manifold/files/2854808/resource-log.csv.zip) I used, and this is the Drive ID: `1rAx3esu-2kgMYmRioY7hGyXJ1HImseQS`.

**Comment by SMaxOwok** [comment]
I have a strong feeling this is related to #1935 and events.

**Comment by SMaxOwok** [comment]
Ok, I was wrong:

```
ActiveRecord::RecordNotFound: Couldn't find ActsAsTaggableOn::Tag with 'id'=90
```
