### ISSUE TITLE
Show errors in new resource interface

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1825]
It seems we're not surfacing errors in the new resource backend interface. Steps to reproduce:

1. Make a new resource
2. Set type to link
3. Enter http://google.com as the URL.
4. Save the resource.

Repeat steps 1-4. Look at console for errors message.

**Comment by SMaxOwok** [comment]
@zdavis am I guessing right that you're talking about the action callouts here?  I don't see this behavior in the resource backend, but might be looking in the wrong place...

Can you confirm you're still seeing this too?  I replicated something similar in action callouts earlier and am not seeing it now.

**Comment by SMaxOwok** [comment]
Talked IRL and am closing for now.  Will open if reproduced.
