### ISSUE TITLE
Refactor `Collection` to `ResourceCollection`

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1840]
Currently a collection of resources has a model called `Collection`.  I believe this is too vague and should be renamed to better illustrate what it actually represents.  There can already be some confusion between a `ProjectCollection` and a `Project`'s `Collection`.

For instance, in the frontend we define a container with a project's list of resources as `ProjectResources`.  Following that convention resource collections would go in `ProjectCollections`, but that is already defined as a list of `ProjectCollection` records.

I'm proposing we refactor `Collection` to `ResourceCollection`.

**Comment by zdavis** [comment]
Resolved in d31a66123cd3f2cfbad496a036bce299be93a8c8 and following.
