### ISSUE TITLE
Use appropriate icon for ActionCall drawer header

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1876]
<img width="649" alt="screen shot 2019-02-04 at 2 53 39 pm" src="https://user-images.githubusercontent.com/8389445/52242935-e8561980-288c-11e9-8225-85d7e8389317.png">

**Comment by zdavis** [comment]
Let's use schmutzfinger. May need to be added to the icon component.

![image](https://user-images.githubusercontent.com/255909/52354704-c6bc7580-29e5-11e9-938e-3dbfd2218bd8.png)
