### ISSUE TITLE
Change "Restart Ingestion" button 

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#1882]
## Feature Description

When ingestion is complete, a button appears outside of the frame of the execution status report that says "Restart Ingestion" with a red X. It looks like an error message when it is actually a call to action. Recommend changing the icon, perhaps to a green circle.

## *Why* is this feature important? *Who* does it help?

The red X can be confusing and cause a user to re-ingest by mistake.

## User Stories

I am a new user creating a project. I ingested a text and now I'm getting what looks like a warning and think I have done something wrong. 

## Design Notes

Maybe a re-do circular arrow would be nice - in Manifold green.

**Comment by zdavis** [comment]
Assigning to @laelito for now.

**Comment by zdavis** [comment]
We have a new icon for this in sketch file v1.8.4

![image](https://user-images.githubusercontent.com/255909/53599945-304f2000-3b5d-11e9-9499-c302b7a555ee.png)

**Comment by krosemichael** [comment]
It's perfect!
