### ISSUE TITLE
Document content block best practices within Manifold

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1904]
## Feature Description
Provide documentation within the content blocks interface that suggests how to organize blocks for different kinds of content (see the list at the top of #1209). In addition, provide documentation for each available content block that shows an example of what it looks like 

## *Why* is this feature important? *Who* does it help?
Content blocks are cool, but we're worried that users won't be able to figure out how to put them to good use. We also acknowledge that expecting users to leave the app and read documentation isn't necessarily realistic. One feature that's really lacking in Manifold is opportunities for getting help or instructions within the app itself. This feature would involve building help screens within the content blocks interface. In the long run, we may want to apply the conventions we establish here in other parts of the application.

## User Stories

As a user using the content blocks interface in the backend...
  ...I can click a help icon for the content blocks interfaces as a whole
  ...I can click a help icon for each available content block
 
As a user viewing the content blocks help screen...
  ...I can see a screen that lets me pick from the seven types of projects defined in #1209 
  ...I can pick a project type and see what content blocks are recommended for that project
  ...I can pick a project type and see a brief written explanation of the recommended blocks
  ...Maybe: I can press a button in the interface to replace the existing content blocks with the recommended configuration (the markdown block would be assigned placeholder text, and the TOC would default to the first text on the project) 

As a user viewing the help screen for a specific content block
  ...I can see a graphical representation of what the block might look like
  ...I can read a brief explanation of the configuration options for the block that includes recommendations about how to configure it for different types of projects

## Design Notes

We're envisioning this as a modal interface, as there will likely be too much content for a tool tip. Ideally, this interface could be used in the future to document other complex parts of Manifold.

**Comment by zdavis** [comment]
When we release 3.0, we will provide this documentation in the manifold docs. We will gather feedback and then move it to the app itself, hopefully for a 3.1 release.

**Comment by zdavis** [comment]
_Here is my first pass at a writeup of what each block does:_

**Markdown Block**

The Markdown Block allows editors to create sections of markdown content on a project page. The block can be assigned a gray background to help it stand out from other content on the page. Possible uses of this block include adding descriptive text about the project or supplemental textual content.

**Metadata Block**

The Metadata Block will render metadata about the project in three columns. Project metadata is managed on the “metadata” tab of the project record. This block will not render if no metadata has been added to a project.

**Texts Block**

The Text Block lists some or all texts associated with the project. The texts that are included in the list can be filtered to only include texts from one or more categories. The block can be configured to include or exclude author names, subtitles, dates, descriptions, and cover images in the output. The list can also be configured to group texts by category.

**Recent Activity Block**

The Recent Activity block lists the last six activity records for the project. Activity records can be managed on the project’s “activity” tab. If a project contains more than six activity records, users will be shown a button that links to the full, paginated list of activity on a separate screen.

**Resources Block**

The Resources Block renders a teaser of the ten most recently updated resources on a project, accompanied by a link to the resource library for that project as well as the total number of resources on the project. If the “Show All Collections” switch is enabled, this block will also list each of the project’s resource collections. The block can be configured to only show specific collections if desired. If the project has collections, the block will also render a link to the “all collections” view for the project.

**Table of Contents Block**

The Table of Contents Block renders the table of contents for a specific text in the project. This block is especially useful for projects that only have one text, in which cases it’s generally more useful to render a TOC than to render a list of project texts. The editor must specify which text the Table of Contents should draw from, and the depth field can be used to limit the depth of the table of contents (the default limit is six).

**Comment by zdavis** [comment]
Closing this for now, as we decided to go with a different approach (see #1910). That said, @jojokarlin or @tsmyre may want to include the content above, or a variation on it, in our documentation.

**Comment by tsmyre** [comment]
Oh, I can assure you I def. will. Thanks!
