### ISSUE TITLE
Implement project layout scaffolding

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1910]
Following the discussion of project type templates, we agreed to scaffold blocks for a project based on a type specified during creation.

Completing this task involves a few things:

API:
- [x] Remove text requirement from TOC Block
- [x] Add `complete` (or some name) method to each block class.  This should require certain attributes/relationships are set before a block is considered "complete" or "renderable".
- [x] Adjust service added in 9e3a619 to handle arbitrary blocks or blocks specified by a kind.  The kind will be specified by a param posted during project creation.
- [x] Adjust permissions on content blocks based on user role.  If a block is incomplete, only a project editor or above can see it on frontend.

Client:
- [x] Add a dropdown to new project screen that shows available template kinds.
- [x] Add indicator (a little "!" ?) to backend content blocks to mark an incomplete block.
- [x] Add frontend components for incomplete content blocks.  Base visibility on current user permissions.

**Comment by laelito** [comment]
Let's do a simple inline notification to let admins know when a Content Block needs their attention.

The styling would be essentially the same as a standalone information dropdown banner, but contained within the content area of the Block.

![screen shot 2019-02-11 at 4 40 28 pm](https://user-images.githubusercontent.com/26985828/52603468-c5db7780-2e1b-11e9-9c2e-d094320fb590.jpg)

**Comment by zdavis** [comment]
@mkgold Are you OK with this design? ☝️

**Comment by mkgold** [comment]
This looks great. One thing that might be confusing to users: is it just the area in yellow that won't be displayed or the entire Texts section, including the Text icon and the word "Texts"?
