### ISSUE TITLE
Enable Markdown for text descriptions

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1911]
Since we can now surface the contents of the text description field in a forward facing way with blocks, it would be good to enable markdown formatting of the field so more robust text styles can be employed, esp. italics and linking: 

<img width="1093" alt="description" src="https://user-images.githubusercontent.com/25825222/52457380-0dfa5180-2b1f-11e9-871d-4e93988ba4f9.png">

**Comment by zdavis** [comment]
Looks like you're talking about "Text descriptions," not "project descriptions". Adjusting title of issue accordingly.
