### ISSUE TITLE
Hero upload forces open a new button drawer

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1913]
When I go to load a zip archive as a downloadable file in the hero blade, as the upload is being transmitted a new button drawer slides open:

<img width="1168" alt="screen shot 2019-02-07 at 10 02 49 pm" src="https://user-images.githubusercontent.com/25825222/52458448-06d64200-2b25-11e9-811b-a5e7b7ff39e9.png">

**Comment by SMaxOwok** [comment]
Bug is here:
https://github.com/ManifoldScholar/manifold/blob/master/client/src/backend/containers/action-callout/New.js#L41


When the form is submitted, render is called again and the model passed in is the initial pending one.
