### ISSUE TITLE
Hero block uses wrong project image

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1914]
Currently the project hero block is rendering the `Project.Cover` component.  This component is poorly named though, as it is really the project avatar.

https://github.com/ManifoldScholar/manifold/blob/master/client/src/frontend/components/project/Cover.js

Suggestion would be to rename that existing component to `Project.Avatar` and make a new `Project.Cover` component that uses the correctly `project.coverStyles.medium` attribute for its source.

The hero block should ultimately first look for a cover image, then fallback to the avatar image.

**Comment by zdavis** [comment]
Agree with suggestion. I'm going to refactor `Cover` to `Avatar` and move it into global components, since it looks like a backend ProjectCollection component is importing it (and crossing the frontend/backend division)

**Comment by zdavis** [comment]
Also renaming Project.Thumbnail to Project.GridItem, since the difference between Thumbnail and Avatar is confusing.
