### ISSUE TITLE
Improve word doc ingestion TOC generation

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1924]
See https://edge.manifoldapp.org/projects/the-urban-domestic

Something went awfully wrong with the TOC generation here. Investigate.

**Comment by SMaxOwok** [comment]
It looks like there are tons of h2s with no content... Maybe we should make sure that document headers have content before we assign them IDs for TOC generation.

**Comment by zdavis** [comment]
Yeah, that's what I'm thinking.

**Comment by zdavis** [comment]
Pull request on the way for this. When my fix is applied, the same doc ends up with this as TOC:

![image](https://user-images.githubusercontent.com/255909/52827289-0be14700-3079-11e9-9573-b20e24396d8f.png)

**Comment by mkgold** [comment]
nice work on this, and thanks
