### ISSUE TITLE
Automatically parse youtube and vimeo URls

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#1949]
## Feature Description

Some users have expressed confusion about what the Video ID is in YouTube and Vimeo videos when adding videos as resources to their projects.

## *Why* is this feature important? *Who* does it help?

Making this process clearer would benefit users who are adding video resources but do not know what a video id is.

## User Stories

I am an instructor who wants to add a video resource to my Manifold project. The add resources page requests the video id. I enter in the URL but it doesn't work. I'm not sure where to find the video id. 

## Design Notes

A line of explanatory text might do the job, or is there a way to set it to extract the video id from the URL?

**Comment by zdavis** [comment]
Updating issue title.

We should do both—add instructions below the field (open to suggestions on exact wording) and add a mechanism to extract the ID from the URL.

**Comment by zdavis** [comment]
Breaking into two issues—I'd treat missing instructions as a bug and the ability to extract IDs from the URLs as a feature. See related #1950
