### ISSUE TITLE
Add mechanism to view "My Projects" to the back end

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#1954]
## Feature Description

A quick way to view and access all the projects I have created in the back end.

## *Why* is this feature important? *Who* does it help?

This feature would particularly help users who are uploading many texts, will be returning to a project to continue to build it over a longer period of time, or will often want to return to a text that they uploaded a while ago to make changes. 

## User Stories

I am an instructor who is putting all of the novels I am teaching this semester on Manifold. I will be working on this over the course of several months, so the texts that I previously ingested will no longer be in the "Recently Updated" list, but I'd like a quick way to access them.

**Comment by zdavis** [comment]
Let's implement this as a new filter option on the all projects list in the BE.
