### ISSUE TITLE
Top Nav bar display issue

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1961]
Yesterday, Krysia and I gave a workshop at Hunter College. The computer in the room, which was attached to a display system, (multiple large TVs around the room) showed the profile icon and "enter admin mode" buttons not in the upper right of the page, as expected, but rather bumped down a line and aligned to the left side of the page. screenshots below, along with some computer info I grabbed from supportdetails.com

![img_8307](https://user-images.githubusercontent.com/278503/53529826-e2361000-3abb-11e9-9742-74322dac242b.JPG)
![img_8306](https://user-images.githubusercontent.com/278503/53529828-e2361000-3abb-11e9-83fb-50811fa1da3a.JPG)
![img_8305](https://user-images.githubusercontent.com/278503/53529829-e2361000-3abb-11e9-9154-010221ee137f.JPG)
![img_8304](https://user-images.githubusercontent.com/278503/53529830-e2361000-3abb-11e9-9261-f1cc4c87953a.JPG)
![img_8303](https://user-images.githubusercontent.com/278503/53529831-e2361000-3abb-11e9-9aa5-6309e6b5a3d2.JPG)

**Comment by zdavis** [comment]
I don't think we should devote resources to supporting Firefox 45. Firefox is a fairly evergreen browser that we can generally rely on to be current. Firefox 45 is two years out of date, and it's likely that we're taking advantage of CSS functionality that's not present in it.

I'm unable to reproduce this in a current version of Firefox, or in Chrome.

**Comment by zdavis** [comment]
See https://caniuse.com/#compare=firefox+45,firefox+65 for differences in terms of what is not supported in FF45 vs 65, the current version.

**Comment by mkgold** [comment]
Okay -- thanks. I will let the Hunter team know that the browser on that computer is two years out of date!!

**Comment by zdavis** [comment]
Thanks, Matt!
