### ISSUE TITLE
Draft content can't be selected in select inputs because it is not indexed

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1969]
To reproduce:

1. Make a draft project
2. Add a resource collection. It won't be added to the index because the project is draft.
3. Add a resources content block to the project. Try to select the resource collection in the content block. You can't because it hasn't been indexed.

We probably need to add draft records to the ES index and conditionally exclude them from results; or we need to stop using the ES index for finding records in the backend.

**Comment by SMaxOwok** [comment]
I'm not actually sure that's the problem.  I think something is wrong with the HasMany component.
