### ISSUE TITLE
Implement Standalone Projects

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1970]
**The problem**

Some users just want to put a single project on Manifold. For these cases, the home page that shows a library of projects is useless and confusing. Some users want to put multiple projects on Manifold, but they want to link to them from an existing site. We've talked to presses who already have an online presence with a page devoted to each book, and they'd like to just add a button to those pages that link directly to the project pages.

**UX**

To address these use cases, we want to develop a new "stand-alone" mode for projects. This is something that could be enabled on a project-by-project basis. Currently, projects are relatively flat. A project can include the following 7 pages:

- [Project Landing Page](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes) 
  - [Resources](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resources)
    - [A Resource](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource/tennessee-farmer-1834-1839)
  - [Resource Collections](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource-collections)
    - [A Resource Collection](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource-collection/node-210631)
     - [A Resource in a Collection](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource-collection/node-210631/resource/tennessee-farmer-1834-1839)
  - [Events](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/events)

This feature would be limited to these seven project pages, which I'll refer to as "project pages" going forward. 

Any project page can be rendered in _standalone_ mode or in _library_ mode. When a project page is rendered in standalone mode, it will show a new header and header navigation. Because we will be concealing the presence of the library, from the header the user will only need to access login + search. We may want to remove the Manifold logo in this case, and make the hero area be the top of the page. Or, we may want to replace the existing header with project-specific navigation. For example, we might have the following links in the standalone header:

home > project landing page
resources > resources page
collections > collections page
activity > activity page

Keep in mind, not all projects will have resources / collections / activity, which might inform the approach.

We will also need to change the footer, which currently has links to library pages. I think we can probably remove the first row of the footer and use a smaller footer with the copyright + powered by Manifold language.

We don't anticipate that any changes need to be made to the reader.

**Implementation Details**

In the backend we will render a link to the project in standalone mode. That url might be /projects/some-project?mode=standalone.

When a user visits a project in standalone mode, a session variable will be set that tells Manifold that the user is looking at projects in standalone mode.

When a project page is requested, it will render in standalone mode or in library  mode depending on the variable in the user's session.

When a user visits any frontend page other than the 7 listed above, the session variable will be cleared. So, visiting a project in standalone mode, then navigating to the library (via some other external link) will put the user back in library mode.

**Comment by zdavis** [comment]
- Optional back link bar that can be used to contextualize a project. Text and link target can be set on a project-by-project basis. In the example, we show a “University of Minnesota Press” bar at the top that takes the user back to the press website. This bar might be used to return the user to the book page on an existing press site, for example. Or a professor might use it to return the student to blackboard or some other crummy LMS.
- Color of back link bar will be configurable
- We decided that primary nav is not really necessary for stand alone projects. Users can navigate to the various sections fine—let’s keep it simple and clean!
- On the project landing page, the project title + subtitle is shown in a large header.
- On interior project pages (resources, activity, etc.) the header bar is a little bit shorter.
- We remove page navigation from the footer. We probably will need to work press logos into the footer, which we can do.
- Comps show what the header looks like for a standalone project when the hero is in dark mode, light mode, and has a BG image.

Feedback, as always, is much appreciated.
https://marvelapp.com/4iaddjh

**Comment by zdavis** [comment]
I have some initial thoughts on this standalone triggering mechanism, but my thinking is still pretty fluid and I'm open to alternative suggestions.

I think there’s a setting on the project that can be:

1. Standalone Mode Enabled
2. Standalone Mode Enforced
3. Standalone Mode Disabled

I’m not sure we actually need a session key here… we could just store this in the redux state.
The mechanism for triggering standalone mode for a project is a ?standalone query string.

When a project is view in standalone mode, we could store something in the store to indicate that standalone mode is enabled for the project. When the frontend header is rendered (indicating we’re no longer in standalone mode), we could remove that value from the store.

We also need a settings value for standalone project backlink text and URL, and override fields on each project.

**Comment by tsmyre** [comment]
What's the difference between Enabled and Enforced?

**Comment by zdavis** [comment]
If it’s enforced, the project will only display standalone. If enabled, it
can display in standalone or library mode, depending on the request.

**Comment by SMaxOwok** [comment]
Some progress has been started on `mo/1970`

**Comment by zdavis** [comment]
Implemented in #2296
