### ISSUE TITLE
Correct project draft field instructions

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1988]
Should be:
"Draft projects are only visible to users with editorial permissions"

Or something. @tsmyre care to improve the language?

**Comment by tsmyre** [comment]
I'm not sure if this is am improvement, but what about, "Draft projects are only visible to users who can modify its settings".

**Comment by zdavis** [comment]
Let's go with:
```
A draft project is only visible to users who are able to modify it.
```
That echoes the "can modify project" language from the permissions form.
