### ISSUE TITLE
Download arrows on the hero point right

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2022]
For the calls-to-action section of the Hero Block, the arrows in buttons associated with downloads presently point right. They should instead point downward:

![dload](https://user-images.githubusercontent.com/25825222/54376431-0d3e6900-4651-11e9-9cd0-2cca505f2ed0.png)

**Comment by SMaxOwok** [comment]
@tsmyre can you confirm you're selecting the download type for these? They look correct in all contexts to me.

**Comment by tsmyre** [comment]
No, I can't. I went back to the same project and it was pointing down. I didn't change anything. When I looked at the settings it listed as download. I then moved it all around and it retained the down arrow. I don't know what was going on, but it seems to be correct now.

**Comment by SMaxOwok** [comment]
Closing for now, but reopen if it pops back up.  Your screenshot is definitely convincing...
