### ISSUE TITLE
A citation loop feature

### ISSUE THREAD

**Issue by rhoadsstevens** [ManifoldScholar/manifold#2048]
## Feature Description
From a Categorized text in Manifold, I wish it were possible to provide a link to a passage in the Published text. Then, from that passage in the Published text, it would be great to be able to get back to that original place in the Categorized text. 

For example, if the Categorized text was a piece of criticism about _Beneto Cereno_, then it would be cool if that text could cite passages in _Beneto Cereno_ that are linked to a Published text of _Beneto Cereno_. So the reader would be able to see the cited passage in context, and then, when finished, it would be great if they could get back to their starting point. It would be a loop. 

## *Why* is this feature important? *Who* does it help?
I have noticed, via a pilot, that grad students and faculty members like the idea of combining Public Domain works of literature with their own supporting materials--like criticism. It would be fantastic if Manifold texts were linked together and if readers could always get back to their starting points.

**Comment by mkgold** [comment]
Thank you for this suggestion, Elliott! This is in line with a feature request we are working on that will allow people to link to specific places in a text. We are going to create a new ticket called "“Expose interface for generating a link to a text node in the reader” to manage this feature and we will link to your feature request here to keep your use case in mind as we develop.
