### ISSUE TITLE
Reader resource drawer scrolls horizontally with long titles

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2052]
![drawer](https://user-images.githubusercontent.com/8389445/54629306-89abc000-4a34-11e9-9d74-a1b2254fecfc.gif)

**Comment by SMaxOwok** [comment]
Seems like the class on these isn't working as expected anymore.

```
.vertical-list-primary ul .name .truncate {
    display: block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
```

**Comment by zdavis** [comment]
@dananjohnson Could you please add the truncation to `.entity-row__text` in my zd/list-refactor-2 branch and close this issue in your commit? Thanks!

**Comment by SMaxOwok** [comment]
This is from `zd/list-refactor-2`.  Not sure if it will apply after your changes, @dananjohnson, but worth confirming it doesn't look this way after.

![Screen Shot 2019-03-28 at 2 01 35 PM](https://user-images.githubusercontent.com/8389445/55192667-44893b80-5162-11e9-8cd3-d827c4be08e5.png)
