### ISSUE TITLE
Give Project Creators power change roles via Permissions? 

### ISSUE THREAD

**Issue by rhoadsstevens** [ManifoldScholar/manifold#2054]
## Expected Behavior
We are using Version 2, and it seems like Project Creators should be able to give Readers powers via Permissions. 

## Current Behavior
Right now, if a Project Creator clicks Permissions, they get a 403 error message. It would be better if they could bring in Readers and empower them in a project.

**Comment by SMaxOwok** [comment]
This has been fixed in 61056e9 which will be included in v3.0.

Permissions list item visibility has been fixed to only those who can set permissions.
Project creators are allowed to set permissions for their owned projects.
