### ISSUE TITLE
User unsubscribe all button has wrong color

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2063]
<img width="400" alt="Screen Shot 2019-03-22 at 8 21 49 AM" src="https://user-images.githubusercontent.com/8389445/54833758-f1a01780-4c7b-11e9-8b84-d124c27edd7d.png">

**Comment by SMaxOwok** [comment]
Maybe this is intended?  It looks weird to me, but it's occurring to me that it might be because it's a negative action.

Looking for confirmation.

**Comment by zdavis** [comment]
Agree that it shouldn't be red. I think we need to reconsider whether it and reset pw should be green though. Adding design label and will discuss with LT.

**Comment by zdavis** [comment]
Lael to make the green neutral; red is good as is. These changes extend only to the action navigations that appear below record headers in drawers and in the main backend content area.

**Comment by zdavis** [comment]
Make reset pw and unsubscribe $neutral50 (9A9A9A). 

![image](https://user-images.githubusercontent.com/255909/55182068-392a1600-514a-11e9-9f4b-9f4254413446.png)

**Comment by zdavis** [comment]
Also, the icon in the current implementation is wrong. Here's the correct icon.

[mail-icon.zip](https://github.com/ManifoldScholar/manifold/files/3019624/mail-icon.zip)

**Comment by laelito** [comment]
Latest production art now reflects this icon color change for neutral actions.
