### ISSUE TITLE
Drawer pagination is wrapping weirdly

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2066]
![pagination](https://user-images.githubusercontent.com/8389445/54850981-cdf1c700-4ca5-11e9-9908-4ae89cb95d1f.gif)

**Comment by zdavis** [comment]
I can look at this during list refactor.

**Comment by zdavis** [comment]
@SMaxOwok could you check if this is still an issue in my zd/list-refactor-2 branch? If it isn't, let me know and I'll make sure that PR closes this issue.

**Comment by SMaxOwok** [comment]
@zdavis I think it resolves the problem.  It gets a little hectic with a lot of options, but never wraps or looks weird.

![Screen Shot 2019-03-28 at 2 00 32 PM](https://user-images.githubusercontent.com/8389445/55192585-0b50cb80-5162-11e9-9b42-f457b87c50ad.png)

**Comment by zdavis** [comment]
I'll address this.
