### ISSUE TITLE
Upgrade eslint config

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2068]
Upgrade eslint-config-airbnb to 16 and fix things.

**Comment by ConnorChristensen** [comment]
@zdavis 
Should I still use v16, or should I use v17 which is the newest one?

**Comment by zdavis** [comment]
V17. Consult with max and Alexa if there are rules that require difficult
code changes, as we may choose not to enforce them.

Zach

**Comment by zdavis** [comment]
This has been done. `eslint-config-airbnb` is currently at v18 in manifold. There are rules we should consider enabling and addressing, but I think this issue can be closed.
