### ISSUE TITLE
Deprecate icon: arrowBack64

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2093]
In Sketch file v1.8.9, `icon/64/arrow-back` will be removed. It will be replaced by `icon/64/circle-arrow-left`. All instances of `arrowBack64` in code will need to be replaced with `circleArrowLeft64`.

When this has been removed from code, update this issue, at which point the icon can be removed from the sketch file.

**Comment by zdavis** [comment]
@laelito We have removed arrowBack64 from code, and it can now be removed from your sketch file. Thanks!

**Comment by laelito** [comment]
Thanks @zdavis!
