### ISSUE TITLE
Toggle Feature publication from list view

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2105]
Presently, to swap out the Feature on the site, I need to go into the feature that is now live and toggle it's published slider off and then nav to the feature I want live, enter its record, and move that slider to published. It would be nice if those sliders were exposed on the list of all of features for an instance so they could be changed directly from that view.

**Comment by zdavis** [comment]
There's already a convention for this around managing membership of resources in resource collections. The markup and UX is all in place—we'd just need to add an update API call to the features list container. Easy.
