### ISSUE TITLE
Design missing SVG icons

### ISSUE THREAD

**Issue by dananjohnson** [ManifoldScholar/manifold#2110]
We need design assets for these icons to be able to finish replacing all icon font instances with SVG components. I'll update this list as I discover any other missing icons.

- [x] checkmark (16)
![Screen Shot 2019-04-02 at 3 07 44 PM](https://user-images.githubusercontent.com/12454203/55514780-d63ef000-561d-11e9-846e-6f874a3aaf6a.png)

- [x] ~bold close (16)~
![Screen Shot 2019-04-03 at 2 29 30 PM](https://user-images.githubusercontent.com/12454203/55514740-bd363f00-561d-11e9-95ab-909bcb4002e9.png)

- [x] zoom (see [resource collection slideshow](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource-collection/node-210631))
![Screen Shot 2019-04-12 at 2 58 32 PM](https://user-images.githubusercontent.com/12454203/57035517-1edece80-6c07-11e9-95f9-4e1086ed1395.png)

- [x] play outline (16) (see [resource collection](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource-collection/node-210631))
![Screen Shot 2019-04-12 at 3 38 57 PM](https://user-images.githubusercontent.com/12454203/57035581-42a21480-6c07-11e9-9d5f-58e9213a4aad.png)

- [x] eye open (16) (see [resource collection](https://edge.manifoldapp.org/projects/the-adventures-of-sherlock-holmes/resource-collection/node-210631))
![Screen Shot 2019-04-12 at 3 39 52 PM](https://user-images.githubusercontent.com/12454203/57035599-4d5ca980-6c07-11e9-8d51-a911010fabb8.png)

- [x] play (see [resource audio player](https://edge.manifoldapp.org/projects/ivanhoe/resource/outer-limits-audio-intro-e60a4111-2cc7-4716-82bc-9ee3cb7b5b1d))
![Screen Shot 2019-05-01 at 11 34 23 AM](https://user-images.githubusercontent.com/12454203/57035369-aed04880-6c06-11e9-8ccb-bcfd74e3bd71.png)

- [x] pause (see [resource audio player](https://edge.manifoldapp.org/projects/ivanhoe/resource/outer-limits-audio-intro-e60a4111-2cc7-4716-82bc-9ee3cb7b5b1d))
![Screen Shot 2019-05-01 at 11 34 38 AM](https://user-images.githubusercontent.com/12454203/57035372-b42d9300-6c06-11e9-82b5-7fd1e50ff19e.png)

- [x] speaker (see [resource audio player](https://edge.manifoldapp.org/projects/ivanhoe/resource/outer-limits-audio-intro-e60a4111-2cc7-4716-82bc-9ee3cb7b5b1d))
![Screen Shot 2019-05-01 at 11 34 27 AM](https://user-images.githubusercontent.com/12454203/57035378-b8f24700-6c06-11e9-8c07-ba743d47772c.png)

- [x] curved arrow (reader comments panel)
![Screen Shot 2019-05-02 at 2 45 03 PM](https://user-images.githubusercontent.com/12454203/57108961-14950100-6ce9-11e9-9669-e97ec0b9d14c.png)

- [x] speech bubbles (reader comments panel)
![Screen Shot 2019-05-02 at 3 26 00 PM](https://user-images.githubusercontent.com/12454203/57110802-a94e2d80-6cee-11e9-8bae-019cf33c84d9.png)

- [x] speech bubble with lines (resource detail)
![Screen Shot 2019-05-06 at 4 39 13 PM](https://user-images.githubusercontent.com/12454203/57261652-92c11280-701d-11e9-9bb7-99f6b4c9d81c.png)

- [x] detailed pencil (resource detail)
![Screen Shot 2019-05-06 at 4 40 21 PM](https://user-images.githubusercontent.com/12454203/57261693-bd12d000-701d-11e9-86e3-ca27ce59802e.png)
_(for now I've replaced this with the 32x32 annotate icon, but it doesn't look great)_
![Screen Shot 2019-05-06 at 4 40 29 PM](https://user-images.githubusercontent.com/12454203/57261712-d3b92700-701d-11e9-8aee-7d5000370758.png)

- [x] basically everything in this reader menu
![Screen Shot 2019-05-07 at 9 17 38 AM](https://user-images.githubusercontent.com/12454203/57315751-13792080-70a9-11e9-95b4-3c14c837a97e.png)

- [x] filled cube (reader)
![Screen Shot 2019-05-07 at 9 50 16 AM](https://user-images.githubusercontent.com/12454203/57317697-90a69480-70ad-11e9-99f9-fa6c8c5f57ca.png)

- [x] info (bottom of TOC menu in reader)
![Screen Shot 2019-05-07 at 11 57 59 AM](https://user-images.githubusercontent.com/12454203/57325680-6c53b380-70bf-11e9-97b6-81ac7fc40886.png)

**Comment by zdavis** [comment]
Ixnay on the oldbay losecay.

**Comment by laelito** [comment]
and put a checkmark on that checkmark!

rettypay leasepay.

**Comment by dananjohnson** [comment]
onezoday

**Comment by laelito** [comment]
USSSSSSSSYAY

**Comment by laelito** [comment]
@dananjohnson -- Sorry for the delay on these, but all the above icons are now symbols in the production Sketch file. You may need me to make some adjustments, and if so, just let me know.
