### ISSUE TITLE
Improve responsiveness of search filters

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2120]
Looks like on narrower lists these filters get a little weird between 760px and ~960px.
<img width="456" alt="Screen Shot 2019-04-04 at 3 02 09 PM" src="https://user-images.githubusercontent.com/8389445/55591564-aad60700-56ea-11e9-9a31-1bfc637b975e.png">

**Comment by zdavis** [comment]
This was fixed in 9a205a80716754c9306476605e316b94eb21f6b6
