### ISSUE TITLE
Incorrect CSS for all projects link

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2136]
On the demo instance, which doesn't presently have any project collections, the link to `See all projects` isn't rendering as expected.

<img width="1857" alt="demo" src="https://user-images.githubusercontent.com/25825222/55966943-01899680-5c3f-11e9-9840-fcc129dcd5cb.png">

**Comment by zdavis** [comment]
Thanks, Terence. We will def. fix this!

@dananjohnson, I also noticed that the color is incorrect on links in project collection descriptions. For example:

![image](https://user-images.githubusercontent.com/255909/55967332-f890c900-5c2e-11e9-91e1-
9180e98cca28.png)

Given that we _never_ want these links to be blue or purple, can we apply a sane global default to all links?

**Comment by zdavis** [comment]
Please open PR against branch `v3.0.x`

**Comment by dananjohnson** [comment]
Thanks @tsmyre! @zdavis I've got a fix for this that I was just working on yesterday afternoon. While refactoring icons I found a lot of inconsistencies in the markup for project lists on the frontend. I'll open a PR with this commit, which will solve this issue and iron out a handful of other inconsistencies in these lists.

**Comment by zdavis** [comment]
Also here, @dananjohnson 
![image](https://user-images.githubusercontent.com/255909/55992145-b5e7e480-5c60-11e9-9a1e-446155665fbf.png)

Did you apply a global fix for this link color issue?

**Comment by dananjohnson** [comment]
No, let me add that to the PR.

**Comment by dananjohnson** [comment]
Resolved by 713a5af and 72d2af0.
