### ISSUE TITLE
Add language to collections page to indicate that no collections have been created

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2138]
This is bad UX:

![image](https://user-images.githubusercontent.com/255909/55967940-fa0ec100-5c2f-11e9-8a97-620d91efe988.png)

**Comment by zdavis** [comment]
Please open PR against branch `v3.0.x`

**Comment by SMaxOwok** [comment]
Is there any kind of design or language for this?

It looks a little weird just putting in "No collections found" when there aren't any filters. Or maybe filtering should be added along with it?

**Comment by SMaxOwok** [comment]
@laelito can you whip something up for this?  It sounds like we _don't_ want to add filtering here, so just something that signifies there aren't any collections created yet.  Maybe similar to the empty library stuff.

**Comment by zdavis** [comment]
@dananjohnson Just repurpose the project collections placeholder for this. Perhaps in the process of doing this, it makes sense to collapse frontend/project-collection/Placeholder, frontend/project-list/Placeholder, and this new placeholder into a single, reusable component.
