### ISSUE TITLE
Provide GDPR compliant embedding of third party materials

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#2140]
## Feature Description

Provide a GDPR compliant way of embedding resources in Manifold that are not actually hosted by a specific Manifold installation (video streaming resources, interactive resources, ie. iframes etc). A GDPR compliant form of embedding first shows a placeholder with a consent message where the embedded content should appear and before any http request is made to the server from which the content will be embedded. The use has to click on the place holder and afterwards the asynchronous request is made and the content such as a YouTube video is embeded and shown. See [example](https://www.youtube.com/watch?v=lm_HIic6obw) of a Wordpress Plug-In that does exactly that.

## *Why* is this feature important? *Who* does it help?

GDPR requires explicit consent when personal data is processed to other services than the website itself. The IP-address that is processed when content is embedded from external sources is considered personal data. Since this request is made at the moment the page is loaded the user never had a choice to decide if he wants to share his or her IP-address with other services. This effects anyone in the jurisdiction of the European Union

## User Stories

As a University wants to offer publishing services by its own Manifold instance it is blocked in doing so by its data protection officer because the software is not GDPR compliant

## Design Notes

See [example](https://www.youtube.com/watch?v=lm_HIic6obw) of a Wordpress Plug-In that does exactly that.

**Comment by mkgold** [comment]
Thank you for submitting this feature request, @Cutuchiqueno ! We will discuss and update the ticket.

**Comment by mkgold** [comment]
linking this to https://github.com/ManifoldScholar/manifold/issues/2140

**Comment by zdavis** [comment]
Closing because we are tracking all this in #1722. I've added a back-link to this in #1722 so we capture it.
