### ISSUE TITLE
Dates published and updated

### ISSUE THREAD

**Issue by BethFuget** [ManifoldScholar/manifold#2147]
This is a feature request but I don't know how to mark it as such:

Could you give publishers a choice of which dates they'd like to see alongside their project thumbnails? Ideally we'd be able to say whether we want to see the original pub date or the updated date or both. It would also be nice to set whether the updated date should be a fixed date or automatically generated by new activity.

For example, if I have a backlist series of books, I'd like readers to see when they were published so they know how old the work is. It might be that's the only date I want, if nothing's been added. But if it was a 2010 book and my author added resources in 2019, it would be great to say, "Published 2010, updated 2019." If those resources are the only significant updates, I'd like to fix the updated date then, so it doesn't automatically change if (for example) I add a new button or link or make some other minor change. If there's going to be real, ongoing work, though, it would be nice to be able to switch back to the automatically generated updated date you now have, so we could have the original pub date plus the date of the latest changes.

Perhaps toggles for:
pub date - show/hide
updated date - show/hide, set/automatically fetched?

Thanks for considering!

**Comment by BethFuget** [comment]
Another thought: you could perhaps just give people the option to show/hide the "updated" dates. My main concern is avoiding the impression that work is new when it isn't, so if I can hide the "updated" dates, that would solve the problem. It would be great to be able to show the actual pub dates alongside the thumbnails (as suggested above) but if that's too much trouble at this point, I can add them to the descriptive copy instead. Thanks!

**Comment by zdavis** [comment]
Beth reports that the publication date doesn't always save correctly. Need to investigate.

 I agree that we should have an option about whether to show published date, updated date here:

![image](https://user-images.githubusercontent.com/255909/59433390-67b5a580-8db7-11e9-91cb-cdbbd94513b2.png)

**Comment by zdavis** [comment]
Hi Beth,

Thank you so much for your patience on this. In Manifold v4, which is due out in the next couple days, there will be a "finished" flag on projects. For projects that are no longer being worked on, just set the finished switch to on. When this switch is on, Manifold will show the projects published date rather than its last updated date in lists. When the switch is off, Manifold will show when the project was updated. If we run into other cases where Manifold's presentation isn't quite right for finished projects, we can build on this to tweak the presentation based on whether the project is finished or not.

best,
Zach

![image](https://user-images.githubusercontent.com/255909/65463495-af16ed80-de0c-11e9-9718-3a24750b9e5b.png)

**Comment by BethFuget** [comment]
Hi Zach,

Thank you so much for this very elegant solution! Thanks too for the head’s up – I was able to tell our series editor about the change last week and he was pleased to hear it. I’ve updated our backlist books and the collection now looks just the way we want it.

I haven’t had a chance to explore the other updates yet but am looking forward to it.

I hope you and your family and dogs are all doing well, and that you had some good days out at your cabin on the coast this summer.

Take care,
Beth

**Comment by BethFuget** [comment]
I forgot to mention: thanks for the very nice shout-out in your blog post to our Libraries and Accessible Technologies Services team. I'll send them the link to make sure they see it.

All the best,
Beth
________________________________
From: Beth Fuget
Sent: Monday, September 30, 2019 6:26 PM
To: ManifoldScholar/manifold <reply@reply.github.com>
Cc: zach@castironcoding.com <zach@castironcoding.com>
Subject: RE: [ManifoldScholar/manifold] Dates published and updated (#2147)


Hi Zach,



Thank you so much for this very elegant solution! Thanks too for the head’s up – I was able to tell our series editor about the change last week and he was pleased to hear it. I’ve updated our backlist books and the collection now looks just the way we want it.



I haven’t had a chance to explore the other updates yet but am looking forward to it.



I hope you and your family and dogs are all doing well, and that you had some good days out at your cabin on the coast this summer.



Take care,

Beth

**Comment by zdavis** [comment]
Thanks, Beth! I'm happy to hear that the solution solved your problem!
