### ISSUE TITLE
ResourceImportRow results vertical alignment is off

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2157]
![Screen Shot 2019-04-26 at 8 31 26 AM](https://user-images.githubusercontent.com/8389445/56819092-e3ef2c00-67fd-11e9-95e0-50a132fade12.png)

**Comment by dananjohnson** [comment]
I have a fix for this as part of #2113.

**Comment by zdavis** [comment]
Fixed in #2113
