### ISSUE TITLE
Short section bodies prevent resource thumbnails from appearing

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#2161]
Resource thumbnails are not appearing on pages with short text content (Petrarch sonnets) making it impossible to remove anchored resources in the reader.

## Expected Behavior

Each placed resource should show a thumbnail in the left margin which has an X for removing the placed resource.

## Current Behavior

If a resource is placed near the top of a non-scrolling body of text, the annotations will never pass the viewing threshold and will not become visible in the sidebar.

## Possible Solution

Adjust the threshold for threshold for showing/hiding thumbnails. If the annotation is positioned in the top of the window and can't be scrolled, there should be a way to see them.

## Steps to Reproduce

 In Petrarch's Canzoniere, each sonnet lives on its own page. https://cuny.manifoldapp.org/read/untitled-4510b6ee-86b2-4652-aead-4bac733316a0/section/ffdcd187-c38b-48d2-9432-5c20dd76a14e

**Comment by zdavis** [comment]
Sorry it took so long to address this @jojokarlin —this will be fixed in the next release to CUNY
