### ISSUE TITLE
H5P Embed Height Sizing Incorrectly

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2179]
H5P embeds does not always return height correctly. See `https://vpmmanifold.com/read/untitled-9e343a74-5a73-48af-97c5-2693e7612357/section/3123614d-2aa2-47aa-8e33-261ce7157e7a` for a few examples.

**Comment by zdavis** [comment]
https://github.com/davidjbradshaw/iframe-resizer-react

**Comment by tsmyre** [comment]
Will this go with v4?

**Comment by zdavis** [comment]
@tsmyre do you still see the problem on that URL above? It's looking pretty darn good to me.

**Comment by tsmyre** [comment]
Ditto. Looks great from my end too!

**Comment by zdavis** [comment]
Closing.
