### ISSUE TITLE
Review focus styles globally

### ISSUE THREAD

**Issue by dananjohnson** [ManifoldScholar/manifold#2189]
Visually indicating focus needs to be handled application-wide in way that's more consistent, DRY, and in compliance with [color contrast guidelines](https://webaim.org/resources/contrastchecker/).

**Comment by Santoz2** [comment]
Hi, this is Zaijen, a Student Accessibility Assistant from UW.

For reference, a specific example of where indication of focus needs improvement can be seen by attempting to place focus on either the profile icon, or the link to the current page (eg, Home when on the main page).

Currently, this indicator is a thin dotted line, which can be difficult to see, especially for sighted users with low visibility.

**Comment by dananjohnson** [comment]
Hi @Santoz2! Thank you for your feedback! #2269 improves focus styles across Manifold, including replacing the thin dotted line with a stronger focus ring.
