### ISSUE TITLE
Parts of Manifold do not seem to respect SSL configuration

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#2201]
I configured Manifold to use SSL with a certificate from letsencrypt. I also configured it to redirect requests made with http to https. After the upgrade to v 3.0 the browser complains that the connection is unsecure because part of the requests are not encrypted. When I looked into the inspector to track all requests that are made while a page is loaded  I saw the following:

    Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS. 
    the-melusina-intervention:2 Mixed Content: The page at 'https://www.melusinapress.lu/projects/the-melusina-intervention' was loaded over HTTPS, but requested an insecure image 'http://www.melusinapress.lu/system/settings/press_logos/1/small-207f419715469fb31dbdba9cc7ff5a19fa9720ee.png'. This content should also be served over HTTPS. 
    the-melusina-intervention:2 Mixed Content: The page at 'https://www.melusinapress.lu/projects/the-melusina-intervention' was loaded over HTTPS, but requested an insecure image 'http://www.melusinapress.lu/system/settings/press_logo_mobiles/1/small-0e13fd91b743a37e83cf922c448073912ead84ba.png'. This content should also be served over HTTPS. 
    the-melusina-intervention:2 Mixed Content: The page at 'https://www.melusinapress.lu/projects/the-melusina-intervention' was loaded over HTTPS, but requested an insecure image 'http://www.melusinapress.lu/system/maker/2b2dcb9a-45cc-496f-b3f4-492947707ff5/avatar/small_square-9279731bda0632c2f213cc29ac365c4b.jpg'. This content should also be served over HTTPS. 
    the-melusina-intervention:2 Mixed Content: The page at 'https://www.melusinapress.lu/projects/the-melusina-intervention' was loaded over HTTPS, but requested an insecure image 'http://www.melusinapress.lu/system/settings/press_logo_footers/1/original-674552d8839e4b901a6fd59bac508552aad9269a.jpg'. This content should also be served over HTTPS. 
    the-melusina-intervention:1 Mixed Content: The page at 'https://www.melusinapress.lu/projects/the-melusina-intervention' was loaded over HTTPS, but requested an insecure image 'http://www.melusinapress.lu/system/users/avatars/3/f/8/small_square-db157dd854d030aa58232be250488b592e27be59.png'. This content should also be served over HTTPS. 
    the-melusina-intervention:1 Mixed Content: The page at 'https://www.melusinapress.lu/projects/the-melusina-intervention' was loaded over HTTPS, but requested an insecure image 'http://www.melusinapress.lu/system/resource/18c00f55-423c-4fff-90fc-88ab997ffbfc/attachment/small_portrait-8df46d29a73f4afa9fafe3fbc90dfcaf.png'. This content should also be served over HTTPS.

so it seems, uploaded or auto-generated images are requested by Manifold without adhering to the SSL settings. Could that be?

**Comment by zdavis** [comment]
What Manifold URL is triggering these errors?

**Comment by Cutuchiqueno** [comment]
any that pulls-in images, so actually any (you can try your own; our instance is running at the moment).

the curious thing is, that when I take one of the URLs above and load it on its own, the request is automatically redirected to https as it should be the case. Only when the page requests the resource the browser logs that it uses http instead of https.

tried with: https://www.melusinapress.lu/system/resource/18c00f55-423c-4fff-90fc-88ab997ffbfc/attachment/small_portrait-8df46d29a73f4afa9fafe3fbc90dfcaf.png

**Comment by zdavis** [comment]
I'm hoping to look into this tomorrow.

**Comment by zdavis** [comment]
Still on my radar. Hopefully tomorrow.

**Comment by Cutuchiqueno** [comment]
Dear Zach, I would still be interested in solving this. If there is something we can do or provide to facilitate this, please tell us.

**Comment by zdavis** [comment]
Just tried to reproduce this in v4 (which we're hoping to release tomorrow). Was unable to reproduce it in a clean install of the v4 package.

**Comment by Cutuchiqueno** [comment]
ok, I will wait until tomorrow and have a look if it solves by itself via the upgrade.

**Comment by Cutuchiqueno** [comment]
Problem solved after upgrade to 4.0

**Comment by zdavis** [comment]
Hurray!
