### ISSUE TITLE
Incorrect icon in reader text size drawer

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2214]
![image](https://user-images.githubusercontent.com/255909/58509092-93dfee00-814a-11e9-84ea-04cdffbdb1a5.png)

**Comment by dananjohnson** [comment]
@zdavis can you tell me how to reproduce this issue? I don't see it.

**Comment by zdavis** [comment]
I saw it on edge.manifoldapp.org

**Comment by dananjohnson** [comment]
Hmm, I don't see it there either.

**Comment by dananjohnson** [comment]
I didn't update the icons in that panel, since we're waiting on design for them from Lael. So not quite sure what caused the issue you saw.

**Comment by zdavis** [comment]
Closing—unable to reproduce reliably.
