### ISSUE TITLE
Notes panel in reader has invisible tab stops

### ISSUE THREAD

**Issue by avaaec** [ManifoldScholar/manifold#2241]
Hello! 
## Observed Behavior
When opening the notes panel on the reader's banner, keyboard focus lands on the close panel button. When tabbing forward there are two invisible tab stops before reaching the first visible element; the "Your Notes" button. The first invisible tab stop is simply labeled "button" and closes the panel when activated with enter or space. The second invisible tab stop is labeled "Close button" and does nothing when activated. Below is a snippet of what NVDA reads when opening the panel a pressing tab three times.
``` 
ClosePanel button <- this is consistent with the other buttons on the banner

button <- this button is invisible, activating it closes the panel

Close button <- this button is invisible, activating it does nothing

Your Notes button

heading level 2 SEE ALL button
```
## Expected Behavior
It is expected that when the panel is opened focus should land on the close button, like it is, and pressing tab should take one directly to the first visible element: the "Your Notes" button.

## Testing environment
NVDA 2019.1.1
Firefox 60.7.0esr

**Comment by zdavis** [comment]
@dananjohnson, please take a look at this. ☝️ 

Adding accessibility label.

**Comment by dananjohnson** [comment]
Will do!

**Comment by avaaec** [comment]
Fix verfied. :100:
