### ISSUE TITLE
Twitter hashtag query also pulls user tweets

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2256]
For a [new project](https://manifold.umn.edu/projects/anti-book) on the Minnesota instance I included a Twitter query for `#anti-book` but the project also pulled in tweets from user `@_Anti_Book` (even though he didn't use any hash tags), which was unexpected. My sense was a hashtag search would only pull in tweets that employed that hashtag.

**Comment by zdavis** [comment]
We are limited by what twitter search returns. See https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators

What happens if you quote it? "#anti-book"

**Comment by tsmyre** [comment]
Same thing, unfortunately. Though it has given me the sense of a need to bulk delete recent activity cards.

**Comment by zdavis** [comment]
I'm closing this because I don't think it's something I can fix. We're really piggy backing off the twitter search query functionality—I see the same issue in the twitter search UI, so I don't see us fixing this on our end.
