### ISSUE TITLE
Requesting support for Greek characters

### ISSUE THREAD

**Issue by ckatopodis** [ManifoldScholar/manifold#2257]
I'm working on a CUNY student edition of Margaret Fuller's "The Great Lawsuit," and Fuller was someone well-versed in Greek, Latin, French, Italian, and German--all of which she incorporates into her writing. In an effort to offer the public more Manifold editions of amazing women writers like Fuller, getting support for Greek characters (and all of the above) is **essential**.

**Comment by tsmyre** [comment]
Greek, along with any character that can be represented in UTF-8, is supported by Manifold. An [example here](https://demo.manifoldapp.org/read/google-doc-prime/section/d6dd0f56-f276-4967-a625-b9635ef8ee1b#h.hr262mydyhfg) of Greek on one of our demo texts alongside Cyrillic, Hebrew, Chinese, and Arabic.

Are the Greek characters you're using in the Fuller text not coming through? If so, I'd be glad to take a look to better understand what's going on.

**Comment by zdavis** [comment]
Closing due to lack of feedback. @ckatopodis, feel free to update this issue when you're able to provide more information, and we'll reopen it if we're able to act on it.
