### ISSUE TITLE
Night mode renders user links as white in the annotation drawer

### ISSUE THREAD

**Issue by munsonbh** [ManifoldScholar/manifold#226]
iOS 10.2.1

**Comment by zdavis** [comment]
Occurs in all browsers. Good catch. Thank you, Ben.

This one's all yours, @naomiyaki!

<img width="499" alt="screen shot 2017-04-05 at 9 32 06 pm" src="https://cloud.githubusercontent.com/assets/255909/24737993/673484cc-1a47-11e7-9428-7a5ee71ede8e.png">

**Comment by zdavis** [comment]
Additionally, the text in the annotation (and comment) text areas is invisible while in dark mode.
