### ISSUE TITLE
Include section URL in generated citations

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#2266]
## Feature Description
In the "Cite" function in the reader, the generated APA/MLA/Chicago citation should indicate that it is a Manifold edition and include the Manifold specific citation.

## *Why* is this feature important? *Who* does it help?
Manifold does not simulate pages, but many citation methods for ebooks require some indication of pages. Users who wish to cite a Manifold text wish to return to the precise section from the citation (rather than finding the project and searching for the citation). This feature will help students anxious about doing their citations properly (when caught between book and online citation). This feature will help faculty reviewing papers in which their students cite Manifold texts. This feature will help scholars point specifically to attribution in Manifold projects.

**Comment by jojokarlin** [comment]
I just wanted to cite Structuring Equality for the Manifold OER Report and the citation still doesn't note that it is an online source in any tangible way. I think it's important that we include the URL in the citations, especially as people start using these texts to teach.

**Comment by zdavis** [comment]
Closed, will pursue in #2619
