### ISSUE TITLE
Links to pages within Manifold project are not working

### ISSUE THREAD

**Issue by BethFuget** [ManifoldScholar/manifold#2267]
For the last few months, I've used Call-to-Action links on our projects to send people to the TOCs and "start reading" points. I've been using these instead of buttons since our epub files weren't designed properly for the buttons and this seemed a good alternative. There was one small glitch, though not a serious one - the links opened in a new tab, and I believe that Zach was going to do something so readers would stay in the same tab - but as I say, this wasn't a serious problem.

However, I've been out of the office and haven't looked at any of our projects for a few weeks, and just went into them and found that these internal links no longer work at all. It looks like someone might have done something with them - when you click one, it doesn't open in a new tab - but they no longer take you to the right page in the project. Instead, you just get the blank page shown in the "link results" file attached.

I've tried recreating a few of the links but no luck. Is there something else I can do, or something you can do to fix this?

Thanks,
Beth

![Link example](https://user-images.githubusercontent.com/44627983/61011679-78165d00-a330-11e9-86b0-2597ad7f2148.JPG)
![Link results](https://user-images.githubusercontent.com/44627983/61011683-7ba9e400-a330-11e9-8ebb-97f3834a39d4.JPG)

**Comment by zdavis** [comment]
Thanks, Beth. I'm looking into this now. Will update shortly.

**Comment by BethFuget** [comment]
Great - thanks!

**Comment by BethFuget** [comment]
Hi Zach, I was just wondering if you have a sense of when this problem might be solved. Will it likely be soon, or will it take a while yet? I'm wondering if I should remove these links from all our projects and add "Start Reading" buttons instead, as an interim measure. This isn't ideal because (for our epubs) the "Start Reading" buttons take people to the cover images and they have to click through several pages before they can actually start reading, but otherwise, without the links, they can't get into the projects. And this is a bad time for our site to be down in part because we have a proposal before the library administration for funding to continue the pilot. What would you advise? Thanks!

**Comment by zdavis** [comment]
I expect to have it fixed very soon—almost certainly today. I have a pull request in progress that fixes it. I'm planning on releasing to your instance as soon as its done.

**Comment by BethFuget** [comment]
Great - thanks!

**Comment by zdavis** [comment]
Beth, I've merged the fix into the v3.0.x branch and released it to the UW instance. I've checked the links on the Molecular Feminisms book, and they seem to work as expected, but you may want to check a few other projects. Feel free to follow up here if I missed anything with my fix.

**Comment by BethFuget** [comment]
Thanks so much, Zach! I really appreciate it. The links are working fine now.
