### ISSUE TITLE
Consider removing large drop shadow below reader top bar

### ISSUE THREAD

**Issue by munsonbh** [ManifoldScholar/manifold#227]
As a reader I often use the top crop of the reading area as a guide for my place. By including a deep shadow there after scrolling a bit, I no longer have a comfortable break to orient with. I have heard from others that they read in the same way.

**Comment by zdavis** [comment]
Curious to hear what others think. We went back and forth on that drop shadow a bit. If we don't have the shadow, my sense is that we'd need a clear visual separation at the bottom of the header. Without the shadow, I found the cropped text behind the white header a little jarring.

**Comment by laelito** [comment]
Yeah, I can definitely see how the "white-fog" could create some frustration if your eye is naturally landing at the top of the page. Now that we're in beta I think we'll see lots of interesting issues like this—so many people experience and use software in so many different ways, and we're just beginning this 'gather and process the feedback' phase. Going forward I could see several possibilities play out—depending on the consensus that develops. For instance, if people seem to be frustrated by the white-fog, we might replace it with a simple stroke divider. Or perhaps the consensus might be that the menu options bar itself is taking up precious vertical real estate in reader mode (I've never really been 100% sold on the menu header at the top, at least on mobile when reading). So if that's the case, the whole header might move or radically change, which could render the white-fog issue moot.

**Comment by naomiyaki** [comment]
I agree that the more time I spend in the reader, the more I want the header to float away while I'm reading: especially on a long text. Conversely, I find this behavior really annoying on iOS when I'm jumping around between lots of pages so I could see it going both ways. That said, being able to swipe in from the left to get to contents could be fun!

**Comment by mkgold** [comment]
I agree that at the least, the "white fog" transition at the top is a bit too heavy. I wonder if we could, as a first step, make it less strong.

**Comment by zdavis** [comment]
@naomiyaki I'm assigning this to you. Could you try to reduce it a bit and post some before/after screenshots on this issue? Thanks!

**Comment by zdavis** [comment]
Closing — updated reader header design removes the fade. I'll be making separate issues for the redesigned header.
[Manifold_UI_Reading_ALL_v1.5.pdf](https://github.com/ManifoldScholar/manifold/files/1235871/Manifold_UI_Reading_ALL_v1.5.pdf)
