### ISSUE TITLE
URL validation/checking in manuscripts

### ISSUE THREAD

**Issue by crowesn** [ManifoldScholar/manifold#2270]
`As a:` publisher
`I want:` to validate URLs in a manuscript
`So that:` broken/invalid urls can be reported and corrected.

I am trying to import a textbook to manifold with a significant number of url hyperlinks. Some of them are broken 404s I would like to have a way to highlight the broken ones so the author can go in and fix without having to check each one. I tried to use a command line link checker with limited success. It would be nice if there was a bad link flag available after upload in manifold. Or perhaps there is a way to do this that I can do prior to upload.

**Comment by tsmyre** [comment]
Hey Sean, we had the chance to talk about this as a team this morning. Our consensus was that this is a bit beyond the scope of Manifold itself. That said we very much appreciate the impact of link rot on living publications. For the moment we use and recommend the [Linkinator](https://github.com/JustinBeckwith/linkinator) site crawler.  We'll be adding that recommendation to our documentation as well. If you had further thoughts on this, please don't hesitate to reopen the issue.
