### ISSUE TITLE
Annotation controls aren't appearing on iOS devices

### ISSUE THREAD

**Issue by munsonbh** [ManifoldScholar/manifold#228]

**Comment by zdavis** [comment]
Yeah, this was mentioned in the blog post and came up in our meeting today. We're aware of this and it's on our list. The selection API is only partially supported in iOS (http://caniuse.com/#feat=selection-api), so we have to find a work around for the absence of `selectStart` detection.

**Comment by jojokarlin** [comment]
Just putting a note in to request review of this issue -- for teaching and reading, it would be really helpful to get at these texts across iOS devices. I've had a request from a teacher looking how best to advise her class.

**Comment by zdavis** [comment]
Very pleased to report that we have a pull request in the works for this issue, and expect to have it resolved in the next non-patch level release of Manifold.

**Comment by zdavis** [comment]
Oops—that commit doesn't quite fix it, but it does lay the groundwork for a fix. This is still coming soon.

**Comment by jojokarlin** [comment]
This is done now, yes? It worked last week!

**Comment by zdavis** [comment]
It’s functional but I’d like to improve it.

**Comment by zdavis** [comment]
Closing this for now—I've opened #1938 to record the additional improvements I think should be made in terms of mobile annotation.
