### ISSUE TITLE
97% Memory Usage and Segmentation Fault after multiple Re-Ingests of 300pages Publication

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#2309]
Running Manifold 3.0 on Digital Ocean Droplet with Ubuntu 19.04. LTS.

After getting close to our first publication of a 300 pages text we uploaded different versions of the text to the project and had frequent re-ingestions of versions.

At the same time the memory usage of the server went up to 97% without going back in times of no interaction. Then today, the first Error 500 issues appeared when trying to delete a version or to show a text in the reader. Another reason for why this has not come to my attention before is the fact that before I had to shutdown the server when I was not working with it due to unsolved GDPR issues. Now, is the first time it ran for more than a (working) week.

When trying to evaluate via the shell what causes the memory load an the 500 issues and issued `manifold-ctl tail` I received a `Segmentation fault`:

    /usr/bin/manifold-ctl: line 21: 26951 Segmentation fault      (core dumped) /opt/manifold/embedded/bin/omnibus-ctl manifold /opt/manifold/embedded/service/omnibus-ctl $@

When I restart the server and Manifold I am around 49% memory usage. However, any action I carry out on the UI consumes more memory after memory runs full again. At no time, memory is freed again. I evaluated this with htop, but here is also a 1-day selection from the usage statistics of Digital Ocean.

![image](https://user-images.githubusercontent.com/306064/62290527-d9c67480-b461-11e9-9fee-7edd71276232.png)

I basically would have to restart the server every 1-2 days. This is the workload 2 persons doing the aforementioned tasks. However, we plan to get public within the next 2-3 weeks which would significantly increase workload.

**Comment by zdavis** [comment]
How much memory do you have on the VM?

**Comment by Cutuchiqueno** [comment]
8GB

**Comment by zdavis** [comment]
@Cutuchiqueno Does this continue to be a problem?

**Comment by Cutuchiqueno** [comment]
No, it doesn't. Thx for the support.

**Comment by Cutuchiqueno** [comment]
I have to correct myself. Memory consumption remained an ongoing problem until today. Besides the killing of ruby related processes due to lack of memory (see fig. 1 below) we now also experienced the complete freeze of the server due to memory issues.

![grafik](https://user-images.githubusercontent.com/306064/102768522-9b489700-4381-11eb-9c79-1cc0a2dada6e.png)

(Fig. 1)

All these issues happen in synchronization with the jobs that are scheduled with job scheduler of Manifold. Figure 2, for instance, shows the moment in which the server killed one of those Ruby processes. It is exactly in line with the workload that is created by the scheduled jobs.

![grafik](https://user-images.githubusercontent.com/306064/102768885-245fce00-4382-11eb-9e6d-db20fe81de93.png)

(Fig. 2)

All this happens on our operational Manifold instance. Though, I did not find concrete evidence we connect also some data inconsistency issues around annotation data with this problem.

**Comment by zdavis** [comment]
Could you please add swap to the host and see if it mitigates the problem?

**Comment by zdavis** [comment]
We've spent quite a bit of time looking for memory leaks in Manifold over the last few months, and have yet to find the cause. We recently put some application performance monitoring in place on instances we control, and are waiting to see what we catch there. When we're back from the break, next week, I'll follow up with you and we'll put some monitoring on your instance so we can figure out what leads to the memory ballooning. I understand that you think the problem is related to scheduled jobs—it could be, but that's not our sense, since when we do see memory usage increasing, it's always tied to the main puma process and not to the zhong or sidekiq processes that handle scheduled and background jobs.

**Comment by Cutuchiqueno** [comment]
I can confirm the dependency of this issue from puma. In the end, I figured that it is always one of the _puma cluster worker_ processes that grows limitless over time. See output of htop:

![image](https://user-images.githubusercontent.com/306064/107374411-d9437b00-6ae7-11eb-8f6d-6ff0a8d8824b.png)

Thus,  while there are many puma cluster worker processes, it seems always be the one that relates to _manifold api_ which accumulates RAM usage over time.

**Comment by zdavis** [comment]
Stale issue. Closing. Please feel free to reopen if it continues to be a problem.
