### ISSUE TITLE
Annotation selection error in IE11 prevents popup from appearing

### ISSUE THREAD

**Issue by dananjohnson** [ManifoldScholar/manifold#2335]
The following error is logged repeatedly when making a text selection:
```
There was an error in updateSelection: TypeError: Unable to get property 'dataset' of undefined or null reference
```

The error originates from the `updateSelectionState` method in [`client/src/reader/containers/annotation/annotatable-components/CaptureSelection.js`](https://github.com/ManifoldScholar/manifold/blob/6453a961b0cb539cd37c7f105f31d3a569ddb343/client/src/reader/containers/annotation/annotatable-components/CaptureSelection.js#L112)

**Comment by zdavis** [comment]
No longer supporting IE11. Closing issue.
