### ISSUE TITLE
Follow projects from project home page

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#2365]
## Feature Description

When I visit a project, I would love to be able to add that project from that page. 
## *Why* is this feature important? *Who* does it help?
Currently you can only follow a project from the library. As the libraries grow, the "Following" becomes a useful resource for finding the texts, so it would be helpful to be able to Follow from inside the project (once you know what the project is and if it is a project you need to follow). As teachers use the CUNY instance and repurpose textbooks, it would help to use the following to quickly find the projects you want students to use. Making the Following system work across different levels would be very useful.

## User Stories
An instructor browses available titles and wants to mark a book to check out later. Once the instructor enters the project, she would click a + sign to follow.

**Comment by zdavis** [comment]
Closing because this will be addressed in the OER development.
