### ISSUE TITLE
Final v4 Fixes

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2370]
- [x] Show anonymous name on annotation in reader.
- [x] Replace anonymous animal names with [fancy names](https://docs.google.com/spreadsheets/d/1-oLxiL4ZVyOYp5LLSa5WlUZhqrumUiIQZbxgxSqEF18/edit)
- [x] Show lock on anonymous groups in group selector
- [x] Exclude projects where standalone mode is enforced from library
- [x] Do not allow comments on anonymous annotations
- [x] Change RG role name from _Owner_ to _Moderator_.
- [x] Add warning prompt when toggling from a Private or Anonymous group to a Public one.
- [x] Clean up code instructions on group new/edit form.
- [x] When leaving a group, public or anonymous, I cannot access the annotations I left while in the group.
- [x] [Selecting text previously annotated](https://github.com/ManifoldScholar/manifold/files/3637627/Screen.Recording.2019-09-20.at.3.25.57.PM.mov.zip) in a group I no longer belong to throws a 500 error.
- [x] [Selecting annotation group in drawer triggers re-render of popup](https://github.com/ManifoldScholar/manifold/issues/2370#issuecomment-533714521)
- [x] [WithReadingGroups fetch sometimes returns empty array for `readingGroups`](https://github.com/ManifoldScholar/manifold/issues/2370#issuecomment-533726715)
- [x] Enable projects to be [removed from collections manually](https://github.com/ManifoldScholar/manifold/files/3640385/collection.zip).
- [x] Reader error: Failed prop type: Invalid prop `bodyComponent` of type `object` supplied to `UIPanel`, expected `function`.
- [x] ~Poor cover rendering at phone size~

**Comment by dananjohnson** [comment]
![screencast 2019-09-20 14-26-56](https://user-images.githubusercontent.com/12454203/65359946-e38f6d00-dbb2-11e9-9dd7-bbea0de7314b.gif)

**Comment by dananjohnson** [comment]
**To reproduce:** From logged out state, log in within the reader and then highlight some text to annotate. Opening the reading group selection will show only the "My Public Annotations" and "My Private Annotations." If you inspect the `Annotation.Popup.Menu` component, you'll see that the prop `readingGroups` is an empty array.

If you leave the reader and return to it and try the same thing, you should now see all the reading groups you are a part of.

One effect of this that the [`currentGroupName`](https://github.com/ManifoldScholar/manifold/blob/f82130929cb42e45815864ad689c1dd4ea00ec0a/client/src/reader/components/annotation/Popup/parts/CurrentReadingGroup.js#L19) getter in Annotation.Popup.CurrentReadingGroup would fail in the event that the current group is anything other than "My Public Annotations" or "My Private Annotations". I'm not certain how one would get into this state, but this a potential cause of the issues @tsmyre is describing.

**Comment by zdavis** [comment]
@tsmyre For this one:
```
Exclude projects where standalone mode is enforced from library
```
I will exclude these projects from two places:
1. The /projects page on the frontend
2. The grid of projects that shows up on the home page when no collections are configured to display

If somebody puts a standalone project in a collection, I think that's on them, and it should display.

**Comment by tsmyre** [comment]
That works for me. That did lead to a new issue though, that I just recorded above: I can't deselect projects from collections manually.

**Comment by tsmyre** [comment]
Also, as of this posting, excluding projects from the library is not working. See Ivanhoe on Edge:

![Screen Shot 2019-09-22 at 8 42 31 PM](https://user-images.githubusercontent.com/25825222/65397930-885ba700-dd79-11e9-8939-d1422c0b9286.png)

![Screen Shot 2019-09-22 at 8 42 23 PM](https://user-images.githubusercontent.com/25825222/65397933-8d205b00-dd79-11e9-884e-745a17c6a2db.png)

**Comment by zdavis** [comment]
I haven’t released any fixes from this issue to edge, so that’s expected.
We will release them all at once.

**Comment by zdavis** [comment]
![image](https://user-images.githubusercontent.com/255909/65454170-6a358b80-ddf9-11e9-9711-ded88d9bb322.png)
