### ISSUE TITLE
Sort Resources by Name as Default

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2400]
On the [GWU instance](https://gwpress.manifoldapp.org/), when bulk ingesting resources they show up in, what appears to be, a random order. It would be useful if they sorted alphabetically A–Z by default. Also, the alpha A–Z sort doesn't seem to always order correctly (e.g.):

_First Page_
![Screen Shot 2019-10-14 at 1 44 38 PM](https://user-images.githubusercontent.com/25825222/66775089-dcddd800-ee88-11e9-8df1-fc15aac44daa.png)

_Last Page_
![Screen Shot 2019-10-14 at 1 44 48 PM](https://user-images.githubusercontent.com/25825222/66775100-e109f580-ee88-11e9-9f11-92f7c2c0a4f3.png)

**Comment by zdavis** [comment]
Currently, the default sorting is by created_at and then the sort_title. We can remove the created_at part of that equation. 

The sorting in your screenshot seems correct to me. `Chapters 6-8` should in fact come after `Chapter 19`, and any computer would order them that way as `chapters` will come after `chapter`. The only way this could be sorted properly would be for the machine to understand the semantic meaning of the two strings, which gets us into more complex territory than we want to be in. We can expose a sorting field, which already exists but is hidden, for exceptional cases like this.
