### ISSUE TITLE
Reports of inability to open resource modal in reader on chrome

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2410]
User is on a surface tablet and reports that clicking on the resource cube in the reader text will not open the modal view. Only by clicking on the thumbnail in the margin will it open. Perhaps it's registering a touch event rather than a click? See if you can reproduce in windows.

**Comment by dananjohnson** [comment]
This isn't a Windows-specific issue. It's based on how we're handling the click: https://github.com/ManifoldScholar/manifold/blob/master/client/src/reader/components/notation/Marker.js#L39-L58.

I think we're assuming here that touch device === mobile device (i.e. on smaller screens, the resources in the margins are hidden), and also that touch devices don't use mice. Neither fits super well with the surface tablet.

**Comment by dananjohnson** [comment]
I'm thinking the condition for that `if/else` should be whether or not the thumbnails in the margin are visible, not if the device supports touch.

**Comment by zdavis** [comment]
What if instead of having this if/else in the click handler, we render two elements in the DOM, each with one side of that if/else attached—and we hide/show them with media queries, since I assume it's media queries that are determining whether or not the thumbnails are visible in the margin. Can you make that happen, DJ?
