### ISSUE TITLE
Buttons not working in IE11

### ISSUE THREAD

**Issue by dananjohnson** [ManifoldScholar/manifold#2422]
All buttons are broken currently in IE11. They don't seem to respond at all to click events. I've tested this locally and on edge.

![screencast 2019-10-31 11-25-52](https://user-images.githubusercontent.com/12454203/67977513-7d483200-fbd5-11e9-945f-cf7960906485.gif)

**Comment by zdavis** [comment]
Decision has been made to drop IE11 support. Closing issue.
