### ISSUE TITLE
BE select color appears black in FF

### ISSUE THREAD

**Issue by dananjohnson** [ManifoldScholar/manifold#2429]
This likely can be traced to trying to set a color for the options, since FF is unique in inheriting this color from the `<select>`, and would otherwise appear white in this context.

<img width="520" alt="Screen Shot 2019-11-07 at 2 25 40 PM" src="https://user-images.githubusercontent.com/12454203/68434035-d6cbd600-016c-11ea-9f87-8fd3a789cf63.png">

**Comment by zdavis** [comment]
I've tried to reproduce this in FF and can't. 
![image](https://user-images.githubusercontent.com/255909/71588704-54f68a00-2ad7-11ea-9ee5-166483d5f39b.png)

Please re-open and provide additional details if this is still an issue.
