### ISSUE TITLE
Nice print view

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#2480]
## Feature Description
Right now, if one goes to print a chapter of a Manifold text, the print view is completely unstyled. Would it be possible to add some minimal amount of styling (the details of which would need discussion) to improve the print view?

## *Why* is this feature important? *Who* does it help?
this would help people who print out chapters for reading and/or class discussion, and also people who want to read on the subway, plane, or other situations where they may not have an internet connection

## User Stories
I'm a faculty member who wants to read a chapter before class. I go to print out a chapter and I'd love it to look a bit better than it does currently

**Comment by mkgold** [comment]
tweet in support of this issue: https://twitter.com/jimccasey1/status/1231774315185655810

**Comment by zdavis** [comment]
@bot plan

**Comment by tsmyre** [comment]
Also in support of this feature are our friends at the CDL.

**Comment by zdavis** [comment]
![image](https://user-images.githubusercontent.com/255909/114789478-086ca780-9d38-11eb-9504-c828461b83aa.png)
