### ISSUE TITLE
Give presses more control over header and footer

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2575]
We've had a few groups want to add logos to the footer or even add an institutional footer. The simplest solution would be to allow users to set HTML+CSS for the press header and the footer. A better solution would be to setup a rudimentary templating mechanism so that dynamic elements (the nav, the logged in/out state, etc) could be incorporated into custom markup. In the past we thought this would be possible with plugins, but a less technical approach is probably more desirable.

**Comment by aupress** [comment]
Scholarly presses and libraries are often required to display their home institution affiliation on their websites, which is true in our own case. Also, we can see a case when a publication project is a collaboration between several organizations or funded by granting agencies which require credit. We find that the current setup is limiting in this regard and even more so when used in the standalone mode. Currently, one cannot add a logo to the footer in sandalone mode. It would be great to have more flexibility in terms of both content and layout of the footer.

Our use of Manifold is exclusively standalone mode, as a companion site to our main website. Ideally, we would like both footers to look identical or near identical to have consistency in visual identity between the two sites. Perhaps the HTML+CSS solution would offer the most flexibility.

We can say the same about the header in standalone mode. Currently one cannot add a logo to the header or header bar. I would be great for brand identity to have that ability.

**Comment by zdavis** [comment]
To solve as part of #2778
