### ISSUE TITLE
Download Source button is not appearing

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2616]
For some texts on the Minnesota instance, the `Download Source` button is not appearing in the BE:

<img width="1034" alt="download" src="https://user-images.githubusercontent.com/25825222/74684818-76e4c280-5192-11ea-9e54-53a3769d1731.png">

Direct link [here](https://manifold.umn.edu/backend/projects/text/5941f88f-ce70-43dd-bb57-5f8fab6dac1f/general).

**Comment by zdavis** [comment]
Was this recently added? In the past, we didn't necessarily keep the ingestion source, so this button may not appear for texts that were ingested before we implemented the download feature. If it was added recently, there may be a bug.

**Comment by tsmyre** [comment]
No, some of these have been sitting around for some time. I haven't noticed this on anything I've recently added, so I'll close this out.
