### ISSUE TITLE
Improve student reading experience in RGs

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2632]
## Feature Description

To date, we're proposing that reading groups should be used for the classroom. One problem with the current approach is that we put a lot of burdens on the reader to make sure their annotation filters are set correctly in the reader. For example, if a professor has used a text in multiple classes, the text might contain a number of public annotations and RG annotations. When students come to the text, they need to open the visibility menu and limit annotations to their RG. This puts too much burden on the student to get the right reading experience.

Ideally, when a student comes to a text that's being used in a reading group they belong to, Manifold should automatically prompt the user to restrict visibility to RG annotations. We need to consider how Manifold knows that the text is being used in the RG. Is it set explicitly on the RG? Does it detect whether there are RG annotations on the text?

Another problem we need to solve is that instructors may want to include annotations on a text that span reading groups. One way to do this would be via the "author" permission. If the instructor were an "author" on the project, her annotations would stand out from the others. However, we need to restore the "author" annotation filter to allow these to show through in the reader.

## *Why* is this feature important? *Who* does it help?
Teachers are having a good first-experience with Manifold, but are finding it harder to use a text the second time, especially after it's cluttered with annotations that are no longer relevant. RGs solve some problems here, but it's too hard for the user to get the view right.

## User Stories
TBD

## Design Notes
TBD

## Development Notes
TBD

**Comment by tsmyre** [comment]
I wonder if there's a way to make that author credential less specific and more versatile. For a press the `author` designation is appropriate, but less so in the classroom, where `instructor` would be more apt. I wonder if the title field itself could be set on a text basis. Presently functionality allows for multiple authors, so having more than one instructor or a mix of instructor, author, or other (TA?) would be good to retain.

**Comment by zdavis** [comment]
I thought about this, and discussed it with Alexa yesterday, but my feeling here is that we should keep some semantic meaning around roles, if not just because having those semantics is essential for explaining what a feature actually is. Adding roles is pretty easy, and adding an instructor role makes sense to me, especially since we may get to a place where there is behavior around instructors that wouldn't be relevant for authors.

**Comment by zdavis** [comment]
Solved, I think, in the OER reading groups work in v8.
