### ISSUE TITLE
Text order set in back end does not persist

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#2636]
When I set the text order in the back end of two projects in the CUNY instance by dragging and dropping them, they do not display in the order that I set. The text order in the front end does not match the text order in the back end.
## Expected Behavior

Texts should display in the order they are placed in in the back end--text order in the front end should match the order in the back end.
## Current Behavior

The order of texts on the front end does not match the order in the back end
## Steps to Reproduce

Examples: https://cuny.manifoldapp.org/projects/eng-111-literature-and-composition; https://cuny.manifoldapp.org/projects/eng225-afro-american-literature
1. Create a project
2. Add multiple texts
3. Arrange text order on the texts page in the back end
4. View text order on the front end

**Comment by zdavis** [comment]
Incorrect issue number referenced in 4560eba29de90273aea18760da1b5d69fc016e7b above.
