### ISSUE TITLE
Citation generator for selected passage

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#269]

**Comment by zdavis** [comment]
Naomi started on this, and may have done the markup. There is design for this feature, and it's ready to be implemented AFAIK.

**Comment by naomiyaki** [comment]
Other than the markup that already exists for annotations and the like I don't think I've added anything additionally for citations specifically, but I'm excited to do it!

**Comment by zdavis** [comment]
Oh, right — we just did the citation UX in the popup, I think. Well, Max, you can take a stab at the CSS for it. I think the trigger to open the citation UI is already present in the annotation popup, just commented out.
