### ISSUE TITLE
Change div links to a links

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2727]
As part of her work with the Manifold team on a preservation grant, Karen Hanson (of Ithaka), discovered that there are situations where links use a `div` instead of semantic `a` link.

**Comment by zdavis** [comment]
Would be so helpful to get an example of where this is happening...

**Comment by tsmyre** [comment]
Whoops. Sorry. Here we go. It is occurring in the Project Resource Library links, navigating from a listed element to the Resource Detail view.

![div](https://user-images.githubusercontent.com/25825222/81445250-1f754380-913e-11ea-9880-1b07233483d4.png)

**Comment by zdavis** [comment]
The markup for these cards is really old. Closing this because we'll tackle it as part of #2732.
