### ISSUE TITLE
Sequence of texts in project mismatch between landing page and admin page

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#2767]
The sequence of texts in a project that the project owner is capable to modify by drag and drop in the admin interface is not completely the same on the landing page of a project:

![image](https://user-images.githubusercontent.com/306064/83663011-94665c80-a5c8-11ea-9b36-ae32375cdae7.png)

This quite a crucial issue when, as in this case, you have an encyclopedia where the alphabetical order is essential.

**Comment by zdavis** [comment]
What version of Manifold is this on? v4.x or v5?

**Comment by zdavis** [comment]
(possible duplicate of #2636)

**Comment by Cutuchiqueno** [comment]
yes, I indeed stepped over this one when I searched for similar bugs, sorry. ( and yes, still on 4.1)

**Comment by zdavis** [comment]
No worries. Appreciate the report!
