### ISSUE TITLE
Default resource thumbnails fail to render

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2774]
On the Minnesota instance, resource annotation thumbnails are showing the broken image icon, instead of the appropriate default Manifold resource icon, for resources that aren't images or videos or have a set thumbnail. Scrolling through [this text](https://manifold.umn.edu/read/untitled-a5533014-27c2-48fd-a0fb-498976cbe4da/section/f0b7aa36-06d6-4566-86da-4728c360ef75) shows this behavior:

![resource](https://user-images.githubusercontent.com/25825222/83905019-89294300-a726-11ea-8a31-995ad69146a5.png)

This from another text section:

![resource](https://user-images.githubusercontent.com/25825222/83905070-a6f6a800-a726-11ea-8383-7c6d2a067ef2.gif)

**Comment by tsmyre** [comment]
I just created a new text to on the Minnesota instance, and this bug seems to still be in play. Reopening with a link to the project this is currently affecting.

https://manifold.umn.edu/read/07bde896-eeb4-45f4-942d-d227946fe12b/section/fa60a515-60ee-4a4a-977c-e5ef368f1bb1

**Comment by zdavis** [comment]
Investigated this—fix is fine, just hasn't been released to MN yet. Closing again.
