### ISSUE TITLE
Pagination regression on project collections list page

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2818]
See https://manifold.umn.edu/projects/project-collections

<img width="987" alt="Screen Shot 2020-08-14 at 4 30 06 PM" src="https://user-images.githubusercontent.com/255909/90299607-85631c80-de4b-11ea-910d-24c6269a9696.png">

**Comment by tsmyre** [comment]
I believe this may be related: projects in collections don't entirely fill out the available grid space before paginating. Here we see nine projects. On the second page there are an additional five.

<img width="1678" alt="pagination" src="https://user-images.githubusercontent.com/25825222/92526004-66596f80-f1ea-11ea-914f-283aa6c6ab4b.png">

**Comment by zdavis** [comment]
Will be fixed in next v5 release
