### ISSUE TITLE
CrossRef DOI integration

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#282]
DOIs

We store the following DOIs in Manifold:

1. Project Landing Page => Dataset
2. Project All Resources Page => Dataset
3. Resource => Component
4. Text Landing Page => Book (published text) or Posted Content (provisional)
5. TextSection => Article

UMNP will likely not assign DOIs to TextSections, provisional texts, and individual resources, but other texts may.

#1 and #2 will be assigned when the project is created

Other DOIs will be manually triggered by backend users. For example, when a text is ingested, the backend might prompt the user as to whether or not she wants a DOI to be created.

Manifold will need a mechanism to synchronize its DOI locations with CrossRef.

Assigning/saving DOIs will need to be an idempotent process that can be run multiple times.

Build this as a service with an adapter that is cross-ref specific in case someone in the future wants to integrate with another vendor.

Terence will give me sample DOIs for each object so I know how to structure them.
Zach will produce sample XML for each request and share it with the CrossRef representative before proceeding with development.

**Comment by zdavis** [comment]
We may need design from Lael for places where we show DOIs on the frontend:

1. On the project detail view (no design needed; will fit into metadata block)
2. On the project resources view (in lt. gray, very backgroundy, above back link near footer)
3. On each project collection view (same as project resources)
4. On texts (in some cases, likely only on the publication text, put it on the content page)

**Comment by tsmyre** [comment]
@zdavis Following our call today, here are the relevant display considerations for our DOI integration, which is no longer an automated process but a manual one to be performed by publishers in the means that most makes sense to them:

[Display as a link](https://www.crossref.org/display-guidelines/#full)
[Where to display](https://www.crossref.org/display-guidelines/#apply) — this may require more discussion.

**Comment by SMaxOwok** [comment]
![project_detail](https://user-images.githubusercontent.com/8389445/38214859-c9d729c2-367a-11e8-9d66-a6daf47aebf2.png)
![project_resources](https://user-images.githubusercontent.com/8389445/38214860-c9ea2c34-367a-11e8-8e20-580d91b8a438.png)
![resource](https://user-images.githubusercontent.com/8389445/38214861-ca011df4-367a-11e8-8b54-50924dccb57b.png)
![text_about](https://user-images.githubusercontent.com/8389445/38214862-ca159356-367a-11e8-8f78-52d784893376.png)

**Comment by SMaxOwok** [comment]
I'm not totally sure on if the `DOI` label should always be there, never be there, or be there when part of the metadata list. 

Let me know what you're thinking for placement with these after seeing the above.  Should DOIs be separate from the metadata list?

**Comment by zdavis** [comment]
@tsmyre @susanmpls curious what you two think.

**Comment by susanmpls** [comment]
I'm inclined to only have the DOI label show when one has been assigned.

**Comment by tsmyre** [comment]
I agree with that and also that DOIs should be part of the metadata list. That way they'll show in all the same places, and also they'd be scrapped into the citation builder, correct?
