### ISSUE TITLE
Private RG comments generate 403 error

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2832]
When an access-restricted project has public annotations/comments toggled off, readers annotating that project in the context of a private reading group that has been granted an entitlement to that project can annotate passages but not respond to those annotations with a comment.

This issue was first reported on the DDH instance and is replicated on [this Edge project](https://edge.manifoldapp.org/projects/dracula). Invite code to RG has been sent via DM in Slack.

**Comment by zdavis** [comment]
Fixed in 8f47a5c
