### ISSUE TITLE
Project collections remain accessible after visibility toggled off

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2835]
[This project collection](https://manifold.umn.edu/projects/project-collection/racial-justice) on the Minnesota instance has `Visibility` and `Show on Homepage` both toggled off. However, the collection page is still available to access if the URL is known.

From our Slack chat around this, the expectation for a collection in this state to only be visible in this way to admins. For everyone else it could either return an error message or redirect to the instance home page or project collections page. The latter two seem preferable.

**Comment by zdavis** [comment]
@bot bug
