### ISSUE TITLE
Include Publication Date metadata at export

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2836]
When a project is exported for preservation, the publication date is not currently included. It would be useful to include that information for the project and each individual text.

**Comment by zdavis** [comment]
Assigning to @scryptmouse. I've started working on this in zd/2836, but keep hitting a wall. Fundamentally, no matter what I do, I can't seem to get Manifold to render a new metadata.json file for a project's child text. I've tried modifying and saving the project. I've tried modifying and saving the project's text. I've tried changing force_new_export to default to true in the interactions. I've deleted all the project exports, and no matter what I do, I can't get the publication date to show up in the text's metadata.json in the project bag.

I'm sure I'm missing something obvious, but I'm going in circles and need another set of eyes here. Thanks!
