### ISSUE TITLE
Add navigation back to members page of reading group dashboard from view of individual member's annotations

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#2839]
## Feature Description

When I am viewing a particular group member's annotations through the reading group dashboard, I would like to be able to easily navigate back to the members page that lists all of the members in the group. Currently, when a user is viewing the list of a particular group member's annotations, there is a "manage reading groups" button in the upper left-hand corner that brings you back to the main reading groups home page that lists all of the reading groups you have created. Instead or in addition, I would like to have a navigation mechanist that would allow me to go back to the members page of the reading group I'm currently working in.

## *Why* is this feature important? *Who* does it help?

Creating an easy way to toggle between the member list in a reading group and a particular member's annotations will benefit instructors who are grading an annotation assignment, an editor who is reading through each reviewer's comments, anyone who has created a reading group and wants to go through a number of particular readers' annotations. 

## User Stories

i am an instructor and I am going through the members list to assign grades on an annotation assignment. I would like an easy way to toggle between an individual student's annotations and the list of members in the group so I can move on to the next student.

**Comment by zdavis** [comment]
Clicking on the reading group badge to the right of the annotation doesn't give you what you need here?

**Comment by krosemichael** [comment]
I'm not sure what you mean by the reading group badge to the right of the annotation. I realized I can get back to the screen I wanted by scrolling back to the top and clicking on "See all members." What was confusing me is that "manage reading groups" is sticky in the upper left-hand corner as you scroll through the page and looks like a "back" button because of the arrow, so I expected it to take me back to the last screen I was on, which was the "See all members screen," but it actually takes you back to the page that lists all of your reading groups. You have to scroll back up to the top of the page to see the "see all members" button. 

![image](https://user-images.githubusercontent.com/46459975/95650123-739aa000-0aaf-11eb-90d0-9cead9077e70.png)

I think we may want to revisit the design of the "manage reading groups" button, and/ or the question of which calls to action are sticky at the top of the page - maybe all three - "manage reading groups," "see all members," and "edit group" should be in that top bar. Since I realized there is a way to move the way I wanted, though, I'd say it's fine to close this request.

**Comment by mkgold** [comment]
FWIW, I don't find the "Manage All Reading Groups" button confusing (I would expect it to lead back to a page that lists all reading groups), but the question of what should be sticky at the top is interesting

**Comment by zdavis** [comment]
The manage all reading groups button is more like a breadcrumb navigation
than a back button. We use this same convention throughout the application,
and changing the behavior of this button to be a back button would entail
changing behavior elsewhere so that behaviors (and code) are consistent. If
what you want to do is go back, why not use the browser back button? If
that doesn’t work because there wasn’t a URL change, we could address that.

**Comment by krosemichael** [comment]
Yeah, fair. The "see all members" button also works. Not sure if it'll cause confusion if I go ahead and close this, but I'm happy for it to be closed.

**Comment by zdavis** [comment]
Thanks, Krysia. I'm going to go ahead and close this—we can always re-open if we decider we want to take some action here.
