### ISSUE TITLE
Theme color regression

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2875]
On Edge, I am able to adjust the `Accent Color` field, but I cannot adjust the default for `Header Foreground Color`, `Header Foreground Active Color`, or `Header Background Color`.

The app lets me save new values into those fields but it does not render them.

**Comment by zdavis** [comment]
This no longer appears to be an issue. Confirmed that I'm able to make these changes in Master:

![image](https://user-images.githubusercontent.com/255909/113951168-e028fa00-97c7-11eb-85f0-ad4caf1b330d.png)
