### ISSUE TITLE
Changes to resource block

### ISSUE THREAD

**Issue by konecnymark** [ManifoldScholar/manifold#2882]
## Problem: At present there is only one kind of button label for the resource block. This is often not sufficient to guide the user to explore what the specific type of resource is available.

**Comment by zdavis** [comment]
Just to clarify this request, the user would like a few changes to the Resources content block:
- Make it possible to set the title of the content block, similar to what we do on the text list content block.
- Make it possible to include a textual description above the resource grid, also similar to what's possible with texts.

Alexa, perhaps you could setup the BE interfaces for this and render the content on the FE, and if necessary, Dana can give it a quick style pass.

**Comment by konecnymark** [comment]
Thanks for looking at this and we look forward to seeing the prototype
