### ISSUE TITLE
Bad breaks in the Reader

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2913]
With recent updates I've been noticing bad line breaks and spacing more and more. I suspect that is on account of my regularly shifting the parameters of the Reader (shrinking the font, expanding and collapsing the margins).

At first I thought this had to do with our texts commonly being justified:

<img width="1030" alt="justify" src="https://user-images.githubusercontent.com/25825222/102815158-8a078680-4391-11eb-98af-ac1179e59397.png">

In response I added a stylesheet that left-aligned the affected content. But this turned up something more. You can see in these two shots that the text is now left-aligned but lines are breaking curiously. Each of these show one single paragraph:

**Example 1**
<img width="796" alt="bad" src="https://user-images.githubusercontent.com/25825222/102815375-df439800-4391-11eb-9eb5-58857fce9def.png">

**Example 2**
<img width="795" alt="break" src="https://user-images.githubusercontent.com/25825222/102815379-e2d71f00-4391-11eb-8c96-14dd50391eba.png">

This Text lives [here](https://manifold.umn.edu/read/metagaming/section/00d65eb7-926c-4159-9d95-5fee5285e7b8#ch01). As you changing the settings in the Reader (text size and margins) you'll start to see how the breaks occur within paragraphs render.

We started talking through this on Slack, where Zach reported that disabling the following global declaration in our CSS resets seems to mitigate some problems:

```css
*, *::before, *::after {
  box-sizing: border-box;
}
```

**Comment by tsmyre** [comment]
Another example from a [recently loaded text](https://manifold.umn.edu/read/critical-refugee-studies/section/21cc6956-947d-4127-8aa8-a22974331ad1).

<img width="918" alt="bio" src="https://user-images.githubusercontent.com/25825222/103238071-30fa9e00-490f-11eb-9c26-f1a0007cc2d2.png">

This is the coding for this paragraph:

```html
<p class="aubiof"><span class="aubion">Ma Vang</span> is an assistant professor and founding chair of Critical Race and Ethnic Studies at the University of California, Merced. Her forthcoming book, <i>History on the Run: Secrecy, Fugitivity, and Hmong Refugee Epistemologies</i>, examines how secrecy structures both official knowledge and refugee epistemologies about militarism and forced migration. She is the coeditor of <i>Claiming Place: On the Agency of Hmong Women</i> (University of Minnesota Press, 2016), and her writings have been published in <i>positions: asia critique</i> and <i>MELUS</i>. With a UC Multicampus Research grant, she is a founding member of the Critical Refugee Studies Collective, which aims to ethically reconceptualize refugee lifeworlds to make apparent processes of colonization, war, and displacement. She serves as coeditor of its website, which hosts the refugee archive and story map platforms for refugees to share stories. She is also actively engaged with student and community organizations.</p>
```

**Comment by tsmyre** [comment]
This is also being reported on the [UMass instance](http://umpressopen.library.umass.edu/read/coaching/section/1e2ead3f-1cc2-47fa-a2d5-cfb20c5c5226).

Here we see one single paragraph that breaks at the resource annotation.

<img width="742" alt="umass" src="https://user-images.githubusercontent.com/25825222/104051091-2fea2c00-51ad-11eb-89b6-09531447fc80.png">

**Comment by zdavis** [comment]
Hey @dananjohnson, could you pause on the OER work at some point in the next day or two to look at this issue and let me know what you think? I'd like to address this for v6 if it's not too much work.

**Comment by zdavis** [comment]
Hey @tsmyre — Dana and I are no longer able to reproduce this problem. When you have a chance, could you check and see if you're able to reproduce these issues?

**Comment by tsmyre** [comment]
Likewise, I'm not longer seeing this either. Is this something that could have been happening because of something going on in Chrome?

**Comment by zdavis** [comment]
Could be a browser issues that was fixed, or a manifold issue that we fixed without knowing it. I'm closing this and we can reopen if it pops up again.
