### ISSUE TITLE
Gather Flagged Annotations in a Central Place for Viewing by All Associated with a Project

### ISSUE THREAD

**Issue by vkern** [ManifoldScholar/manifold#2924]
### Feature Description

Notifications for flagged annotations are currently only viewable by a Manifold administrator and a project creator. It would be useful for others who contribute to projects (those in Reader roles) to be able to view these flags and help determine a responsive course of action.

### Why is this feature important? Who does it help?

This feature would share the work load of monitoring flagged annotations. It would also allow project contributors (those Readers added to a project) to monitor flagged annotations on their work by tracking flagged annotations on a centralized list.

### User Stories

The UW Libraries is working with our Center for Teaching and Learning (CTL) to host a conference on Manifold. The conference is administered by several within the CTL. An online conference, the bulk of the conference activity will take place through annotation dialogue between attendees and presenters. Conference administrators would like to take turns monitoring any flagged annotations throughout the conference.

**Comment by mkgold** [comment]
Thank you for submitting this ticket, @vkern ! This feature would be very useful on the CUNY instance, as well.

@zdavis I note that there are some flag-related issues in ticket as well https://github.com/ManifoldScholar/manifold/issues/2829 , including suggestions for adding options to provide details on the reason the annotation is being flagged.

**Comment by zdavis** [comment]
Closing this. Going forward, we'll track improvements to flagging in #2982. I'm going to update that list to include specific's from @vkern's request here.
