### ISSUE TITLE
Backend project nav clips on smaller screens

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#293]
![screen shot 2017-04-25 at 2 04 17 pm](https://cloud.githubusercontent.com/assets/8389445/25409349/628ece44-29c6-11e7-804c-3c0411b99f9b.png)

**Comment by naomiyaki** [comment]
Got it! If it isn't already I'll make sure this is scrollable. On non-touch displays, should we have arrows that scroll the element?

**Comment by zdavis** [comment]
Hmm... I guess? Generally speaking, do we want to support mobile sized screens that don't have touch enabled?
