### ISSUE TITLE
Support math display in LateX

### ISSUE THREAD

**Issue by fyemath** [ManifoldScholar/manifold#2931]
In STEM subjects, users often need to write math expression. Can you make Manifold support LaTeX math display? It would be good if manifold will support [MathJax](https://github.com/mathjax/MathJax) or at least [KaTeX](https://github.com/KaTeX/KaTeX). Thank you!

**Comment by tsmyre** [comment]
@fyemath I'm closing this issue since it duplicates an existing ticket. We'll continue to track our work around this in #1354.
