### ISSUE TITLE
Feature Request: Mastodon / decentralized platforms

### ISSUE THREAD

**Issue by Pixouls** [ManifoldScholar/manifold#2941]
Current social media integrations are focused on big social media platforms, would be interested to see a Mastodon integration, considering the amount of F(L)OSS developers engaged on that platform. I am a student but I don't have a social media platform to connect with, wouldn't want that associated with my studies, and don't like the adware experience associated with them — so having integration to decentralized and federated feeds would be nice.

**Comment by zdavis** [comment]
Thanks for taking the time to open an issue! I'm not sure that this is in our current vision for the platform—we certainly don't have funding for it. However, if you'd like to share more on exactly what this integration would look like, we're all ears. Currently we mostly use social platforms as identity providers (with the exception of pulling tweets that match a query into projects), so I'm not sure how we'd leverage a decentralized platform in this way. Happy to hear suggestions, but I think we'd need a more detailed vision for what this integration could look like for this to be actionable for us. 

I'm going to close this for now, as it's not currently actionable, but please feel free to continue discussing and we can see if others in the community are interested in this as well.
