### ISSUE TITLE
Review a11y of reader search text excerpts accordion

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2966]
The button at the bottom of the first search result opens an accordion that shows all excerpts for the search result. Please check to make sure we have a valid implementation of the accordion pattern from an a11y standpoint. Thanks!

![image](https://user-images.githubusercontent.com/255909/113950572-85db6980-97c6-11eb-9458-7fcd0d68d349.png)

See #2756 for background and what's driving this request.

**Comment by tsangaaron09** [comment]
Mikey and I took a look at the accordion example mentioned above. Our feedback is that focus indicator(screen reader on or not) is able to focus on all results, even the ones that are not supposed to be hidden by the accordion. In your example screenshot, even if the accordion is collapsed, keyboard navigation is still able to focus on the 4th and 5th excerpt. Additionally, with the "Show All Excerpts" button, we are experiencing no feedback from NVDA when it is selected to expand or collapse. We would recommend adding an announcement of "expanded" or "collapsed" upon focus of the button as well as the activation of the button which can be implemented using the "aria-expanded" property.

Optionally, it is a common design pattern to only allow one accordion to be expanded at once to reduce clutter. So, expanding one accordion of results would collapse the previously expanded accordion. Given the structure of the page and relationships of the search results, this may or may not be applicable. We would be more than happy to discuss this further and get your thoughts on this! 

For reference, this is the design pattern for accordions according to W3: https://www.w3.org/TR/wai-aria-practices-1.1/#accordion

**Comment by zdavis** [comment]
I don't think that chaining these accordions is necessary/correct because they are not part of a single list. If, for example, we had a list of FAQs, and each could be opened or closed, then I might be inclined to allow only one to have an open state at a time. In this case, the user is encouraged to go deeper and expand results that are not connected to each other. In that case, I don't think it would be successful UX to make the decision to close a list on the user's behalf.

We're familiar with this (and other) aria patterns. When Dana has bandwidth, he will update the implementation to better conform to the pattern. Thanks for the feedback here.

**Comment by tsangaaron09** [comment]
Sounds good! That was along the lines of what we were thinking as well. Please let us know if there is anything else we can help with. We would be glad to retest this issue after it is updated.

**Comment by zdavis** [comment]
Resolved in #3082
