### ISSUE TITLE
Alphabetize project subjects

### ISSUE THREAD

**Issue by robin-miller** [ManifoldScholar/manifold#2984]
In the backend, there is currently no way to organize/alphabetize Project Subjects. It would be great to have drag bars so that you could reorder Project Subjects after they are entered into Manifold.

**Comment by zdavis** [comment]
Thanks, Robin. Do these subjects really need to be manually sorted? We can easily alphabetize them, if that goal is to just get some sane sorting in place. We could allow manual positioning, but it's more complex and takes more time, so I'd prefer not to do it unless there's real demand for it.

ZD

**Comment by robin-miller** [comment]
Alphabetizing these would be perfect. Thanks, Zach!

**Comment by zdavis** [comment]
Retitled issue
