### ISSUE TITLE
Add contrast in mobile views for menu listings using light active colors

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2994]
The team at Union reported that when they style their header with a dark color and adjust the Header Foreground color to white, they don't show with enough contrast in mobile views. Would a new mobile theme field be a useful approach here or would having the system automatically account for lighter colors be easier? Or perhaps something else altogether?

<img width="1166" alt="header" src="https://user-images.githubusercontent.com/25825222/116275335-27603600-a749-11eb-9061-4eae1532b604.png">

_Example Header ↑_

<img width="371" alt="theme" src="https://user-images.githubusercontent.com/25825222/116275236-0c8dc180-a749-11eb-8b34-300c2378da1f.png">

_Mobile Menu ↑_

**Comment by zdavis** [comment]
This'll be fixed in v7. These settings:

![image](https://user-images.githubusercontent.com/255909/122137678-0e473d80-cdfa-11eb-8e3a-e6ac926d7911.png)

Will look like this:

![Uploading image.png…]()
