### ISSUE TITLE
Component FetchData methods should not be triggered by URL hash changes

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#304]
https://github.com/ManifoldScholar/manifold/blob/master/client/src/components/global/HigherOrder/ResolveDataDependencies.js#L28

This line causes components to call their `fetchData` methods when a hash is added to the URL.  In some cases, this causes conflicting requests during an update.

Slack Discussion:
https://manifold-scholarship.slack.com/archives/C0BCDM82H/p1493399926648943

**Comment by zdavis** [comment]
FetchData is being completely rewritten as part of the react-router v4 upgrade.
