### ISSUE TITLE
Style (and improve) forgot password email

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#306]

**Comment by zdavis** [comment]
The basic idea here is to improve the aesthetic of emails sent from Manifold. I'm assigning this to LT for now, because the first step is getting global email design in place. I believe I provided details on this in the last design brief that I gave to LT.

**Comment by laelito** [comment]
A PDF showing design for a basic Manifold email styling template is attached with views for desktop and mobile. The source file is available on the shared internal Dropbox.

[Manifold_UI_Email_Template_v1.1.pdf](https://github.com/ManifoldScholar/manifold/files/1620068/Manifold_UI_Email_Template_v1.1.pdf)
