### ISSUE TITLE
Request: two fields for collection descriptions

### ISSUE THREAD

**Issue by BethFuget** [ManifoldScholar/manifold#3069]
Have you considered creating two fields for collection descriptions, so that we can include a short description of a collection on our homepage and a longer description on the collection page itself? This would make it possible to provide full details about a collection, including series editors, funding sources, etc., on the collection page without cluttering up our homepage.

An alternate approach would be to add a toggle so that we can choose whether or not to show the description on the homepage. If "on," the description would show on both pages; if "off," only on the collection page, while the homepage would have the collection title alone.

I'd prefer option 1 for more flexibility but option 2 would also serve our main interest, which is focusing attention on our growing set of collections and the publications themselves rather than on info about each collection.

Thanks for considering!

**Comment by zdavis** [comment]
@1aurend This would be a great first feature, I think, for you to tackle the API side of development.

**Comment by zdavis** [comment]
@bot feature

**Comment by 1aurend** [comment]
Just realized I never replied to this. Sorry! I'm making a Linear issue for myself now.

**Comment by zdavis** [comment]
This has been implemented and will be in the next major release of Manifold.

**Comment by BethFuget** [comment]
I'm delighted to hear it! Thanks so much.
