### ISSUE TITLE
Error 503: API TypeError

### ISSUE THREAD

**Issue by insprecta-beck** [ManifoldScholar/manifold#3071]
Are Manifold's servers under maintenance currently?? Specifically the web servers??

503: API TypeErrors keep popping up for certain link resources on a Manifold project we have. This is one of the links in question: https://www.facebook.com/weareohio/videos/538212456347/

Could this error be due to Firewall configurations??
I will check our sites code for bugs, but so far it seems that this is most likely a server side issue.

**Comment by zdavis** [comment]
Investigated, not an problem with Manifold.

**Comment by insprecta-beck** [comment]
We're trying to create and upload the same resources to see if the error
continues.

The error is inconsistent across similar resources. I understand that using
a browser with any extensions installed will trigger the error warning.
The error does not occur clicking on the resource using browsers without
extensions.

I think it's a bug that operates somewhere within the browser / application
layer.

Thanks for your help.
