### ISSUE TITLE
Broken footnote links

### ISSUE THREAD

**Issue by quantummcguinn** [ManifoldScholar/manifold#3076]
Hi there. Got a broken footnote link and can't solve. I ingested HTML which had been exported from InDesign. Everything good apart from: in preview mode, clicking on the footnote (both marker and number) generates "404 Error: API Not Found".

Marker code goes like this:
<span class="CharOverride-2"><span id="footnote-000-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="Hughes&amp;McCutcheon_Religion_in_5_Minutes_Ch19.html#footnote-000">1</a></span></span>

Note code goes like this:
<p class="Footnote-tab"><a class="_idFootnoteAnchor _idGenColorInherit" href="Hughes&amp;McCutcheon_Religion_in_5_Minutes_Ch19.html#footnote-000-backlink">1</a>&#9;Retrieved on February 27, 2017 from <a href="http://www.businessinsider.com/map-shows-how-religion-spread-around-the-world-2015-6"><span class="Hyperlink">www.businessinsider.com/map-shows-how-religion-spread-around-the-world-2015-6</span></a>.</p>

I admit that I'm not really a coder so it may well be obvious to everyone else. Help appreciated. TIA

(Because my pasted HTML will probably render, I'm attaching screenshots of the HTML as well.)
<img width="659" alt="Screenshot 2021-09-08 at 21 05 38" src="https://user-images.githubusercontent.com/90352088/132577971-72edd3ed-487f-41ac-b839-e94a8212c508.png">
<img width="661" alt="Screenshot 2021-09-08 at 21 05 49" src="https://user-images.githubusercontent.com/90352088/132577983-7e943c0b-84ee-4dc4-a866-f07ef6570672.png">

**Comment by tsmyre** [comment]
Closed with #3078
