### ISSUE TITLE
Viewing options not working correctly for highlights/annotations

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#3090]
Process: I go to the DH Debates instance and I'm writing a text -- https://dhdebates.gc.cuny.edu/read/untitled-88c11800-9446-469b-a3be-3fdb36bfbd1e/section/c733786e-5787-454e-8f12-e1b7a85cac72#ch05 . I'm logged in on this instance from a previous session

I go to the view options and unclick "others" for highlights and annotations. Those disappear

When I change "reading group" to the one I want to use (a private group), my own highlights disappear, even though I made the highlights previously with that group selected. The act of clicking the box next to the group name makes them disappear

this happens for both annotations and highlights. if "show all" is clicked in the viewing options, I can see the highlights comments, but if I click the group name in which they highlights/annotations were made, they disappear

**Comment by zdavis** [comment]
Matt, is this a duplicate of https://github.com/ManifoldScholar/manifold/issues/3028, perhaps? If so, that was fixed in v6. DH Debates still needs to be updated to v6 (can do tomorrow!)

**Comment by mkgold** [comment]
oops -- yes, looks like it is a duplicate. sorry! and thanks for the update!
