### ISSUE TITLE
Investigate why Manifold can't ingest this google doc

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#311]
I confirmed that ingestion failed in my local env for this doc:

https://docs.google.com/document/d/1Um3kLNU-jhYbYbXz6ViYpJVrFV_Qxg9zHqN6Ti_yyPY/edit

**Comment by SMaxOwok** [comment]
This Google Doc was getting exported with UTF-8 encoding, but contained invalid characters in the styles.  The fix in the PR referenced replaces any characters that don't match UTF-8 when we attempt to ingest the file.

Original error message:
`"\XE2" FROM ASCII-8BIT TO UTF-8`
