### ISSUE TITLE
Make Manifold Logo a link to frontend in admin mode

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#3110]
When one is in admin mode and wants to exit out of it, one currently has to find the "exit admin mode." That's fine if one knows where it is, but I think it would make sense that clicking on the Manifold logo in the header nav woul dalso  would also take one to the frontend.

Currently, we have the Manifold logo and then the word dashboard in the header nav, both of which take the user to the dashboard home. Making the change I suggest above would be more intuitive, I think, and would also reduce the duplicate function of these two links as they currently appear.

**Comment by zdavis** [comment]
@tsmyre do you agree with what Matt's requesting here?

**Comment by tsmyre** [comment]
@zdavis I don't. I understand the request, but I think as many folks who would think clicking that will get them out of the backend will be about the same number of folks who will be surprised that by clicking it they were knocked out of the backend.

The icon on the frontend returns you to the landing page of the instance. It seems right to me that it works in parallel in the backend, taking you to the landing page of the backend. In the same vein, you don't click on the Manifold icon in the frontend to get to the backend. So I would be more inclined to leave it as it is.

**Comment by zdavis** [comment]
I share Terence’s view. Matt, how strongly do you feel about this request?

**Comment by zdavis** [comment]
@mkgold I'm closing this, as I don't think there's consensus for this change. Happy to discuss further in one of our meetings and reopen in the future.
