### ISSUE TITLE
Scope BE dashboard projects to current user's writable projects

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#3271]
When I grant a user (reader, project creator) access to a project they wouldn’t otherwise be able to edit, when that user jumps into the backend they see on the dashboard a larger list of projects than that they can actually access (the BE project list returns the correct results).

E.g., I give a reader (let’s call this person Fang Face) access to edit the project Dracula on Edge. When Fang Face logs in and clicks on the `Editor Mode` button to access the backend they can see 72 projects, even though they only have credentials to access the one project, Dracula. If they click on any project other than Dracula, they get an access denied error, as expected, but previously they would only be able to see just those projects they can actually affect.

**Comment by zdavis** [comment]
This has been fixed.
