### ISSUE TITLE
Unexpected access to journals in draft mode

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#3273]
I log in as a Project Creator and can see all the journals listings, whether they are in draft mode or not. As I click on the listings, those that aren’t in draft mode return an access restricted warning. But those that are still in draft allow me to edit them, when they should not.

**Comment by zdavis** [comment]
I believe this was resolved in https://github.com/ManifoldScholar/manifold/pull/3312, and I did a quick test in my local environment to confirm. That said, please feel free to test on edge again and make sure it's fully resolved.
