### ISSUE TITLE
Adjust warning language around deleting journal issues

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#3280]
When a user moves to delete a journal issue they are confronted with this warning:

> Are you sure you want to delete this issue?
>
> This action cannot be undone.

Some users may believe they are _only_ deleting the issue record and not the associated Manifold Project. We should make that clear in the warning by adjusting the language to this:

> Are you sure you want to delete this issue? Deleting the issue will also delete the associated project.
>
> This action cannot be undone.

**Comment by zdavis** [comment]
The issue edit view where you saw this is no longer used. As of today, the issue properties are merged into the project properties. The only way the user can delete the issue now is to delete the project. I'm closing this since it's no longer actionable.
