### ISSUE TITLE
v7-alpha doesn't promote published Features to the HP

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#3320]
When a Feature is toggled to `Published`, it does not appear as expected on the Manifold HP in v7-alpha.

See the Apparatus instance:

- Feature: `https://apparatuspress.manifoldapp.org/backend/records/features`
- Homepage: `https://apparatuspress.manifoldapp.org`

**Comment by zdavis** [comment]
Thanks, Terence. We'll look into it.

**Comment by zdavis** [comment]
WDP-336 in Linear
