### ISSUE TITLE
Project images are converted to jpegs, don't allow transparent backgrounds

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#335]
![screen shot 2017-05-10 at 11 55 02 am](https://cloud.githubusercontent.com/assets/8389445/25915878/b0e3987e-3577-11e7-9c1f-9d1a53260b64.png)

**Comment by zdavis** [comment]
This is happening because the :format is hardcoded in the BASE_STYLES constant in attachments.rb. We could change all the small versions to png, I think — or we could explore whether it's possible to have the format simply be jpg if the input is jpg, png if the input is png, etc.

**Comment by SMaxOwok** [comment]
I started looking into this and found that we'll also need to include `-background none` at the start of the conversion.

**Comment by SMaxOwok** [comment]
It also seems like somewhere along the line the `manifold_attachment_pdf_styles` are being overridden.
