### ISSUE TITLE
Built-in Text-to-Speech for Accessibility

### ISSUE THREAD

**Issue by jeffwgallant** [ManifoldScholar/manifold#3422]
We've received a question from one of our Manifold superusers - would it be possible to add a built-in text-to-speech screen reader in Manifold alongside the other accessibility options such as the font/dark mode options?

**Comment by zdavis** [comment]
This isn't something we'd build as part of Manifold. It would be complex, if not impossible, to do well, and this function is already handled by screen reader applications.

**Comment by jeffwgallant** [comment]
Thanks! I'll relay the info to them.
