### ISSUE TITLE
Official VPAT for Manifold

### ISSUE THREAD

**Issue by jeffwgallant** [ManifoldScholar/manifold#3423]
Some colleges have a strict online accessibility policy that there needs to be a VPAT in order to use or link to _anything_ in their learning management systems. Even though Manifold aims for WCAG AA and has an accessibility page I can link people to, a VPAT would fulfill this adoption-critical requirement much better.

**Comment by zdavis** [comment]
Closing this issue as it's not a development task per se. That said, the team is aware of demand for a VPAT, and it has been discussed many times. I've made sure the rest of the Manifold team is aware of your request, and we'll keep it in mind as we continue to talk through whether or not to devote time and money to creating a VPAT.
