### ISSUE TITLE
Social improvements, page titles, and open graph tags

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#345]

**Comment by zdavis** [comment]
The goal of this story is to generally improve the ease with which users can share Manifold on social media. I'm primarily concerned about the following types of shared content:

1. Projects
2. Texts and text sections
3. Resource collections
4. Resources
5. Not tied to a specific project, but rather to the Manifold instance itself (such as the /featured page)

The image and text that's shared should be relevant to whichever type of entity the shared URL falls under. I recommend you utilize FB's sharing helper to assist in this effort (https://developers.facebook.com/tools/debug/sharing). To get that to work, we may need to setup some port forwarding on our router to your development environment — that might be a pain, but I can help with it. It will be less of a pain than guessing and repeatedly deploying to see how the tags look on FB.

Ideally, the page titles and meta tags would be set in the container components, near the top of their render methods.

One approach here is to roll our own using react-side-effect, which is what we're currently using to set body classes (see https://github.com/gaearon/react-side-effect). Another approach would be to use an established library like Helmet (https://github.com/nfl/react-helmet). I'd recommend you start out by looking at Helmet and see how it goes. 

Keep in mind that these meta tags and the title tag will need to be rendered in the client, and on the server-side render. Look at the <Html> component in client/helpers/Html.js. This is where the <head> content is rendered during the server-side render. It looks like this is currently using a library called react-document-meta to render meta tags from config.js. That library is discontinued and refers users to Helmet, so that's another argument for moving in that direction.

Note that this is for v0.3.0. Until v0.2.0 is released, this PR should be for a v0.3.x branch, which we can create. Once v0.2.0 is out, the PR can be against master.

**Comment by SMaxOwok** [comment]
Note to remove the nginx config on the proxy when this feature is completed

**Comment by SMaxOwok** [comment]
This got merged in.
