### ISSUE TITLE
Scrolling issue on visibility drawer

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#3487]
When I am on the DDH Manifold instance, I find that if I am looking at a text as a logged in viewer and try to hit the viewing options modal drawer (the eye icon), the drawer opens, but I'm unable to scroll down to see all of the options because the scroll focus is on the background text rather than the modal.

Please see attached screenshot and let me know whether you need any other info to replicate.

<img width="1464" alt="Screen Shot 2022-11-02 at 5 36 22 PM" src="https://user-images.githubusercontent.com/278503/199607313-726cb31c-a5e4-484a-9a20-83357b7ff2c2.png">

**Comment by tsmyre** [comment]
Just confirming that I can replicate this behavior on Brave.

**Comment by zdavis** [comment]
Fix will go out in next version.
