### ISSUE TITLE
Can only view first 20 Project Collections in the backend

### ISSUE THREAD

**Issue by Ian-BD** [ManifoldScholar/manifold#3489]
When viewing project collections in the Backend you are limited to the first 20 based on the sort order with no way to to paginate. these means there's no easy to view all Project collections once you have more than 20.

## Expected Behavior
Like the front end there should be options to click through pages to view all Project collections.

## Current Behavior
Only the first 20 Project collections are viewable.

## Possible Solution
The simplest solution seems to be adding pagination below the list.

## Steps to Reproduce

1. Access backend.
2. Create 21 Project collections.
3. Notice only 20 are viewable

## Context (Environment)
Our client is unable to add and modify project collections easily, my current workaround is for them to email me when they've added a new one and I can find a direct link by calling the Manifold API.

## Notes
I noticed this issue when looking at the API request in the Network tab of Firefox's Dev console, it appears that pagination is a feature of the API but there's no way to alter it.
![image](https://user-images.githubusercontent.com/89195159/200337670-14a5a759-1bc4-417e-8e74-b0e11a84cd41.png)

**Comment by zdavis** [comment]
Fixed in #3493
