### ISSUE TITLE
Use URL instead of # in href property of next/previous button a-links on Project Resources list page  

### ISSUE THREAD

**Issue by karenhanson** [ManifoldScholar/manifold#3532]
## Feature Description
This is an extension of this work, related to Mellon-funded research into platform preservability: https://github.com/ManifoldScholar/manifold/issues/2727.

`<a href=”#”` is still used on the next/previous/numbered links used to navigate resource lists (e.g. at the bottom of this page: https://manifold.umn.edu/projects/metagaming/resources). A generic web crawler would currently miss these links. Ideally the href property would contain the target URL instead of a "#".

## *Why* is this feature important? *Who* does it help?
Allows web crawlers to navigate content that would otherwise require a click. In our case, to support website archiving processes but may improve search engine discovery.

## User Stories
As a preservation archive, I would like to be able to take a complete snapshot of the Manifold content using an automatic web crawler. I would like the web crawler to be able to discover and visit all `<a>` links without requiring custom configuration to simulate on-click actions.

## Design Notes
Suggest using relative or full URL in the href.

## Development Notes
n/a

**Comment by zdavis** [comment]
MNFLD-569 in Linear

**Comment by 1aurend** [comment]
Fixed in #3627
