### ISSUE TITLE
Social icon labels are missing in footer when stand-alone mode is enabled

### ISSUE THREAD

**Issue by aupress** [ManifoldScholar/manifold#3567]
When syand-alone mode is enabled in Manifold Settings > Properties, social icons in the footer are missing labels.

![misisng social icon labels](https://user-images.githubusercontent.com/60119385/222514694-841ec1e0-7bfc-44a0-9d5e-c9a4f29f063a.png)

**Comment by 1aurend** [comment]
Fixed in #3585
