### ISSUE TITLE
Feature request: allow units in resource sizes

### ISSUE THREAD

**Issue by benmiller314** [ManifoldScholar/manifold#3590]
In the settings for interactive resources, there are fields to support an optional minimum height and minimum width. These fields, however, seem to only accept numbers, which are then converted to a fixed number of pixels. I discovered this when trying to use a viewport unit, because declaring an absolute minimum number of pixels is a recipe for awkward overflow on screen sizes smaller than the one on which we're preparing the document. (Indeed, setting a minimum rather than a maximum width also runs the risk of the resource overflowing the available space, preventing the iframe from responsively scaling for mobile devices or side-by-side browser windows.) 

I've confirmed that [iframes can take viewport units for their own widths and heights](https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts), though in that case width and height have to be set in the CSS rather than in the HTML itself. I hope this isn't too big of a barrier.

If the issue is instead more about the challenges of parsing input from the webform, would it be possible instead to add a pulldown menu on the form that allows us to specify units? This would also clarify to users that px is the default, if that's what you prefer.

Grateful for your consideration of this enhancement!

**Comment by 1aurend** [comment]
Resolved in #3636
