### ISSUE TITLE
Adding background image for the homepage v7.1

### ISSUE THREAD

**Issue by Pin-ZHU** [ManifoldScholar/manifold#3618]
After upgrade from the version 6.x to the new version 7.1, when uploading the background image for the Melusina Homepage, the image does not appear. It seems that the variable "bgImage" is not replaced by the image.
And we received the following error:
![image](https://github.com/ManifoldScholar/manifold/assets/104444638/a313b0d8-af46-40c0-a090-34fd79df0c89)

**Comment by 1aurend** [comment]
Fixed in #3627
