### ISSUE TITLE
Text titles are being incorrectly capitalized in text list and in events.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#372]
![screen shot 2017-06-02 at 8 41 54 am](https://cloud.githubusercontent.com/assets/255909/26733323/599c1ec4-476f-11e7-98fe-4fd03d136ef3.png)

**Comment by SMaxOwok** [comment]
@zdavis I'm not replicating this.  It seems like the text title comes directly from whatever was uploaded.  Unless you're aware of that and want me to be modifying the title to title case in all cases.  Let me know.

![screen shot 2017-06-07 at 10 13 45 am](https://user-images.githubusercontent.com/8389445/26891513-22b9f5a8-4b6a-11e7-855a-a7caa68ba854.png)

**Comment by zdavis** [comment]
I'm not convinced it's not a bug. Does the event title come from the associated text, or is it saved on the record. Get into the rails console on the Cornell staging site and see if you can figure out why the last event on this page (http://cornell.manifoldapp.org/project/602dba50-1055-4ea9-bbfd-6178ff20dbad/events) has incorrect capitalization. Perhaps the text was uploaded with the incorrect title, the event was created, then the text title was changed?

**Comment by SMaxOwok** [comment]
Closing per our discussion:
https://manifold-scholarship.slack.com/archives/C0BCDM82H/p1498588887990509
