### ISSUE TITLE
Link to resource detail from activity feed is incorrect and 404s

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#380]
![screen shot 2017-06-02 at 12 02 57 pm](https://cloud.githubusercontent.com/assets/255909/26740695/6eba9d78-478b-11e7-8e73-f273b6e70ca0.png)

**Comment by SMaxOwok** [comment]
Fixed in https://github.com/ManifoldScholar/manifold/commit/1fd2f4f94f9a1996e96473d0df54a49b31f1aa54
