### ISSUE TITLE
Viewing a resource in the reader resets the scroll position.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#381]

**Comment by SMaxOwok** [comment]
In progress branch: `feat/scroll-to-top`

**Comment by zdavis** [comment]
Max ran into an infinite loop issue on this — ball is in my court to take a look at the branch.

**Comment by SMaxOwok** [comment]
https://www.cuttlesoft.com/infinitely-dispatching-actions-react-redux-react-router-v4/

A little insight

**Comment by SMaxOwok** [comment]
I feel like I'm so close to cracking this...

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#render-func

**Comment by zdavis** [comment]
Either I fixed this at some point, or we incorporated a fix from Max. In any case, it no longer seems to be an issue.
