### ISSUE TITLE
Improve GDoc Ingestion Styles

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#388]
*	The `Title` and `Subtitle` headings are relegated to standard text, but other headings (`Heading 1`, etc.) retain their style. Possible to change title treatment back to retain their original style?
*	Table borders remain black when switched to the dark theme.
*	For paragraphs styled as numbered lists, the numbers don't pass from the GDoc to the platform, and the text remains black in the dark theme. Possible to retain the numbers?
*	Text that has been manually adjusted in font and size in the GDoc is standardized with the remaining running text, but when in dark mode—while it shows in white—it is backed by white, making the text invisible.
*	Using the ruler to modify indents is mirrored on Manifold with what is in the GDoc. This _seems_ like the best approach.
*	Document title does not appear in the menu bar.

**Comment by zdavis** [comment]
@SMaxOwok I'd like you to do some exploration and research on this issue. Make a public good doc that has formatted text as Terence describes above and include the link here. It'd be helpful to also see the HTML that Google generates so we can discuss how to address these problems. I'm also curious as to whether or not there are any ways to export google doc content besides the HTML export. It looked to me like there were lots of hard-coded, inline styles in there. I wonder if we might have more success with a rich text export transformed to HTML via PanDoc.

**Comment by zdavis** [comment]
Terence already has an example we can work from: https://docs.google.com/document/d/1bTY_5mtv0nIGUOLxvltqmwsrruqgVNgNoT2XJv1m5JQ/edit

**Comment by zdavis** [comment]
For future reference, when google docs exports the doc as HTML, the exported document does not support multiple columns. If Google's export doesn't support it, Manifold won't support it either.
