### ISSUE TITLE
GDoc Encoding Error

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#409]
Converting a file from Word to GDoc and then uploading that GDoc to Manifold can throw this error:

```
Processing failed: "\xE2" from ASCII-8BIT to UTF-8
```

The file in question can be found here: https://docs.google.com/document/d/1oq4WjoH2ix0XSZRolXIJnRWD0sv4V6PN_Zi-nVX0cXU/edit?usp=sharing

**Comment by SMaxOwok** [comment]
Regression from HTML refactor.  Original fix: https://github.com/ManifoldScholar/manifold/commit/39016b9e5a02aaf1d49922739a00052a4975b7ff
