### ISSUE TITLE
Manifold can ingest an EPUB from a URL.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#420]

**Comment by zdavis** [comment]
This should be relatively straight forward after my recent ingestion changes. Look at the google doc strategy for an example of fetching remote content prior to ingestion. I believe the fetching happens in the strategy itself now, rather than in an inspector.

We'll need to think about what the ingestion interface looks like in the backend, since we'll need to offer the user a choice between uploading and entering a URL in the backend. Take a stab at it and let's see where it goes.

**Comment by SMaxOwok** [comment]
https://standardebooks.org/ebooks/e-t-a-hoffmann/master-flea/george-soane/dist/e-t-a-hoffmann_master-flea.epub3
