### ISSUE TITLE
Frontend dropdown styles aren't right in Firefox.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#439]
![screen shot 2017-07-14 at 2 32 04 pm](https://user-images.githubusercontent.com/255909/28231634-521851ba-68a1-11e7-8b6f-ac3895b3cfe5.png)

**Comment by zdavis** [comment]
Opposite of double rainbow is double dropdown arrow.

**Comment by SMaxOwok** [comment]
Related / dupe of #432
