### ISSUE TITLE
Overlap on see more projects button

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#444]
![screen shot 2017-07-18 at 8 42 10 am](https://user-images.githubusercontent.com/8389445/28326258-20f9034e-6b95-11e7-8812-f05de4ab2c5e.png)

**Comment by SMaxOwok** [comment]
Looks like this is only an issue in #392, will fix there.

**Comment by zdavis** [comment]
@SMaxOwok this issue has a bit of a bad smell — first of all, I don't understand why it would only happen in that branch and not others. Second, it's not clear to me why this fix is necessary, unless there's some other change. Could you just double check and make sure it's only an issue in that branch? If that's indeed the case, then we don't need an issue for it — we should just address it in that PR.

**Comment by SMaxOwok** [comment]
It seems like this is an issue outside of that branch, I just hadn't nailed down the replicating behavior.  Additionally, I'll remove the commit in #392 because I don't think it actually fixes the issue.

To replicate:
1.  Go to /featured
2.  Reload page
3.  Button width should be incorrect
