### ISSUE TITLE
Ingestor spec is failing

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#465]
```     Failure/Error: def self.can_ingest?; end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./spec/services/ingestor/strategy_spec.rb:7:in `can_ingest?'
     # ./app/services/ingestor/strategy.rb:25:in `block in for'
     # ./app/services/ingestor/strategy.rb:24:in `each'
     # ./app/services/ingestor/strategy.rb:24:in `find'
     # ./app/services/ingestor/strategy.rb:24:in `for'
     # ./app/services/ingestor.rb:96:in `start'
     # ./app/services/ingestor.rb:62:in `determine_strategy'
     # ./spec/services/ingestor_spec.rb:74:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:79:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'```

**Comment by zdavis** [comment]
I'm not able to reproduce this. In master, `rspec -fd spec/services/ingestor/strategy_spec.rb` seems to be working for me.

**Comment by SMaxOwok** [comment]
Still replicating, about to investigate more.

Failing tests are from `/spec/services/ingestor_spec.rb`

**Comment by SMaxOwok** [comment]
I was replicating for a while and in the process of fixing when all tests started passing.  I can't replicate anymore, so I'm closing unless it pops up again.

**Comment by zdavis** [comment]
Now I'm seeing it... I'll follow up on this.

**Comment by zdavis** [comment]
I think this has to do with how we add and remove strategies. Stopping spring solves it. I believe I have a fix in mind.

**Comment by SMaxOwok** [comment]
Ah, so that's why it started to work.  I stopped spring to see my changes and then I couldn't replicate even after reverting.
