### ISSUE TITLE
Pressing return in any text field on the new user form in the backend reveals the password

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#476]
I'm not sure why this is happening. Pressing return doesn't seem to submit the form (it probably should). It does trigger my 1password input and the hidden password is revealed, which is odd.

**Comment by SMaxOwok** [comment]
I think three things are happening:
1. The onClick of the password button is being triggered, which is causing the password to toggle.
2. The form is being submitted, which triggers 1password when the password field is of `type=password`.  The type of that field is being changed dynamically between `text` and `password`.
3. The submit event is being caught by the onClick of the password button and stopped.

**Comment by SMaxOwok** [comment]
From w3:
>The missing value default is the Submit Button state.

Just need to explicitly state the button is a regular button. Fix incoming.

**Comment by SMaxOwok** [comment]
I ended up changing the button to a span, since it seemed like that made more sense mark-up wise.
