### ISSUE TITLE
Ingestion strategies are not detecting table of contents

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#477]
EPUB and markdown texts are being ingested without TextSections of `kind: "navigation"`.

The "View Contents" button on project page is not render as a symptom.

**Comment by SMaxOwok** [comment]
For markdown files this is a regression introduced by the stale section removal:
https://github.com/ManifoldScholar/manifold/blob/master/api/app/services/ingestor/strategy/abstract_builder.rb#L209

Still investigating epubs.

**Comment by zdavis** [comment]
I can take a look at this

**Comment by SMaxOwok** [comment]
Markdown can be fixed by added the summary to the spine:
```
  def spine_list
    list = []
    ingestion.readlines(summary_path).each do |line|
      next unless line.strip.start_with?("*", "-")
      path = clean_line(line)
      next unless ingestion.file?(path)
      list << path
     end
     list << File.basename(summary_path)
     list
  end
```

**Comment by zdavis** [comment]
Seems better to fix it where the texts are destroy:

```
      def remove_stale_sections(text)
        text.text_sections.each do |section|
          next if text.spine.include? section.id
          next if section.toc?
          next if section.cover?
          section.destroy
          info "services.ingestor.logging.remove_text_section", id: section.id
        end
      end
```
