### ISSUE TITLE
Footer subject bar in reader isn't positioned correctly

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#478]
![image](https://user-images.githubusercontent.com/255909/28799775-bea4a008-75fe-11e7-97b6-264bef6540a7.png)

Compare to comps.

**Comment by zdavis** [comment]
Hey @naomiyaki — could you please look at this today, before beginning on new markup? Thanks!

**Comment by naomiyaki** [comment]
You bet!

**Comment by naomiyaki** [comment]
Pull requested!
