### ISSUE TITLE
Resource list item thumbnails aren't showing in Firefox & IE Edge

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#483]
Only in Firefox

<img width="218" alt="screen shot 2017-08-01 at 1 35 13 pm" src="https://user-images.githubusercontent.com/8389445/28845947-84fdfc62-76be-11e7-97e6-e643d848b41f.png">
<img width="176" alt="screen shot 2017-08-01 at 1 35 26 pm" src="https://user-images.githubusercontent.com/8389445/28845948-8505e56c-76be-11e7-95d4-5d1b3a0cb726.png">

**Comment by SMaxOwok** [comment]
![screen shot 2017-08-04 at 2 12 21 pm](https://user-images.githubusercontent.com/8389445/28987227-3c327a36-791f-11e7-8264-74b528dfa8b2.png)

Has something to do with how FF interprets this padding.

**Comment by SMaxOwok** [comment]
https://drafts.csswg.org/css-flexbox/#item-margins

**Comment by naomiyaki** [comment]
This is blocked by #630

**Comment by zdavis** [comment]
#630 has been resolved.
