### ISSUE TITLE
Update hero layout with draft button, streamlined makers list

### ISSUE THREAD

**Issue by naomiyaki** [ManifoldScholar/manifold#501]
![gpu preview 2017-08-03 13-38-43](https://user-images.githubusercontent.com/1628239/28942688-21be2b88-7851-11e7-9ca2-c9e791afeed9.png)

**Comment by naomiyaki** [comment]
@zdavis I need the draft feature to be merged to complete! Please have a look and merge when ready.

**Comment by zdavis** [comment]
@naomiyaki that feature has been merged to master, so you should be unblocked on this.

**Comment by naomiyaki** [comment]
Squashed and pushed!
