### ISSUE TITLE
Remove normal font-weight declarations from ingested texts

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#507]
The Manifold reader decides what's "normal," not you. We should strip default declarations of font-weight so Manifold can render sane defaults.

**Comment by tsmyre** [comment]
This is actually causing a problem for me on an upcoming project, which I've loaded [on Edge here](edge.manifoldapp.org/read/untitled-d5869498-2c50-4253-a288-8db843fd0765/section/aef0439e-ebb0-4df7-8f4a-c19b68cb547d).

Specifically, Manifold is retaining bold when context requires the weight to return to normal as shown in the second image below.

<img width="1637" alt="gabrys" src="https://user-images.githubusercontent.com/25825222/61568421-d1753f00-aa48-11e9-973b-22f7cd6c49a8.png">

<img width="667" alt="gabrys2" src="https://user-images.githubusercontent.com/25825222/61568480-113c2680-aa49-11e9-97c9-28fea3f9aa11.png">

Adding a stylesheet after ingest also doesn't correct the issue, though that doesn't feel like the right approach when I was explicit at the outset.
