### ISSUE TITLE
Correct category footer display issues in reader.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#526]
![image](https://user-images.githubusercontent.com/255909/29339877-383e331a-81d1-11e7-8a3b-09f12956970f.png)

![image](https://user-images.githubusercontent.com/255909/29339887-49da0ce8-81d1-11e7-8336-aeb8319b2e97.png)

**Comment by naomiyaki** [comment]
@zdavis Pull request made!
