### ISSUE TITLE
Long title in resource list should be wrapped or cropped

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#539]
![image](https://user-images.githubusercontent.com/255909/29460141-ace2c580-83db-11e7-8683-0c379cfac712.png)

**Comment by naomiyaki** [comment]
I settled on truncating these. My feeling about this UX is that a single line preview is likely sufficient, and a tall resource name can take up a lot of room in this UI. But it's easy enough to go back to multiline if we need to. Note that this applies to resources and collections in the sidebar.

To that end: in the backend, where resources are chosen to be included in collections, I've set these titles to wrap. There's much more horizontal space, so a long name takes up far less height.
