### ISSUE TITLE
Switch style linting to Stylelint

### ISSUE THREAD

**Issue by naomiyaki** [ManifoldScholar/manifold#545]
Style linting is currently done with sass-lint and happens completely separately from Webpack/Asset compilation.

Time to switch to style lint so that we can lint (and autofix!) with a commit hook.

I think can take care of the node/Webpack work, but I'm worried about how this will work with CI. @zdavis Because Stylelint and Sass-lint are fundamentally different systems, the config and rules aren't quite compatible (though we are using them very similarly). Can we setup CI to use stylelint too?

**Comment by zdavis** [comment]
@naomiyaki It looks like Hound CI supports stylelint. See https://github.com/houndci/hound/pull/1334/files.

How do you declare your stylelint rules? Is it in a .stylelintrc.json file? I doubt hound will see them if they're wrapped up in webpack, but if they're in a separate file that it can read, and if you add config to the .hound.yml file in the root of the project (which is also where you'll turn off scss linting), then it might just work.

Even if we can't get hound to work, I'm fine with you switching from sass-lint to stylelint, if that gives you a better developer experience. Developer experience is more important to me than ensuring that the CI runs style lints.
