### ISSUE TITLE
rake development:load crashes

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#562]
```rails aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'purchase_version_label' for Project.```

**Comment by zdavis** [comment]
The most recent migration changes this field. Please go ahead and adjust it in the data loader too.

**Comment by SMaxOwok** [comment]
Actually, it looks like this is an issue in each project's `project.json`.  The line that's throwing the error is https://github.com/ManifoldScholar/manifold/blob/master/api/app/services/importer/project.rb#L48.  Changing `purchase_version_label` to `purchase_call_to_action` in `project.json` lets import run  correctly.
