### ISSUE TITLE
Reduce person picker UI on mobile

### ISSUE THREAD

**Issue by naomiyaki** [ManifoldScholar/manifold#591]
Something should be done to make this input more readable. I'd love to get rid of the "Create New" button on mobile, because pressing "return" should do this anyway, but we might want a little static tooltip to be there so users know about that.

What do you think @laelito @zdavis ?

![manifold scholarship 2017-09-14 13-38-10](https://user-images.githubusercontent.com/1628239/30454668-f47e3a38-9951-11e7-92c8-9f0b79fb1642.png)

**Comment by zdavis** [comment]
I agree that we can lose the "create new" on mobile.

**Comment by naomiyaki** [comment]
This has been addressed in the above mobile styles picker #622
