### ISSUE TITLE
Ingestion uploader is not responding to files

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#609]
Regression introduced with https://github.com/ManifoldScholar/manifold/commit/208690ff29f45e5a9610473bde0750aa223560ca

**Comment by zdavis** [comment]
@SMaxOwok Please fix today if possible. I noticed another related issue and fixed in b3b18b5a344c830fa551efc8f1185c51ff024b23

**Comment by zdavis** [comment]
See #614 — I took a stab at this, which may fix it. I'm also noticing that despite the instructions on a markdown ingestion, uploading a "single markdown file" doesn't seem to work. Please test my branch carefully and review each ingestion type for related (or unrelated) issues.

**Comment by zdavis** [comment]
And feel free to add to or change the zd/609 branch

**Comment by SMaxOwok** [comment]
Closing as #614 fixes this and was merged in
