### ISSUE TITLE
Users can remove their highlights from a text

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#618]
![image](https://user-images.githubusercontent.com/255909/31089371-a63b5170-a758-11e7-9a9f-45895b1550c7.png)

Naomi — just do the markup in a branch. I will follow up with development to make it functional. Thanks!

ZD

**Comment by zdavis** [comment]
(See Manifold_UI_Reading_ALL_v1.6 for the design and notes on the functionality)

**Comment by naomiyaki** [comment]
@zdavis I've pushed the markup to a branch here: https://github.com/ManifoldScholar/manifold/tree/nr/618

Please let me know if you need anything else from me on this!
