### ISSUE TITLE
Improve margin between label and input on all backend form fields

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#641]
Current:
![image](https://user-images.githubusercontent.com/255909/31616895-d0dbabc4-b242-11e7-8632-3b0a732e79e9.png)

Per comps:
![image](https://user-images.githubusercontent.com/255909/31616914-d917b4d6-b242-11e7-8097-ff6c826aacde.png)

**Comment by SMaxOwok** [comment]
@naomiyaki, I've adjusted the label margins as we spoke about.  https://github.com/ManifoldScholar/manifold/commit/098ce17823f2e27d54db95124bab660f9f7f56ca reflects the changes.

Would you mind taking a pass over those as well as commenting on how you would approach the `.has-many-list`?  There are several states it could be in: with images, without images, without results.  These screenshots are as they appear now in `mo/641`.

![screen shot 2017-11-28 at 4 58 13 pm](https://user-images.githubusercontent.com/8389445/33352542-3dbdb2ae-d45e-11e7-844c-4b4cfb784e33.png)
![screen shot 2017-11-28 at 4 59 36 pm](https://user-images.githubusercontent.com/8389445/33352544-3dcf7b56-d45e-11e7-8fd5-ac18e4bff402.png)

**Comment by naomiyaki** [comment]
Thanks Max, I'll try to have a look at this today.

**Comment by zdavis** [comment]
@naomiyaki @SMaxOwok I've already address all of this in a branch that I'm about to merge. Sorry I didn't mention it. I just knocked it out real quick while I was working on something else.

**Comment by naomiyaki** [comment]
Oop, thank you @zdavis ! Please let me know if you need a review of any kind.
