### ISSUE TITLE
Metadata Fields / Markdown

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#674]
Not all of the metadata fields in the backend presently support markdown formatting (e.g., those concerning copyright). We'll want to be able to use such formatting to properly style titles, etc.

**Comment by zdavis** [comment]
Yeah, when you're right you're right. I don't really want to do this, because it will involve refactoring the concern that handles the markdown transformations and caching, but it's clearly needed, so I'll just bite the bullet.
