### ISSUE TITLE
After login, successful login alert should disappear without user intervention

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#676]
Right now, when one logs into a Manifold installation, an alert appears that says that the user has successfully logged in. In order to get rid of it, one has to dismiss the alert.

I think the convention of logging in is well-understood enough that the alert either shouldn't appear at all or, ideally, should appear for a few seconds before disappearing on its own. YMMV.

**Comment by zdavis** [comment]
Currently it goes away after 5 seconds. We can remove it altogether or reduce that timing. I believe 5 seconds is the default for most alerts.

**Comment by zdavis** [comment]
Let's just get rid of the alert. @SMaxOwok, please make it so.
