### ISSUE TITLE
Adding a profile picture with an upper case attachment fails silently

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#682]
When I am logged in and go to the "Edit Profile" option, I select a photo from my personal computer to upload, press save changes -- the status bar at the top indicates progress, and makes it all the way across-- but nothing closes and if I then attempt to return to leave the "Edit Profile" page, nothing has been saved. I have a webrecorder video of the issue, if that helps.
[saving-manifold-photo-20171219160100.warc.gz](https://github.com/ManifoldScholar/manifold/files/1572299/saving-manifold-photo-20171219160100.warc.gz).

**Comment by zdavis** [comment]
@SMaxOwok Could you please take a look at this? You can reproduce by giving a jpg file a .JPG attachment and uploading it as a profile picture. I suspect that this is happening everywhere we accept an attachment upload. Fixing this may be as simple as changing the extension regex to be case insensitive (https://github.com/ManifoldScholar/manifold/blob/master/api/config/manifold.yml#L272), but investigate and see what you find.
