### ISSUE TITLE
Markdown Endnotes

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#688]
For texts ingested as Markdown, the IDs for footnotes are being included alongside the note links in the text and notes section. e.g., 1 (/#fn1). See the [Foundations of Business project](https://private.demo.manifoldapp.org/read/94864d5d-f790-4d75-8970-2edc5273a03d/section/1c14baf6-b698-4ba8-bc6b-e276a3e4814a) on the private staging site for examples.

**Comment by SMaxOwok** [comment]
This appears to be an issue with the text's stylesheet.  

Line 256 in `website.css` has 
```
a[href]:after {
  content: " (" attr(href) ")";
}
```
which is adding a pseudo-element to the footnote containing the href.

![screen shot 2017-12-20 at 2 28 44 pm 2](https://user-images.githubusercontent.com/8389445/34231989-1949ee06-e593-11e7-92bb-41db9ab4bf83.png)

Removing that selector from the stylesheet will remove the extraneous links.  Closing this issue.
