### ISSUE TITLE
Resource card grid layout should be consistent across modern browsers

### ISSUE THREAD

**Issue by blnkt** [ManifoldScholar/manifold#690]
CORRECT IN CHROME
![screen shot 2017-12-20 at 11 47 41 am](https://user-images.githubusercontent.com/8166060/34225523-9af31bac-e57b-11e7-8dc8-a6e62d0cb2a4.png)

WRONG IN IE11
![screen shot 2017-12-20 at 11 35 39 am](https://user-images.githubusercontent.com/8166060/34225533-a4869aea-e57b-11e7-91cd-27cfb81da727.png)

**Comment by zdavis** [comment]
Fixed in 7065ad7ed63236deff1eded7e6c6437cddb40f89
