### ISSUE TITLE
Google product support in Resources

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#693]
Explore adding support for Google Docs, Sheets, and Slides in the `Document`, `Spreadsheet`, and `Presentation` resource types.

**Comment by zdavis** [comment]
@SMaxOwok Could we accomplish this using sub-types, similar to what we do with videos?

**Comment by zdavis** [comment]
I think this request should be folded into a broader re-thinking of resources, and I've tried to capture the gist of what you're asking for in #787. I'm closing this for now, and hope we can move discussion to #787, but if you feel this should stand on its own, please feel free to re-open this issue.
