### ISSUE TITLE
Users should be prompted to confirm before destroying an annotation

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#698]
Talking about the delete link here:

![image](https://user-images.githubusercontent.com/255909/34439952-9de2fa0c-ec66-11e7-98f4-283fc24d8a27.png)

**Comment by SMaxOwok** [comment]
Will be fixed in #677.

![confirmable](https://user-images.githubusercontent.com/8389445/34448628-08136c8a-eca4-11e7-9305-7cab2ce4f177.gif)
