### ISSUE TITLE
Fix broken links in Metagaming

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#704]
The URLs described in the print edition of _Metagaming_ aren't redirecting correctly and need to be adjusted as follows:

http://manifold.umn.edu/metagaming/
needs to redirect to
https://manifold.umn.edu/project/metagaming 

http://manifold.umn.edu/metagaming/games 
needs to direct to
https://manifold.umn.edu/project/fcc2bb4d-6a16-4fca-b6de-490dd4bd49da/collection/dd7d01e6-5dd7-41b9-b1d3-98819506bda9 

http://manifold.umn.edu/metagaming/triforce 
needs to direct to
https://manifold.umn.edu/project/fcc2bb4d-6a16-4fca-b6de-490dd4bd49da/collection/c30f1674-77df-4d50-a738-b068e00153c4 

http://manifold.umn.edu/metagaming/memento 
needs to direct to
https://manifold.umn.edu/project/fcc2bb4d-6a16-4fca-b6de-490dd4bd49da/collection/4c99c113-95c3-4c0e-814b-3eefaba30c36 

http://manifold.umn.edu/metagaming/pitchblack 
needs to direct to
https://manifold.umn.edu/project/fcc2bb4d-6a16-4fca-b6de-490dd4bd49da/collection/37bf019b-db26-4d9b-8488-5ba7cf80fdbb 

http://manifold.umn.edu/metagaming/99exercises 
needs to direct to
https://manifold.umn.edu/project/fcc2bb4d-6a16-4fca-b6de-490dd4bd49da/collection/b773eb57-a289-408c-a55a-ab8cc37268c3 

http://manifold.umn.edu/metagaming/tidehunter 
needs to direct to
https://manifold.umn.edu/project/fcc2bb4d-6a16-4fca-b6de-490dd4bd49da/collection/69e5f05b-d6bc-4943-bda9-ccc81578cf08

**Comment by rclarkburns** [comment]
@tsmyre Redirects have been added and I tested each link to confirm redirect works as expected.

**Comment by tsmyre** [comment]
Perfect. Thank you so much, @rclarkburns !
