### ISSUE TITLE
Add back end fields and front end access for file variants

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#705]
For high res art and resources that have variants (Mac vs. PC builds) we need a place to load them into the back end and then surface them as options to view and download in the front. A working instance are the games from _Metagaming_. We have both Mac and PC builds for each in the back end folder on Google Drive but no way to showcase the PC versions at present.

**Comment by zdavis** [comment]
I think this request should be folded into a broader re-thinking of resources, and I've tried to capture the gist of what you're asking for in #787. I'm closing this for now, and hope we can move discussion to #787, but if you feel this should stand on its own, please feel free to re-open this issue.
