### ISSUE TITLE
Consider thumbnails for file resources

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#706]
For the landing pages of file resources, it might be useful to include thumbnail or audio/video fields that preview or describe the resource at hand.

**Comment by zdavis** [comment]
I think this request should be folded into a broader re-thinking of resources, and I've tried to capture the gist of what you're asking for in #787. I'm closing this for now, and hope we can move discussion to #787, but if you feel this should stand on its own, please feel free to re-open this issue.
