### ISSUE TITLE
Add image size guidance for hero images and other images in the Admin > Appearance tab

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#713]
I'm trying to create a text now, and it would be useful to know what the ideal proportions of a hero image should be. If one uploads a larger image, it gets cropped automagically but not necessarily where one would want.

I suppose an alternative would be to build an image cropping step into the image upload process.

**Comment by mkgold** [comment]
With "guidance," what I am thinking of is a bit of text to add in the parenthetical after this:

HERO IMAGE
The Hero Image is displayed at the top of the project landing page.

**Comment by SMaxOwok** [comment]
![screen shot 2018-01-22 at 2 53 34 pm](https://user-images.githubusercontent.com/8389445/35248896-b251d478-ff84-11e7-87f1-20b4e77883a9.png)
