### ISSUE TITLE
Issues with adding/creating/associating people

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#714]
Any field that prompts the user to add an author or add an associated user doesn't provide an option to select from accounts already existing in the people database; instead it just adds a new entry to the database.

**Comment by SMaxOwok** [comment]
Related to #716

**Comment by zdavis** [comment]
I'm unable to reproduce this; I think perhaps there was a problem with the index, which has been resolved. Or perhaps the lack of user feedback while the API is being queried makes it feel as though it's not working. I asked Terence to check again in Slack.

**Comment by zdavis** [comment]
Index on private demo instance was corrupted. Reindexing solved this issue.
