### ISSUE TITLE
broken footnote/endnote links

### ISSUE THREAD

**Issue by gwijthoff** [ManifoldScholar/manifold#764]
For footnotes:

While most Manifold projects use endnotes (i.e. linking to a separate section of the book), *The Perversity of Things* uses footnotes (linking to notes at the bottom of the page), and it looks like all footnote links are broken in the latest release of this particular project on Manifold.

For endnotes:

I did some digging in other projects that use endnotes, and it looks like endnote links do travel from chapters to the proper location in the endnotes section (for example [fn. 3 to the Introduction](https://manifold.umn.edu/read/72fb8acf-3f25-4ea4-a486-7a810ff81354/section/e339a80c-6709-4a6f-8f18-a83bd8bcd389#en3) of *Carceral Humanism*) but that link travels from fn. 3 in the endnotes back to the beginning of the Introduction, rather than the proper spot of the note in the text.

**Comment by zdavis** [comment]
Thanks for the heads up, Grant. We'll take a look at this and get a fix out soon.

**Comment by zdavis** [comment]
Thanks again for the bug report @gwijthoff. I've got a pull request in place that fixes this issue. I expect we'll get this fix out to manifold.umn.edu in the next day or so.

**Comment by gwijthoff** [comment]
Thanks Zach!

**Comment by zdavis** [comment]
FYI, this fix has been deployed to manifold.umn.edu.
