### ISSUE TITLE
Adopt a new process for handling feature requests

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#772]
I'd like to propose a new process for handling both internal and external feature requests.

Currently, our approach to feature requests is somewhat haphazard, and I think the project would benefit from getting a more formal process in place. Right now, feature requests come in via slack, in conversations on the phone, and from in-person meetings. It's difficult to keep track of them, and it's difficult for the people asking for the feature to see where it's at in the development process.

I propose that we handle all feature requests through Github issues, and that our workflow for feature requests is as follows:

1. The person who wants the feature, hereafter referred to as the "owner" of the feature, opens a github issue.

2. The github issue is given a succinct title. The body of the issue follows a specific template (which I will configure github to automatically drop in the body of the issue). This template is split into the following sections: 1) Why do we need this feature, 2) Brief description, 3) User Stories, 4) Design notes, and 5) Development notes. To open a feature, the owner needs to at least speak to #1 and #2. 

3. The github issue is assigned a "feature request" label and an "under discussion" label.

4. The team discusses the issue on github and through the discussion process, we finalize the description until it's actionable. During this discussion period, team members (or the public) can respond to the issue with "thumbs up" or "thumbs down" to signify general support or lack of support for the issue.

5. During our regularly scheduled calls we briefly review  feature requests and check in on the status of each. Based on votes and discussion, we decide whether to proceed with the issue or not. If there's a lack of activity or interest, we close it. If we agree to proceed, we add an "accepted" label to the issue and discuss where to put it on the roadmap.

6. Accepted issues are assigned to versions on the roadmap, and design/development proceeds when appropriate.

I think this process will help in the following ways:

- It puts a little more burden on the owner to articulate the feature and explain why it's important
- It gives us a public, shared record of these requests and introduces transparency into the process
- It forces CIC to spec and scope the issue before sending it to design, so the owner is more likely to get what he/she wants
- It leads to an articulation that can act as a brief for both design and development.
- It creates a record of the request that can be easily added to the roadmap and makes it clear to everyone which version will include the feature
- It provides more structure to the development portion of our regular call

Thoughts?

**Comment by zdavis** [comment]
I've setup issue templates for features and bugs, and updated the README that shows at https://github.com/ManifoldScholar/manifold to include links to open new issues using these templates:

https://github.com/ManifoldScholar/manifold/issues/new?template=bugs.md
https://github.com/ManifoldScholar/manifold/issues/new?template=features.md

**Comment by mkgold** [comment]
This is a great idea

**Comment by zdavis** [comment]
My sense from our call was that there were no objections to this approach. Closing this issue.
