### ISSUE TITLE
Compose resources from smaller components, rather than strictly defining types

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#787]
## Feature Description
The purpose of this issue is to track a set of improvements to resources that we might want to tackle at once in a future release. Resources display in five principle ways: 1) as a slide in a collection slideshow, 2) as a card in a resource list, 3) in an overlay within the reader, 4) as a marginal note in the reader, and 5) on its detail page. Currently, we have some switching logic that changes the display of each mode depending on the resource kind and sub-kind. Some degree of switching logic is necessary, because we have to make choices about what to display. In the hero on the detail view, for example, we can't really show both a video and a file download link.

That said, I think it would be wise to move toward a system where we come up with a more systematic approach. For example, it might make sense to build resource "hero" models that can be of a fixed number of types: video, audio, or image, for example. It might make sense to allow any resource to have any kind of hero—that way, a file resource (say, a downloadable .exe of a video game), could be accompanied by a video hero that showed an example of the game play. I think it would also make sense to expose the thumbnail field across all resources and have it work in a consistent way. I think we ought to offer downloadable attachments on all resources, not just on ones that are specifically meant to be downloaded. We might also want to consider treating links the same as attachments. That is, as add-ons that can be included with any resource and that display if present. With a more flexible approach to attachments and links, we should be able to get to a place where a "spreadsheet" resource could be either an attached Excel file, or a linked Google Sheet.

## *Why* is this feature important? *Who* does it help?
We want to fully support authors and presses, and a wide variety of resources. The constraints of the current approach seem arbitrary in places.

## User Stories
The following stories are not meant to be exhaustive. Rather, they attempt to capture some requests that have come on in relation to this issue.

- As an admin or author managing resources...
    -   I can add a thumbnail to a file resource.
    -   I can include a video or audio preview on a file resource.
    -   I can offer multiple attached files for download on any resource kind.
    -   I can link spreadsheet resources to google sheets, documents to google docs, etc.

**Comment by tsmyre** [comment]
As part of this revised approach, I think it would be useful to have variants made available for File Resources (or perhaps for all resource kinds generally). In situations where authors have prepared apps for different operating systems, it would be nice to be able to provide any alternatives that exist as part of the same resource instead of creating secondary ones. Having custom thumbnails available to those variants would useful as well in situations where it is important to distinguish between file types in visual mannger (e.g., the Apple logo against the Linux penguin).

**Comment by tsmyre** [comment]
An additional use here would be able to include source files for Interactive resources that can't natively be rendered on the platform and which are relying on a third party to allow readers to explore them. If that third party fails in some way then at least the source files remain available to the community.
