### ISSUE TITLE
EPUB Ingestion: Transforming empty text_section throws exception

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#803]
We attempted to upload the ePUB of William James's Psychology (http://www.gutenberg.org/ebooks/55262) Gutenberg file (the "ePub with Images) and ran into a "no nodes error message. 

this occurred on cuny.manifoldapp.org

**Comment by zdavis** [comment]
I'm able to reproduce. Investigating. It's another character set issue.

14:57:50 cable.1     | output error : unknown encoding ASCII-8BIT

**Comment by zdavis** [comment]
I have a fix for this in dev. Writing tests to support it, and will release to v0.4.x
