### ISSUE TITLE
Closing Resource modal resets view

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#823]
When you close a Resource modal in the Reader, the view is reset to the top of the section instead of taking you back to the place where the resource was clicked.

**Comment by zdavis** [comment]
Hmm.. I could have sworn we'd fixed this. What instance of Manifold are you seeing this on?

**Comment by tsmyre** [comment]
Our production site: https://manifold.umn.edu/

**Comment by zdavis** [comment]
Do you have a URL where this is occurring? For example, on this page, the resource overlay works as I'd expect it to:

https://manifold.umn.edu/read/metagaming/section/00d65eb7-926c-4159-9d95-5fee5285e7b8

**Comment by tsmyre** [comment]
I do: https://manifold.umn.edu/read/c5926868-00c4-45f8-8e91-45cfd9140a87/section/00d65eb7-926c-4159-9d95-5fee5285e7b8#ch01

That points to the same page, but with that URL, which I accessed from [this page](https://manifold.umn.edu/read/metagaming/section/50eda481-7722-4de0-abb8-3bf771d143d0), the experience is different.

**Comment by zdavis** [comment]
There is another regression at play here now, which is causing the problem for all URLs, regardless of whether or not there is a hash in the URL. Working on a fix.
