### ISSUE TITLE
IE: Table of contents overlap issue

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#826]
![image](https://user-images.githubusercontent.com/8389445/36874186-d9f322b8-1d5f-11e8-88a0-ae8c0b94af7b.png)

Quick look suggests the tag `list-style-type: none;` on the contents is the culprit for IE.  The list element is showing the numbers, which are overlapping the text.

**Comment by zdavis** [comment]
Seems like it's an issue with the EPUB styles, not Manifold per se?

**Comment by SMaxOwok** [comment]
Maybe...

![screen shot 2018-03-13 at 4 35 39 pm](https://user-images.githubusercontent.com/8389445/37375406-b44dadb8-26dc-11e8-9466-b67842123079.png)

**Comment by zdavis** [comment]
That’s on them not us. Close it!

**Comment by SMaxOwok** [comment]
Closing as this is an issue with the EPUB
