### ISSUE TITLE
Unclear action label in reingest section

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#830]
I was re-ingesting a text and found that one of the labels "RESET" is very unclear. I have no idea what clicking that link would do -- reset to what state/version? Can we try to clarify? Screenshot attached.
![screen shot 2018-03-07 at 9 53 13 am](https://user-images.githubusercontent.com/278503/37099323-fd23f658-21ed-11e8-9fc2-29cd724161c1.png)

**Comment by zdavis** [comment]
Clicking that will reset the ingestion, and allow you to restart the ingestion. It's not super useful, but ingestions do have a permanent URL, so it's possible to deploy a fix and then retry an ingestion, and that button is definitely useful to us as developers. I'm totally open to suggestions for better UX here.

**Comment by mkgold** [comment]
RESTART INGESTION?

I guess I also find it weird that it appears under the text title; it seems like it would make sense for that action button to appear under the LOG, where other action-oriented buttons appear

**Comment by SMaxOwok** [comment]
![screen shot 2018-03-13 at 3 18 26 pm](https://user-images.githubusercontent.com/8389445/37372918-d3f6a5ee-26d1-11e8-84d3-353a44fcc968.png)
