### ISSUE TITLE
Feature Request: Email notifications and Email Notification Preferences Page

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#838]
I think we should have a configurable set of email notifications associated with various roles. 

As an administrator of an instance, I would like to be notified by email when someone creates a new project or adds a new text to a project. I would like to choose whether to be notified about new project comments and annotations, with digest report options. I want these notifications as an admin so that I am aware of what content is being added to an installation

As an author, I would like to be notified of comments and annotations, with digest report options. I want these notifications because I want to be able to engage people who leave comments and to support activity on the text. And also because I am an author and I love to hear about people engaging my work!

Building this out would involve also building out a notification preferences page.

**Comment by SMaxOwok** [comment]
Closing in favor of #951, which is in progress.
