### ISSUE TITLE
Recently updated project not appearing in list of recently updated projects

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#845]
Steps to reproduce:

1. Create a project
2. Shouldn't it appear in "recently updated"?
3. Update the project
4. Shouldn't it appear in "recently updated"?

**Comment by SMaxOwok** [comment]
source of bug is `with_order` applied here: https://github.com/ManifoldScholar/manifold/blob/master/api/app/controllers/api/v1/projects_controller.rb#L15
