### ISSUE TITLE
Update association dependent behavior

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#847]
We have a number of associations that rely on their `belongs_to` association in more than one way.  In a lot of places we don't have any kind of behavior defined for when the parent record is destroyed.

Quick example is a user's annotations.  If a user makes annotations and is then destroyed, trying to view the annotation on the frontend will error out.

Probably warrants a pass over all records on the backend to define dependent behavior, on the frontend to handle these cases, or some combination of the two.

**Comment by zdavis** [comment]
In all but a few cases when we destroy a model, we want to destroy it's has_one and has_many relationships. I can go through the models and add these in pretty quickly.
