### ISSUE TITLE
Reader has white bar at top in dark mode.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#848]
I think it would be nice if the reader header was also dark in dark mode, but that might be too difficult for this iteration. If nothing else, I'd like to remove the top white bar:

![image](https://user-images.githubusercontent.com/255909/37688709-a2119c04-2c5e-11e8-9872-f993e6e8b4d7.png)

**Comment by naomiyaki** [comment]
I fixed the regression in development. will spend a little time seeing if I can quickly apply the dark theme to the header and then push a PR
