### ISSUE TITLE
Category Page View

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#849]
## Feature Description
Right now, if one is on the homepage of a Manifold installation, we have a hero area, then featured projects, then all projects, with the ability to select a category. Once you select a category, the page reloads. There are two problems, as I see it, with the way it does this:

It reloads and brings the user from the midpoint of the page, where the category selection was made, back up to the top. at that point, the user has to scroll down again through the hero section and featured projects to get to the category they wanted to view.

If it's not possible to filter categories without reloading the page, which would be ideal, I think we should have a special category page view that would a) not show the Manifold hero section and b) not show the featured projects section *unless* it is showing only featured projects within that category. 

## *Why* is this feature important? *Who* does it help?
When people select a certain category of project, they want to see projects from that category. Our current handling of this makes it difficult to actually see that without a bit of rigamarole.

Also, people may share the category page URL and we want projects in that category to be more immediately viewable.

## User Stories
a school is uploading theses and is using a category to group their projects together -- e.g. "School Name Thesis Projects." that category has a URL that the school will want to share. They don't want to see the Manifold hero section or featured projects across the installation that have nothing to do with them (especially on a Manifold install like CUNY's, where people are coming from 24 different schools). They just want to see projects within their category

## Design Notes
in the short term, I would like to see the current page reload to a mid-point on the page so that when you select a category, but are brought back to the all projects/categories section

I also think we will need a page header that shows the category as a header so that people will know what it is. We may also want to add a link to "show all projects" from that category page.

**Comment by zdavis** [comment]
This is relevant to #771, and should be considered as part of that issue. Closing and setting to wont fix for now, but we need to be cognizant of this as we work on #771.
