### ISSUE TITLE
User permissions not saving

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#870]
I created a user named `Project Creator` and tried assigning `Can Modify Project?` permissions to the _Little Women_ project, but the setting doesn't take.

**Comment by SMaxOwok** [comment]
Are you getting any console errors?

In Chrome: View -> Developer -> Developer Tools and the "Console" tab.

**Comment by tsmyre** [comment]
Yes. See below:

<img width="801" alt="screen shot 2018-03-27 at 1 50 28 pm" src="https://user-images.githubusercontent.com/25825222/37988206-f0b46e2e-31c5-11e8-9d0d-25d83db6b5ad.png">
