### ISSUE TITLE
Overlay buttons overlap form elements

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#876]
![screen shot 2018-03-27 at 3 16 36 pm](https://user-images.githubusercontent.com/8389445/37998135-4fa9364c-31d2-11e8-9429-05dd272d4822.png)

**Comment by zdavis** [comment]
Is this only at narrow widths?

**Comment by SMaxOwok** [comment]
I think so, but only because I believe that's the only way to visually replicate the issue.

**Comment by naomiyaki** [comment]
I can fix!

**Comment by naomiyaki** [comment]
Adjusted and ready!
