### ISSUE TITLE
Editors, project editors, and authors should be able to place resources in texts.

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#899]
So far as I can tell only Admins can presently place resources. I think we should extend that to the Editor and Project Creator Role as well as those with Is Project Author and Can Modify Project permissions. I could also see it for the Metadata permission, but I don't have strong feelings right now one way or the other.

**Comment by mkgold** [comment]
If you and the Press don't have concerns about permissions issues about authors with that scoped role adding resources, @tsmyre , I think this would be a good idea.

**Comment by tsmyre** [comment]
@mkgold This wouldn't be for them to load files into the system but to place already existing ones in texts.

**Comment by mkgold** [comment]
aha -- okay. thanks!
