### ISSUE TITLE
MD link support in metadata fields

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#914]
It would be good to have the ability to create links in discursive metadata fields, like `Caption`, `Description`, etc. in line with standard MD syntax: `[anchor](target)`.

**Comment by SMaxOwok** [comment]
@tsmyre where are you seeing the links not formatted correctly? This is something we currently support.

![screen shot 2018-04-02 at 2 45 02 pm](https://user-images.githubusercontent.com/8389445/38217866-afb2664c-3684-11e8-8275-eb3403d52664.png)


I have a feeling this is related to #919 and our usage of metadata properties app-wide.

**Comment by tsmyre** [comment]
@SMaxOwok I'm seeing it [here](https://demo.manifoldapp.org/project/war-of-the-worlds/resource/digital-book-history).

<img width="733" alt="screen shot 2018-04-02 at 4 52 38 pm" src="https://user-images.githubusercontent.com/25825222/38218130-62e8068e-3696-11e8-9292-0495d4ef82b2.png">
