### ISSUE TITLE
HTML Ingestion does not handle external link correctly.

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#916]
I created a new text (HTML ingestion) that contained a link in the title. The anchor appears as a link, but the [target is undefined](https://manifold.umn.edu/read/an-interview-with-professor-mareis-and-dr-allen-critical-media-lab/section/2421c365-8798-49f2-9da9-1dbc72d8bce8).

**Comment by zdavis** [comment]
Are you 100% sure the link target is right in the EPUB? Can you share the EPUB with me so I can investigate?

**Comment by tsmyre** [comment]
This was actually ingested by way of the HTML strategy. Here's the pertinent coding:

`<p class="ct">An Interview with Professor Claudia Mareis and Dr. Jamie Allen from the <a href="http://www.ixdm.ch/critical-media-lab/">Critical Media Lab</a>, Basel</p>`

**Comment by zdavis** [comment]
Ahh, OK, it's an external link. That's good to know. We should be able to solve this.

**Comment by zdavis** [comment]
Max, you should be able to pretty easily reproduce this in an HTML ingestion test case.

**Comment by tsmyre** [comment]
It looks like all external links are not working right now. They are all showing as undefined.
