### ISSUE TITLE
Filtering projects (via searchkick lookup) does not look at maker names.

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#917]
The backend search doesn't seem to be combing through author names and doesn't reveal any results when they are typed in.

**Comment by zdavis** [comment]
What is the URL where you're seeing this issue?

**Comment by tsmyre** [comment]
The URL is https://manifold.umn.edu/backend

Here's a couple screenshots to show what I mean:

<img width="441" alt="screen shot 2018-04-02 at 2 43 21 pm" src="https://user-images.githubusercontent.com/25825222/38212680-3d0a2c2e-3684-11e8-87dd-f0be39710b1f.png">

<img width="456" alt="screen shot 2018-04-02 at 2 42 17 pm" src="https://user-images.githubusercontent.com/25825222/38212654-2669e2de-3684-11e8-90ae-7c4b1bdca4a7.png">

**Comment by zdavis** [comment]
I've edited the issue title, as this issue is not specific to UMP. @SMaxOwok, we are, it seems, indexing the maker names. My index for a project shows, for example:
```
{
"_index": "projects_development_20180325164235322",
"_type": "project",
"_id": "a580cd8b-6c5b-4046-9034-f391a41b718c",
"_score": 1,
"_source": {
"title": "A Voyage to Arcturus",
"body": "On hearing the title A Voyage to Arcturus, one might picture an astronaut strapping themselves into a rocket and flying into space for a swashbuckling adventure.  Nothing could be further from what this book actually is.",
"featured": null,
"maker_names": [
"David Lindsay"
],
"text_titles": [
"A Voyage to Arcturus"
],
"subject_titles": [],
"hashtag": null,
"publication_date": null,
"metadata": {},
"hidden": false
}
},
```
