### ISSUE TITLE
Hide project list if there are none

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#920]
Not sure if this is a functionality bug or just something we didn't notice.

It seems like the projects grid should not render if there aren't any.  That or leave the container, but render it completely empty (no title/filter).

<img width="1404" alt="screen shot 2018-04-02 at 8 57 17 am" src="https://user-images.githubusercontent.com/8389445/38217356-efad9fde-3682-11e8-86cd-f6749de7d5b5.png">

**Comment by zdavis** [comment]
@laelito It'd be good to show some kind of message when no projects are present on a Manifold instance. This will very rarely happen—really only on a new installation. Ideally, the message would invite users to login to the backend and create their first project. Can you give us a quick design on this?

**Comment by zdavis** [comment]
Paging @laelito.

**Comment by laelito** [comment]
Hey Manifoldians, would something like this get the job done?

[No Projects Message v1.pdf](https://github.com/ManifoldScholar/manifold/files/1904897/No.Projects.Message.v1.pdf)

**Comment by laelito** [comment]
aaaand, it looks like github doesn't wanna preview PDFs in-line, so here's a JPEG screengrab of the relevant design chunk.

![no projects message screengrab](https://user-images.githubusercontent.com/26985828/38703216-788ff370-3e57-11e8-9793-1560f2e5aa88.jpg)

**Comment by mkgold** [comment]
Looks nice to me!

**Comment by zdavis** [comment]
I think this design is good to go. @laelito, please add to CIC South dropbox when you have a chance. Thanks.

**Comment by laelito** [comment]
Posted.
