### ISSUE TITLE
Update errors on several components

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#925]
>Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

`Event.Event`
`ResourceListSlideCaption`

**Comment by SMaxOwok** [comment]
These are being caused by dynamic requires

``` 
componentDidMount() {
  import(/* webpackChunkName: "autolinker" */ "autolinker").then(
    autolinker => {
      this.setState({ autolinker });
    }
  );
}
```

**Comment by SMaxOwok** [comment]
@zdavis it seems like importing these modules as we do normally resolves the warnings and preserves functionality.

Is there a reason why the above pattern is being used over something like
`import { autolinker } from "autolinker";`?

**Comment by zdavis** [comment]
Yes. We're using code splitting to avoid pulling in libraries until they're needed. It's not a big deal with this one, but with things like the code editor, it makes a huge difference in our bundle size.

I can tackle this as part of a larger attempt to split apart the bundle.

**Comment by zdavis** [comment]
This approach works for me. Thanks!
