### ISSUE TITLE
Warn users when they might create duplicate maker records.

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#928]
It's possible to have two maker records with the same name. That can be a bit confusing if you create one, forget, and create another without seeing the existing one in the system. Or if one comes in through metadata. It would be useful to have a prompt of some kind to warn the user that there is already a maker record when entering a new name.

**Comment by zdavis** [comment]
I agree that this would be useful, but it would be fairly time consuming to implement, and I don't see us getting to it with current funding. Closing, but happy to reopen in the future.
