### ISSUE TITLE
Resource carousel slide artifacts

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#933]
![resource_slides](https://user-images.githubusercontent.com/8389445/38337067-d983d218-3818-11e8-8ddc-30fb02dfb786.gif)

Chrome ^

**Comment by naomiyaki** [comment]
OK! Will try to adjust the transition here.

**Comment by zdavis** [comment]
Huh. How have we not seen that? I looked at this recently.

**Comment by zdavis** [comment]
@naomiyaki Could you look at this today, please? Thanks!
