### ISSUE TITLE
Presentation File Upload Fail

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#936]
When creating a new Presentation resource the system throws the following error when I load either a PPT or PPTX file: `Attachment is invalid presentation file.`

**Comment by SMaxOwok** [comment]
```
[6] pry(main)> MimeMagic.by_magic(File.open("/Users/mono/Downloads/test.pptx"))
=> #<MimeMagic:0x00007fd056612f00 @mediatype="application", @subtype="vnd.openxmlformats-officedocument.presentationml.presentation", @type="application/vnd.openxmlformats-officedocument.presentationml.presentation">
[7] pry(main)> MimeMagic.by_magic(File.open("/Users/mono/Downloads/manifold.pptx"))
=> #<MimeMagic:0x00007fd0564d0728 @mediatype="application", @subtype="zip", @type="application/zip">
```

This appears to be an issue with office document file types created outside of MS Office.
https://github.com/minad/mimemagic/pull/52/commits/3d23f6532a893f0dd3762da2ee0a5560f1c0dc76

We'll need to consider how best to handle this.

**Comment by zdavis** [comment]
We can update the allowed mime types for these files to include `application/vnd.openxmlformats-officedocument.presentationml.presentation` and `application/zip`
