### ISSUE TITLE
Sort users feature

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#941]
## Feature Description
As Manifold installations grow and gain lots of users, it might be nice to be able to sort the list of users. I would like to be able to do that by role, so that, for instance, I could see everyone with an admin account together, but maybe also by name

## *Why* is this feature important? *Who* does it help?
It will help admins organize their installation and in particular will make it easier to change roles

## User Stories
An admin realizes that people with the role Project Creators should actually be classified as editors. Rather than going through the list and picking out names individually, if the admin could sort by role, it would make it easier to find everyone currently characterized as Project Creator

**Comment by zdavis** [comment]
Agreed, and easy to add. We certainly have design for filtering these kinds of lists:

![image](https://user-images.githubusercontent.com/255909/38432067-24420b5e-397b-11e8-91ea-6e635f0c7a08.png)

**Comment by tsmyre** [comment]
Would there be a chance such changes could be made in mass, e.g., I select five users and change all of their roles in one go?

**Comment by zdavis** [comment]
I think it would be a different feature altogether, with a different
interface. I’m also not sure how often this would need to happen, so I’d
put it low on the list of features to develop, but others might disagree.

**Comment by mkgold** [comment]
thanks, @zdavis @SMaxOwok ! And Terrance, please do start a separate feature request for user management / multiple selections

**Comment by SMaxOwok** [comment]
I'm adding the design label and @laelito per my comment in #949. In regards to sort buttons, we don't have design and need a way to distinguish them from the row of filters.

**Comment by laelito** [comment]
here's what we're thinking for the filtering/sorting feature.

![screen shot 2018-04-13 at 3 47 23 pm](https://user-images.githubusercontent.com/26985828/38760691-0c6996e8-3f32-11e8-9f4a-f5c08f19a5b8.jpg)

**Comment by zdavis** [comment]
And for sorting, we'd include both ascending and descending options in the list. For example:

![image](https://user-images.githubusercontent.com/255909/38760730-4ca19152-3f32-11e8-844c-2d6d30ab3194.png)

**Comment by laelito** [comment]
and here's a more detailed PDF. the idea being that we just use a text label to differentiate between the filtering options and the sorting options. we looked at a variety of possibilities, but opted for this very clean and, hopefully, straightforward approach.

[Backend Sorting v1.pdf](https://github.com/ManifoldScholar/manifold/files/1909688/Backend.Sorting.v1.pdf)

**Comment by zdavis** [comment]
When Naomi is back next week, we should put our heads together about how to style the dropdowns. I know that we always resist straying from browser selects (for good reason). However, I think Matt's request in #942 is going to lead to us building a custom dropdown anyway, and if that's the case, we might want to use that across the board. Let's talk it over.

**Comment by laelito** [comment]
I heart custom dropdowns.

**Comment by zdavis** [comment]
Yes, we'd use the same approach for users!
