### ISSUE TITLE
Select User is actually search for user

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#942]
In a project permissions tab, the text in the search box reads "Select Users." but it is actually a search interface, not a selection interface. I think it would be nice, actually, if one *could* select from a list of actual users on the site, as otherwise one needs to remember who to grant permissions to and that can be difficult. In a case I just dealt with, I had a draft project and wanted to set permissions for it but couldn't remember whether the person behind it actually had a Manifold account on this instance. The select user interface as it stands wasn't much help since it didn't show which users had accounts on the platform.

I think that it would be great if there was some kind of autofill, as there is now, but also that one could bring up a full list of users

**Comment by zdavis** [comment]
This probably involves replacing or refactoring the has_many client form input. Max, I can discuss this with you when you're ready.
