### ISSUE TITLE
Correct resource import mapping delete button styles

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#953]
![screen shot 2018-04-10 at 11 32 11 am](https://user-images.githubusercontent.com/8389445/38576437-00cc3a24-3cb3-11e8-8124-85a7b4860dbf.png)

**Comment by SMaxOwok** [comment]
Less important, but the cancel icon covers the text on mobile and looks a little unfinished/lacking polish.  Might be good to fade the text or truncate it or something.

![screen shot 2018-04-10 at 11 50 48 am](https://user-images.githubusercontent.com/8389445/38577357-834a40a2-3cb5-11e8-9ec2-71b5eb47cd6d.png)

**Comment by naomiyaki** [comment]
Thanks for these! I'm putting myself on this issue in case I can address.

**Comment by zdavis** [comment]
Great! Yes, please do tackle these.
