### ISSUE TITLE
Bulk Load CSV Error

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#963]
When I save an Excel Spreadsheet as a CSV and try to use it in the bulk load process I get the following error.

I'll DM @zdavis with the spreadsheet and Drive folder ID on Slack.

<img width="937" alt="screen shot 2018-04-12 at 1 11 22 pm" src="https://user-images.githubusercontent.com/25825222/38695850-1aee3e56-3e53-11e8-9065-c7a7c99b7ef5.png">

**Comment by SMaxOwok** [comment]
Noticed this too, Excel inserts some bad characters

```
numbers
— en,United States — US,,,klingon; ferengi; picard; federation,,,,,,

excel
äóî en,United States äóî US,,Test,klingon; ferengi; picard; federation,,,,,,
```
