### ISSUE TITLE
Async component load is causing some issues with Slideshow.Caption

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#972]
SSR mismatch on collection page, messed up HTML nesting

Missing button on reader collection

**Comment by SMaxOwok** [comment]
More context for this bug -- `Slideshow.Caption` does not have a re-render triggered when `Velocity` is loaded.  The functionality is in place and works, but the refs that are children of the `VelocityComponent` are still undefined.  This messes up our check to apply the expandable classes where necessary.

This fixes the issue, but is mostly a hack/workaround, so I think we should look more closely at properly resolving this.

```
const Velocity = Loadable({
  loader: () =>
    import(/* webpackChunkName: "velocity-react" */ "velocity-react").then(
      velocity => velocity.VelocityComponent
    ),
  render(Component, props) {
    if (!props.reference.state.velocityLoaded) {
      props.reference.setState({ velocityLoaded: true });
    }
    return <Component {...props} />
  },
  loading: () => null
});

class ResourceSlideCaption extends Component {
  render() {
    const animation = {
      animation: {
        height: this.state.expanded ? this.state.targetHeight : "3em"
      },
      duration: 250,
      complete: () => {
        if (this.state.expanded) {
          this._description.style.height = "auto";
        }
      }
    };

    return (
      <Velocity {...animation} reference={this} >
        {stuff}
      </Velocity>
    );
  }
}
```

**Comment by SMaxOwok** [comment]
@zdavis thoughts?

**Comment by zdavis** [comment]
I don't really have insight as to how to best fix this without digging into it. If what you've proposed is the best solution you can come up with, and it addresses the issue, I think you should proceed with it. Perhaps include a comment explaining why it's less than ideal should we circle back to it.
