### ISSUE TITLE
File Variants for File Resources

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#976]
I think it would be useful to have variants available for File Resources. In situations where authors have prepared apps for different operating systems, it would be nice to be able to provide any alternatives that exist as part of the same resource instead of creating secondary ones.

**Comment by zdavis** [comment]
I'm closing this because I think it's already captured by the user stories in #787. I'd rather build out that issue than have a lot of more granular issues to deal with. I'd encourage you to recast this as a comment on #787 so we're sure to have a clear record of the request. Thanks!
