### ISSUE TITLE
Audio Resource formats

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#979]
Presently the tile associated with audio resources suggests only MP3 as a viable upload, but from [this](https://github.com/ManifoldScholar/manifold/blob/master/api/config/manifold.yml#L181), it should offer FLAC, MP3, WMA, WAV, MID, and OGG.

<img width="190" alt="screen shot 2018-04-17 at 1 19 17 pm" src="https://user-images.githubusercontent.com/25825222/38888670-03697b0e-4242-11e8-9a6a-2c5256e09a17.png">

**Comment by tsmyre** [comment]
Or perhaps there's a way to preference MP3 here as the only kind playable in the system while the others are acceptable for upload?

**Comment by zdavis** [comment]
No, I agree with your original assessment. The upload component needs to be modified to accurately report the file types it accepts in this case.
