### ISSUE TITLE
Add options for share feature

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#980]
When a passage is highlighted and the share button selected there are only two possible options: Cite and Twitter. For those who wish to share via other means, it would be good to have the ability to share directly with Facebook, by way of email, or to simply secure a link to the passage in question. This would be in line with general expectations for a share button and not privilege Twitter as the sole means of sharing from Manifold.

**Comment by zdavis** [comment]
We currently support facebook sharing. The Facebook integration needs to be in place for it to work, which it may not be in the instance you're looking at. Relevant code is here:

https://github.com/ManifoldScholar/manifold/blob/master/client/src/components/reader/Annotation/Popup/Secondary/Share.js#L105

I'm closing this, as it's more an issue of missing configuration on an instance (which I'm happy to help remedy) than an actual bug in the platform.
