### ISSUE TITLE
Default feature page responds poorly

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#990]
![hero](https://user-images.githubusercontent.com/8389445/38951906-d9fdd6e4-42fe-11e8-86d9-749e252e7a2c.gif)

I'm assuming this is a bug, feel free to close if expected/known.

**Comment by SMaxOwok** [comment]
@naomiyaki I'm happy to take this, but would appreciate your input on the best approach.

**Comment by naomiyaki** [comment]
If it's ok with everyone I'd like to take a try (can probably do it tonight or tomorrow) and then have Lael look at it!

**Comment by zdavis** [comment]
Please have at it @naomiyaki — hoping to push out a release in the next couple business days. Thanks!

**Comment by naomiyaki** [comment]
I'm going to try and address today!

**Comment by SMaxOwok** [comment]
This was closed with #1001
